alpha: 5.0
attention_enhancement_layers:
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
caption_prompt: Please describe this image in detail.
coco_annotations_path: /datasets/coco/annotations/instances_val2014.json
image_dir: /datasets/coco/val2014
max_images: null
max_new_tokens: 1024
model_name: llava_1.5_7b
model_path: /models/llava-1.5-7b-hf
output_path: outputs/chair_saliency_17.json
use_gift: true
visual_saliency_computation_layers:
- 17
