# Model configuration
model_name: "llava_1.5_13b"
max_new_tokens: 10

# Data paths
data_path: "pope_data.pkl"
output_path: "outputs/pope_llava_1.5_13b_outputs.jsonl"

# GIFT configuration
use_gift: true
visual_saliency_computation_layers: [10]
attention_enhancement_layers: [14, 15, 16, 17, 18, 19, 20]
alpha: 5.0
