# Model configuration
model_name: "qwen2_vl_7b"
max_new_tokens: 10

# Data paths
data_path: "pope_data.pkl"
output_path: "outputs/pope_qwen2_vl_7b_outputs.jsonl"

# GIFT configuration
use_gift: true
visual_saliency_computation_layers: [14]
attention_enhancement_layers: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
alpha: 4.0
