_target_: cellbridge.data.cluster.cluster_pipeline_leiden
_partial_: true
n_neighbors: 10
use_rep: ${rep.obsm_key}
metric: euclidean
target_cells_per_cluster: 40
label_key: leiden
neighbors_key: null
random_state: 0
