[general]
degree = 2
epsilon = 0.001 # Tolerance for squared error
delta = 0.2 
precision = 3 # Precision for the floating-point numbers
method = MULTIPLE_REGRESSION  # MULTIPLE_REGRESSION, SIMPLE_REGRESSION, FORWARD_SELECTION, EAGER_MILP, PYSR, GPLEARN, KAN
correctness = FUZZING # FUZZING or VERIFICATION or NONE
n = 20 # Number of data points
invariant_type = MIXED # Enforce invariant type, possible values: INT or REAL or MIXED
logger_level = 3

[forward_selection]
selector_initial_rate = 0.8
selector_decay_rate = 0.3
selector_parallel = True
selector_max_features = 7  # This will be dynamically determined in the script (=10 if DEGREE > 2 else 7)

[multiple_regression]
cross_validation = 3
regression_score = neg_mean_squared_error # neg_mean_squared_error or r2

[regression_refinement]
regression_refinement = True  # if True, then use the regression refinement algorithm

[regression_sample]
use_sample_rate = True  # if True, then we use the sample rate
sample_rate = 10 # if the number of data points is larger than this value, then we use the sample rate
sample_threshold = 50 # if the number of data points is larger than this value, then we use this number of data points

[equation_inference]
coeff_threshold = 0.01 # remove coefficients that are smaller than this value
use_cutoff = True  # if True, then we use the cutoffs
coeff_cutoff = 30  # remove equalities that are larger than this value
intercept_cutoff = 50  # remove equalities that are larger than this value

[milp]
enabled = False
solver = GUROBI # PULP, GLPK
objective_threshold = 1e-9
bound = 20
timeout = 1
parallel = True
warnings = False

[milp_sample]
sample_rate = 1.5
sample_threshold = 30
use_sample_rate = True

[full_milp]
strategy = AUTO # if ALWAYS, then use MILP from all data points for each pivot, if AUTO, then we use MILP from all data points for each pivot if the number of data points is less than SAMPLE_THRESHOLD
threshold = 9 # if the number of data points is less than this value, then we use MILP from all data points for each pivot

[milp_freq_refine]
enabled = False

[linear_solver]
enabled = False

[pysr]
timeout = 600

[reductions]
ugly_factor = 20 # remove equalities that have lots of terms and "large" coefficients

[z3]
timeout = 10 # in seconds
slow_simplify = False # simplify results, e.g., removing weaker invariants
consistency_check = False # if True, then we use the consistency check method

[reporting]
property_table_width = 70

[fuzzing]
timeout = 2 # in seconds

[verification]
is_close_for_float = True # if True, then we use the is_close function for floating-point numbers
civl_path = tools/CIVL-trunk_5906/lib/civl-trunk_5906.jar # relative to the root directory
; civl_path = tools/CIVL-1.22_5854/lib/civl-1.22_5854.jar

[limits]
limit_degree = 10 # if the degree is larger than this value, then we use this value

