problem:
  name: cell_diffusion
  sigma: 0.1
  d: 2
  x_0: [0.1, -0.1]
  x_T: [1.0, -0.1]
  T: 4.0

model:
  type: conservative
  dim_hidden: [128, 128]
  emb_dim_hidden: [64, 64]
  activation: gelu

bridge:
  base_drift: true    # non-conservative drift, so must include
  guiding_type: brownian
  decay_coeff: false
  sampler: euler

train:
  self_consistency: standard # standard, nodrift
  num_steps: 400
  num_outer_iterations: 1000
  num_inner_iterations: 1
  traj_batch_size: 64
  train_batch_size: 4096
  lr: 1.0e-3
  ema_rate: 1.0
  jacobian_method: euler
  beta_schedule: average
  ckpt_freq: 100
  seed: 0

plotting:
  plot_fn: plot_two_dim_trajectories