name: sigs
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - scipy
  - sympy
  - h5py
  - scikit-learn
  - pyyaml
  - tqdm
  - matplotlib
  - pip:
      - -e .
