unet_name: "xlarge"
model:
  class_path: sed.models.diffusion.sed.SED
  init_args:
    diffusion_model_config:
      unet_config:
        hidden_dim: [1536,1024,1024,768,512,512,256,256,128,128]
        dropout: 0.1
      input_mode: "sed"