unet_name: "medium"
model:
  class_path: sed.models.diffusion.sed.SED
  init_args:
    diffusion_model_config:
      unet_config:
        hidden_dim: [768,512,512,256,128]
        dropout: 0.1
      input_mode: "sed"