  
Group_BatchSize_Ablation:
  - setting_name: "Budget0.2_Init0.02_B5_LHS"
    total_budget_ratio: 0.2
    init_ratio: 0.02
    batch_size: 5
    init_strategy: "lhs"
  - setting_name: "Budget0.2_Init0.02_B10_LHS"
    total_budget_ratio: 0.2
    init_ratio: 0.02
    batch_size: 10
    init_strategy: "lhs"
  - setting_name: "Budget0.2_Init0.02_B15_LHS"
    total_budget_ratio: 0.2
    init_ratio: 0.02
    batch_size: 15
    init_strategy: "lhs"
  - setting_name: "Budget0.2_Init0.02_B20_LHS"
    total_budget_ratio: 0.2
    init_ratio: 0.02
    batch_size: 20
    init_strategy: "lhs"

  - setting_name: "Budget0.2_Init0.02_B1_LHS"
    total_budget_ratio: 0.2
    init_ratio: 0.02
    batch_size: 1
    init_strategy: "lhs"
 
 
# -----------------------------------------------
Group_Init_Ablation:

  - setting_name: "Budget0.2_Init0.02_B5_LHS"
    total_budget_ratio: 0.2
    init_ratio: 0.02
    batch_size: 5
    init_strategy: "lhs"

  # - setting_name: "Budget0.2_Init0.02_B5_RAND"
  #   total_budget_ratio: 0.2
  #   init_ratio: 0.02
  #   batch_size: 5
  #   init_strategy: "random"

  # - setting_name: "Budget0.2_Init0.05_B5_LHS"
  #   total_budget_ratio: 0.2
  #   init_ratio: 0.05
  #   batch_size: 5
  #   init_strategy: "lhs"

  # - setting_name: "Budget0.2_Init0.05_B5_RAND"
  #   total_budget_ratio: 0.2
  #   init_ratio: 0.05
  #   batch_size: 5
  #   init_strategy: "random"

  # - setting_name: "Budget0.2_Init0.1_B5_LHS"
  #   total_budget_ratio: 0.2
  #   init_ratio: 0.1
  #   batch_size: 5
  #   init_strategy: "lhs"

  # - setting_name: "Budget0.2_Init0.1_B5_RAND"
  #   total_budget_ratio: 0.2
  #   init_ratio: 0.1
  #   batch_size: 5
  #   init_strategy: "random"


