# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_config.proto\x12\renmf.datasets\"\xad\x01\n\x0cMethodConfig\x12\x13\n\x0bmethod_name\x18\x01 \x01(\t\x12\x12\n\nlatent_dim\x18\x02 \x01(\x05\x12\x18\n\x10\x63onstrained_time\x18\x03 \x01(\x05\x12\x19\n\x11\x63onstrained_error\x18\x04 \x01(\x02\x12\x13\n\x0bresult_path\x18\x05 \x01(\t\x12\x12\n\nresult_dir\x18\x06 \x01(\t\x12\x16\n\x0eresult_storage\x18\x07 \x01(\t\"\x8c\x01\n\x0bRealDataset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61ta_dir\x18\x02 \x01(\t\x12\x11\n\tdata_path\x18\x03 \x01(\t\x12\x16\n\nlatent_dim\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x32\n\rmethod_config\x18\x05 \x03(\x0b\x32\x1b.enmf.datasets.MethodConfig\"\x9b\x01\n\x0c\x45xactDataset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61ta_dir\x18\x02 \x01(\t\x12\x11\n\tdata_path\x18\x03 \x01(\t\x12\x10\n\x08sparsity\x18\x05 \x01(\t\x12\x12\n\nlatent_dim\x18\x07 \x01(\x05\x12\x32\n\rmethod_config\x18\x06 \x03(\x0b\x32\x1b.enmf.datasets.MethodConfig\"p\n\x08\x44\x61tasets\x12\x30\n\x0creal_dataset\x18\x01 \x03(\x0b\x32\x1a.enmf.datasets.RealDataset\x12\x32\n\rexact_dataset\x18\x02 \x03(\x0b\x32\x1b.enmf.datasets.ExactDatasetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REALDATASET'].fields_by_name['latent_dim']._loaded_options = None
  _globals['_REALDATASET'].fields_by_name['latent_dim']._serialized_options = b'\020\001'
  _globals['_METHODCONFIG']._serialized_start=37
  _globals['_METHODCONFIG']._serialized_end=210
  _globals['_REALDATASET']._serialized_start=213
  _globals['_REALDATASET']._serialized_end=353
  _globals['_EXACTDATASET']._serialized_start=356
  _globals['_EXACTDATASET']._serialized_end=511
  _globals['_DATASETS']._serialized_start=513
  _globals['_DATASETS']._serialized_end=625
# @@protoc_insertion_point(module_scope)
