data:
  name: 'Poisson_fourier'
  datapath: 'data/test/poisson/poisson.mat'
  offset: 1

test:
  pre-trained: 'trained_models/pretrained-poisson_hyperbolic_44-fourier.pkl'
  iterations: 2000

generate:
  strategy: 'hyperbolic_44'
  seed: 0
  device: 'cuda'
  batch_size: 1
  sigma_min: 0.002 
  sigma_max: 70 
  rho: 7 
  zeta_obs_a: 0.05
  zeta_obs_u: 0
  zeta_pde: 0.0005
  lr_low: 0.2
  lr_high: 0.01
  freq_transition: 10
  beta1: 0.985
  beta2: 0.98
  obs_a: 500
  obs_u: 500
  




