phi1.5:
  hf_key: "/models/tofu_ft_phi-1.5"
  question_start_tag: "<|user|>\n"
  question_end_tag: "<|end|>\n<|assistant|>\n"
  answer_tag: ""
  flash_attention2: "true"
  gradient_checkpointing: "true"