hp:
  model: ResNet10
  dataset: TinyImageNet
  T: 14
  act_fn: leaky_relu
  batch_size: 128
  epochs: 50
  precision_type: PC
  alpha: 0.001
  se_flag: true
  optim:
    w:
      lr: 0.00041153549699448857
      wd: 0.005220992588957544
    x:
      lr: 0.0687379689716789
      momentum: 0.1
