hp:
  model: VGG7
  dataset: CIFAR100
  T: 12
  act_fn: leaky_relu
  batch_size: 128
  epochs: 50
  precision_type: PC
  alpha: 1.0
  se_flag: true
  optim:
    w:
      lr: 3.463739857883915e-05
      wd: 0.0001091209699918462
    x:
      lr: 0.9284617774027867
      momentum: 0.45
