verbose: False
batch_size: 8

num_seeds: 5
training_mode: amp
ID_N_f_test: 0
OOD_N_f_test: 10

outer: focal
num_hypothesis: 1
init_scale: 0.1
init_points: 10
n_iter: 100
opt_range_lower: -1.0
opt_range_upper: 1.0
seed: 1
