verbose: False
batch_size: 8

num_seeds: 5
training_mode: fixed
ID_N_f_test: 0
OOD_N_f_test: 10

outer: diffusion
temperature: 0.001
steps: 50
noise_min: 0.01
noise_max: 0.5
clip_norm: 500.0
num_mc: 10
num_hypothesis: 64
dtype: float64
