# @package _global_
defaults:
  - _self_
  - datamodule: afdbfs_ted

seed: 42
wandb: false
truncation_seq_length: 512
batch_size: 64

datamodule:
  batch_size: 64
  num_workers: 32

datamodule_test:
  _target_: tedbench.data.LightningStructureDataset
  root: ./datasets/cath
  dataset_name: cath4.4
  batch_size: 128
  num_workers: 32

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  max_steps: 18300
  strategy: auto
  devices: auto
  default_root_dir: ${logs.path}
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1

model:
  name: esm2_t33_650M_UR50D
  num_classes: 965
  avg_pool: false

train:
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.0016
    weight_decay: 0.1
    betas: [0.9, 0.95]
  lr_scheduler:
    _target_: tedbench.lr_schedulers.get_cosine_schedule_with_warmup
    warmup_steps: 1830
    max_steps: ${trainer.max_steps}
  loss:
    _target_: torch.nn.CrossEntropyLoss
  llrd: 1.0
  ckpt_path: null

logs:
  prefix: logs/esm2/finetune/${datamodule.dataset_name}/${seed}
  path: ${logs.prefix}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}

# output directory, generated dynamically on each run
hydra:
  run:
    dir: ${logs.path}
  sweep:
    dir: ${logs.prefix}/multiruns/esm2/finetune/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
