# @package _global_
defaults:
  - _self_
  - datamodule: afdbfs_ted

seed: 42

datamodule:
  batch_size: 128
  num_workers: 32

datamodule_test:
  _target_: tedbench.data.LightningStructureDataset
  root: ./datasets/cath
  dataset_name: cath4.4
  batch_size: 128
  num_workers: 32

foldseek_path: /fs/gpfs41/lv11/fileset01/pool/pool-chen/softwares/micromamba/envs/foldseek/bin/foldseek
toks_per_batch: 32768
model:
  name: SaProt_650M_AF2
  path: cache/torch/hub/checkpoints/${model.name}
  num_classes: 965

logs:
  prefix: logs/saprot/linprobe/${datamodule.dataset_name}/${seed}
  path: ${logs.prefix}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}

# output directory, generated dynamically on each run
hydra:
  run:
    dir: ${logs.path}
  sweep:
    dir: ${logs.prefix}/multiruns/saprot/linprobe/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
