title: AutoSOTA
exclude:
  - docs
  - CVPR-2026
  - ICML-2026
  - improved-papers
  - paper-*
  - scripts
  - tests
  - AutoSOTA.png
  - autosota-0.1.0.tgz
  - autosota-0.2.0.tgz
  - cli_guide.md
  - LICENSE
  - README.md
