# Model settings
time_emb_type: "default" # default, zero , logsnr_fourier
rate_matrix: null # not used, just for merge cfg; see sample.rate_matrix
transition: 'marginal'                          # uniform, marginal, argmax, absorbfirst, absorbing
model: 'graph_tf'
n_layers: 5
model_weights_dir: ${hydra:runtime.cwd}/model_weights/${dataset.name}-${general.name} #-${model.time_emb_type}-${model.extra_features}-${model.rrwp_steps}-${model.ema_decay}
extra_features: 'rrwp'        # 'all', 'cycles', 'eigenvalues', 'rrwp', 'rrwp_comp' or null
rrwp_steps: 12

# EMA for model parameters (moved from train)
# 0 disables EMA; typical value: 0.999
ema_decay: 0

# Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}

# The dimensions should satisfy dx % n_head == 0
hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

# training weight for edges, y, and nodes
lambda_train: [5, 0]              # X=1, E = lambda[0], y = lambda[1]
