include(CMakePackageConfigHelpers)
include(GNUInstallDirs)

set(PAG_INSTALL_CMAKEDIR
    "${CMAKE_INSTALL_LIBDIR}/cmake/PAG"
    CACHE STRING "Install directory for PAG CMake package files")

install(
  TARGETS pag_core
  EXPORT PAGTargets
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})

if(PAG_BUILD_CLI)
  install(TARGETS PAG RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
endif()

install(FILES pag_index.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/pag)

install(
  EXPORT PAGTargets
  NAMESPACE PAG::
  DESTINATION ${PAG_INSTALL_CMAKEDIR})

configure_package_config_file(
  ${CMAKE_CURRENT_SOURCE_DIR}/cmake/PAGConfig.cmake.in
  ${CMAKE_CURRENT_BINARY_DIR}/PAGConfig.cmake
  INSTALL_DESTINATION ${PAG_INSTALL_CMAKEDIR})

write_basic_package_version_file(
  ${CMAKE_CURRENT_BINARY_DIR}/PAGConfigVersion.cmake
  VERSION ${PROJECT_VERSION}
  COMPATIBILITY SameMajorVersion)

install(
  FILES
    ${CMAKE_CURRENT_BINARY_DIR}/PAGConfig.cmake
    ${CMAKE_CURRENT_BINARY_DIR}/PAGConfigVersion.cmake
  DESTINATION ${PAG_INSTALL_CMAKEDIR})

install(FILES README.md LICENSE DESTINATION ${CMAKE_INSTALL_DOCDIR})
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/docs")
  install(
    DIRECTORY docs/
    DESTINATION ${CMAKE_INSTALL_DOCDIR}/docs
    FILES_MATCHING PATTERN "*.md")
endif()
