# @package _global_
defaults:
  - _self_
  - datamodule: afdbfs_ted
  - mode: default

seed: 42
debug: false
wandb: false
pretrained_model_path: null

datamodule:
  batch_size: 128
  pin_memory: true
  num_workers: 32

# External CATH 4.4 experimental test set
datamodule_test:
  _target_: tedbench.data.LightningStructureDataset
  root: ./datasets/cath
  dataset_name: cath4.4
  batch_size: 128
  num_workers: 32
  pin_memory: true

model:
  _target_: tedbench.model.miae_encoder_model
  name: miae_b
  num_classes: 965
  avg_pool: true

train:
  optimizer:
    _target_: tedbench.utils.lars.LARS
    lr: 0.1
    weight_decay: 0.0
    momentum: 0.9
  lr_scheduler:
    _target_: tedbench.lr_schedulers.get_cosine_schedule_with_warmup
    warmup_steps: 150
    max_steps: ${trainer.max_steps}
  loss:
    _target_: torch.nn.CrossEntropyLoss
  llrd: 1.0
  ckpt_path: null

logs:
  prefix: logs/linprobe/${datamodule.dataset_name}/${seed}
  path: ${logs.prefix}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}

# output directory, generated dynamically on each run
hydra:
  run:
    dir: ${logs.path}
  sweep:
    dir: ${logs.prefix}/multiruns/linprobe/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
