# @package _global_
defaults:
  - _self_
  - datamodule: afdbfs_ted
  - mode: default

seed: 42
debug: false
wandb: false
pretrained_model_path: null

datamodule:
  batch_size: 32
  pin_memory: true
  num_workers: 16

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  strategy: auto
  devices: auto
  default_root_dir: ${logs.path}
  num_sanity_val_steps: 0

model:
  _target_: tedbench.model.miae_encoder_model
  name: miae_b
  num_classes: 965
  avg_pool: false

logs:
  prefix: logs/test/${datamodule.dataset_name}/${seed}
  path: ${logs.prefix}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}

# output directory, generated dynamically on each run
hydra:
  run:
    dir: ${logs.path}
  sweep:
    dir: ${logs.prefix}/multiruns/test/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
