defaults:
 - model: promptstereo
 - _self_

gpus: ${oc.env:CUDA_VISIBLE_DEVICES, '0,1'}
checkpoint: checkpoint/sceneflow_192.safetensors
max_disp: ${model.instance.cfg.gwc_max_disp}

accelerator:
  _target_: accelerate.Accelerator
  mixed_precision: bf16
  dataloader_config:
    _target_: accelerate.DataLoaderConfiguration
    split_batches: True

dataset:
  KITTI2015:
    outlier: 3
    instance:
      _target_: dataset.stereo_dataset.KITTI
      root: /data/datasets/kitti
      year: '2015'
      split: training
      mask: noc

dataloader:
  split: True
  batch_size_per_gpu: 1
  total_batch_size: null
  param:
    batch_size: null
    num_workers: null
    pin_memory: True
    shuffle: False
    drop_last: False
