#!/usr/bin/env bash
set -euo pipefail

DATA_DIR=${DATA_DIR:-./data/glove}
BASE_COUNT=${BASE_COUNT:-1193514}
QUERY_COUNT=${QUERY_COUNT:-1000}
DIM=${DIM:-200}
TOPK=${TOPK:-100}
MAX_SEARCH_K=${MAX_SEARCH_K:-1000}

EF_CONSTRUCTION=${EF_CONSTRUCTION:-2000}
TARGET_DEGREE=${TARGET_DEGREE:-64}
PROJECTION_LEVELS=${PROJECTION_LEVELS:-32}
METRIC=${METRIC:-l2}

BASE_FILE=${BASE_FILE:-${DATA_DIR}/base.fbin}
QUERY_FILE=${QUERY_FILE:-${DATA_DIR}/query.fbin}
TRUTH_FILE=${TRUTH_FILE:-${DATA_DIR}/gt1000.ibin}
INDEX_DIR=${INDEX_DIR:-${DATA_DIR}/index/}
BINARY=${BINARY:-./build/PAG}

exec "${BINARY}" \
  "${BASE_FILE}" "${QUERY_FILE}" "${TRUTH_FILE}" "${INDEX_DIR}" \
  "${BASE_COUNT}" "${QUERY_COUNT}" "${DIM}" "${TOPK}" \
  "${EF_CONSTRUCTION}" "${TARGET_DEGREE}" "${PROJECTION_LEVELS}" \
  "${METRIC}" "${MAX_SEARCH_K}"
