#!/usr/bin/env bash
set -euo pipefail

DATA_DIR=${DATA_DIR:-./data/music}
BASE_COUNT=${BASE_COUNT:-1000000}
QUERY_COUNT=${QUERY_COUNT:-10000}
DIM=${DIM:-100}
TOPK=${TOPK:-100}
MAX_SEARCH_K=${MAX_SEARCH_K:-1000}

EF_CONSTRUCTION=${EF_CONSTRUCTION:-1000}
TARGET_DEGREE=${TARGET_DEGREE:-32}
PROJECTION_LEVELS=${PROJECTION_LEVELS:-16}
METRIC=mips

export PAG_EF_POINTS=${PAG_EF_POINTS:-5}

BASE_FILE=${BASE_FILE:-${DATA_DIR}/base.fbin}
QUERY_FILE=${QUERY_FILE:-${DATA_DIR}/query.fbin}
TRUTH_FILE=${TRUTH_FILE:-${DATA_DIR}/gt1000.ibin}

if [[ -z "${INDEX_DIR:-}" ]]; then
  INDEX_DIR="${DATA_DIR}/index_mips/"
fi

BINARY=${BINARY:-./build/PAG}

exec "${BINARY}" \
  "${BASE_FILE}" "${QUERY_FILE}" "${TRUTH_FILE}" "${INDEX_DIR}" \
  "${BASE_COUNT}" "${QUERY_COUNT}" "${DIM}" "${TOPK}" \
  "${EF_CONSTRUCTION}" "${TARGET_DEGREE}" "${PROJECTION_LEVELS}" "${METRIC}" \
  "${MAX_SEARCH_K}"
