_target_: "models.diffusion.embedding.CnnEmbedding2d"

# CnnEmbedding2d.__init__(output_dim, input_dim=1, hidden_dim=64, num_blocks=4, use_coords=False)
output_dim: 64
input_dim: 1
hidden_dim: 64
num_blocks: 4
use_coords: true
padding_mode: "circular"

