_target_: "models.diffusion.embedding.FnoEmbedding1d"

# FnoEmbedding1d.__init__(output_dim, input_dim=1, hidden_dim=64, n_modes=(32,), n_layers=4)
output_dim: 64
input_dim: 1
hidden_dim: 64
n_modes: [32]
n_layers: 4

