_target_: "models.diffusion.embedding.MlpEmbedding2d"

# MlpEmbedding2d.__init__(output_dim, input_dim=1, height=64, width=64, hidden_dims=(512,256), dropout=0.0)
output_dim: 64
input_dim: 1
height: 64
width: 64
hidden_dims: [512, 256]
dropout: 0.0
