hp:
  model: ResNet10
  dataset: CIFAR10
  T: 14
  act_fn: gelu
  batch_size: 128
  epochs: 50
  precision_type: S
  Forward_type: FU
  alpha: 0.001
  se_flag: true
  optim:
    w:
      lr: 0.0007512356633853034
      wd: 3.173334999061517e-05
    x:
      lr: 0.5603756844383156
      momentum: 0.1
