hp:
  model: ResNet18
  dataset: CIFAR10
  T: 21
  act_fn: gelu
  batch_size: 128
  epochs: 50
  precision_type: S
  Forward_type: FU
  alpha: 0.0001
  se_flag: true
  optim:
    w:
      lr: 0.0007932723867273946
      wd: 0.0015754949649985316
    x:
      lr: 0.595944262800745
      momentum: 0.5
