hp:
  model: VGG10
  dataset: CIFAR10
  T: 10
  act_fn: gelu
  batch_size: 128
  epochs: 50
  precision_type: S
  Forward_type: FU
  alpha: 0.001
  se_flag: true
  optim:
    w:
      lr: 0.0006191886472729287
      wd: 6.33267921180052e-05
    x:
      lr: 0.45661689536384675
      momentum: 0.5
