hp:
  model: VGG5
  dataset: CIFAR100
  T: 5
  act_fn: gelu
  batch_size: 128
  epochs: 50
  precision_type: S
  Forward_type: FU
  alpha: 0.001
  se_flag: true
  optim:
    w:
      lr: 0.00039929851231324524
      wd: 0.0005321149981080038
    x:
      lr: 0.1604323528667648
      momentum: 0.9
