hp:
  model: VGG7
  dataset: CIFAR10
  T: 7
  act_fn: gelu
  batch_size: 128
  epochs: 50
  precision_type: S
  Forward_type: FU
  alpha: 0.001
  se_flag: true
  optim:
    w:
      lr: 0.0005635907153374876
      wd: 0.002985076410554679
    x:
      lr: 0.17036424672366374
      momentum: 0.5
