hp:
  model: VGG7
  dataset: CIFAR100
  T: 9
  act_fn: gelu
  batch_size: 128
  epochs: 50
  precision_type: S
  Forward_type: FU
  alpha: 0.001
  se_flag: true
  optim:
    w:
      lr: 0.0003959608751289805
      wd: 2.1009320556098787e-05
    x:
      lr: 0.40637036560089673
      momentum: 0.5
