hp:
  model: VGG7
  dataset: TinyImageNet
  T: 9
  act_fn: leaky_relu
  batch_size: 128
  epochs: 50
  precision_type: S
  Forward_type: FU
  alpha: 0.005
  se_flag: true
  optim:
    w:
      lr: 0.0001555770224072221
      wd: 5.609214247950443e-05
    x:
      lr: 0.2652059617891269
      momentum: 0.5
