ACM_DBLP:
  epoch: 50
  hidden_dim: 1024
  input_dim: 17
  lr: 0.0001
  num_hidden_layers: 1
  output_feature_size: 1024
  residual: true
CIFAR-10:
  epoch: 100
  hidden_dim: 512
  input_dim: 768
  k: 9
  k_neig: 5
  language: All-Roberta-large-v1
  lr: 0.01
  num_hidden_layers: 5
  output_feature_size: 512
  vision: CLIP_ViT-L_14@336
CIFAR-100:
  epoch: 100
  hidden_dim: 512
  input_dim: 768
  k: 90
  k_neig: 20
  language: All-Roberta-large-v1
  lr: 0.01
  num_hidden_layers: 5
  output_feature_size: 512
  vision: CLIP_ViT-L_14@336
CINIC-10:
  epoch: 100
  hidden_dim: 512
  input_dim: 768
  k: 9
  k_neig: 5
  language: ViT-L_14@336px
  lr: 0.01
  num_hidden_layers: 5
  output_feature_size: 512
  vision: CLIP_ViT-L_14@336
Douban Online_Offline:
  epoch: 100
  hidden_dim: 256
  input_dim: 538
  lr: 0.001
  num_hidden_layers: 6
  output_feature_size: 256
  residual: false
Imagenet-100:
  epoch: 100
  hidden_dim: 512
  input_dim: 768
  k: 90
  k_neig: 20
  language: ViT-L_14
  lr: 0.01
  num_hidden_layers: 5
  output_feature_size: 512
  vision: CLIP_ViT-L_14
