import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from typing import Tuple, Set, List


def generate_random_dag(n: int, m: int, p: float, seed: int = None) -> Tuple[np.ndarray, np.ndarray, Set[int]]:
    """
    Generate a random DAG on n+m variables with a random subset of m hidden variables.
    
    The DAG is generated by:
    1. Sampling a random permutation of n+m variables (defines topological order)
    2. For each pair (i, j) where i comes before j in the permutation,
       adding a directed edge i -> j with probability p
    3. Marking a random subset of m variables as "hidden"
    
    Parameters:
        n: Number of observed variables
        m: Number of hidden variables
        p: Probability of including each edge consistent with the topological order
        seed: Random seed for reproducibility
    
    Returns:
        adjacency_matrix: (n+m) x (n+m) adjacency matrix where A[i,j] = 1 means edge i -> j
        permutation: The random permutation used (topological order)
        hidden_variables: Set of indices of hidden variables
    """
    if seed is not None:
        np.random.seed(seed)
    
    total_vars = n + m
    
    # Step 1: Sample a random permutation (defines topological order)
    permutation = np.random.permutation(total_vars)
    
    # Step 2: Create adjacency matrix by sampling edges consistent with permutation
    # For each pair (i, j) where permutation places i before j, add edge with probability p
    adjacency_matrix = np.zeros((total_vars, total_vars), dtype=int)
    
    for idx_i in range(total_vars):
        for idx_j in range(idx_i + 1, total_vars):
            # permutation[idx_i] comes before permutation[idx_j] in topological order
            source = permutation[idx_i]
            target = permutation[idx_j]
            
            # Sample edge with probability p
            if np.random.random() < p:
                adjacency_matrix[source, target] = 1
    
    # Step 3: Sample a random subset of m variables to be hidden
    hidden_indices = np.random.choice(total_vars, size=m, replace=False)
    hidden_variables = set(hidden_indices)
    
    return adjacency_matrix, permutation, hidden_variables


def get_observed_variables(total_vars: int, hidden_variables: Set[int]) -> Set[int]:
    """
    Get the set of observed (non-hidden) variables.
    
    Parameters:
        total_vars: Total number of variables
        hidden_variables: Set of hidden variable indices
    
    Returns:
        Set of observed variable indices
    """
    return set(range(total_vars)) - hidden_variables


def compute_statement_graph(A: np.ndarray, hidden_variables: Set[int]) -> Tuple[np.ndarray, np.ndarray]:
    """
    Compute the statement graph from an adjacency matrix and hidden variables.
    
    The statement graph describes causal relationships between observed variables,
    marginalizing over hidden variables. It is described by two adjacency matrices:
    
    1. Directed edges: There is a directed edge i -> j if there is a directed path
       from i to j in the original graph. Computed as (I - A)^{-1}
    
    2. Bidirected edges: The confounding path closure of the statement graph.
       First we compute the initial confounding from hidden common ancestors in the
       original DAG, then we compute the full confounding path closure with respect
       to the statement graph's directed edges.
    
    Parameters:
        A: Adjacency matrix of the DAG where A[i,j] = 1 means edge i -> j
        hidden_variables: Set of indices of hidden variables
    
    Returns:
        directed_adj: Adjacency matrix of directed edges (between observed variables)
        bidirected_adj: Adjacency matrix of bidirected edges (between observed variables)
        observed: List of observed variable indices
    """
    n = A.shape[0]
    
    # Compute (I - A)^{-1} which gives the reachability/path matrix
    I = np.eye(n)
    I_minus_A_inv = np.linalg.inv(I - A)
    
    # Directed edges: (I - A)^{-1}
    # Entry [i,j] > 0 indicates there is a directed path from i to j
    directed_full = I_minus_A_inv
    
    # Extract only the observed variables
    observed = sorted(set(range(n)) - hidden_variables)
    observed_idx = np.array(observed)
    
    # Submatrix for observed variables only (directed edges)
    directed_adj = directed_full[np.ix_(observed_idx, observed_idx)]
    
    # Convert to binary adjacency (threshold at > 0 for paths)
    # For directed: remove self-loops (diagonal)
    directed_adj = (np.abs(directed_adj) > 1e-10).astype(float)
    np.fill_diagonal(directed_adj, 0)
    
    # Bidirected edges: 
    # Step 1: Compute initial confounding from hidden common ancestors in original DAG
    bidirected_full = np.zeros((n, n))
    confounding_full = compute_confounding_paths(A, bidirected_full)
    
    # Extract submatrix for observed variables only
    initial_bidirected = confounding_full[np.ix_(observed_idx, observed_idx)]
    
    # Step 2: Compute the confounding path closure with respect to the statement graph's
    # directed edges. This ensures the bidirected edges are closed under the statement
    # graph structure.
    bidirected_adj = compute_confounding_paths(directed_adj, initial_bidirected)
    
    return directed_adj, bidirected_adj, observed


def compute_confounding_paths(directed_adj: np.ndarray, bidirected_adj: np.ndarray) -> np.ndarray:
    """
    Compute the confounding path matrix for a graph with directed and bidirected edges.
    
    A confounding path between i and j is a path of the form:
        i <- ... <- H -> ... -> j
    where H is a common ancestor (possibly through bidirected edges), and critically:
    - The path from H to i does NOT go through j
    - The path from H to j does NOT go through i
    
    Algorithm:
    1. For each bidirected edge, introduce a new latent vertex l and replace 
       the bidirected edge with directed edges l -> i and l -> j
    2. For each pair (i, j), compute the confounding entry using:
       ((I - A')^{-T} - I) @ ((I - A'')^{-1} - I)[i, j]
       where A' has all edges incident to j removed, and A'' has all edges 
       incident to i removed
    
    Parameters:
        directed_adj: n x n adjacency matrix for directed edges (A[i,j] = 1 means i -> j)
        bidirected_adj: n x n symmetric adjacency matrix for bidirected edges 
                        (B[i,j] = B[j,i] = 1 means i <-> j)
    
    Returns:
        confounding_matrix: n x n matrix where entry [i,j] > 0 indicates a confounding
                           path exists between i and j
    """
    n = directed_adj.shape[0]
    
    # Count bidirected edges (upper triangular to avoid double counting)
    bidirected_edges = []
    for i in range(n):
        for j in range(i + 1, n):
            if bidirected_adj[i, j] > 0:
                bidirected_edges.append((i, j))
    
    num_latent = len(bidirected_edges)
    total_vars = n + num_latent
    
    # Build expanded adjacency matrix C
    C = np.zeros((total_vars, total_vars))
    
    # Copy original directed edges
    C[:n, :n] = directed_adj
    
    # For each bidirected edge i <-> j, add latent vertex l with edges l -> i, l -> j
    for idx, (bi, bj) in enumerate(bidirected_edges):
        l = n + idx  # Index of new latent vertex
        C[l, bi] = 1  # l -> bi
        C[l, bj] = 1  # l -> bj
    
    # Compute confounding matrix entry-by-entry
    # For each pair (i, j): use A' (edges to j removed) and A'' (edges to i removed)
    confounding_matrix = np.zeros((n, n))
    I = np.eye(total_vars)
    
    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            
            # Create A' = C with all edges incident to j removed
            # (both incoming: k -> j, and outgoing: j -> k)
            A_prime = C.copy()
            A_prime[:, j] = 0  # Remove all incoming edges to j
            A_prime[j, :] = 0  # Remove all outgoing edges from j
            
            # Create A'' = C with all edges incident to i removed
            A_double_prime = C.copy()
            A_double_prime[:, i] = 0  # Remove all incoming edges to i
            A_double_prime[i, :] = 0  # Remove all outgoing edges from i
            
            # Compute ((I - A')^{-T} - I) @ ((I - A'')^{-1} - I)[i, j]
            I_minus_Ap_inv = np.linalg.inv(I - A_prime)
            I_minus_App_inv = np.linalg.inv(I - A_double_prime)
            
            # Left factor: (I - A')^{-T} - I, we need row i
            left_factor = I_minus_Ap_inv.T - I
            # Right factor: (I - A'')^{-1} - I, we need column j
            right_factor = I_minus_App_inv - I
            
            # Compute entry [i, j] of the product
            confounding_matrix[i, j] = left_factor[i, :] @ right_factor[:, j]
    
    # Binarize and clean up
    confounding_matrix = (np.abs(confounding_matrix) > 1e-10).astype(float)
    np.fill_diagonal(confounding_matrix, 0)
    
    return confounding_matrix


def count_cpc_edges(directed_adj: np.ndarray, bidirected_adj: np.ndarray) -> int:
    """
    Count the number of edges in the confounding path closure.
    
    Since the confounding matrix is symmetric, we count only upper triangular entries.
    
    Parameters:
        directed_adj: Adjacency matrix for directed edges
        bidirected_adj: Adjacency matrix for bidirected edges
    
    Returns:
        Number of edges in the confounding path closure
    """
    cpc = compute_confounding_paths(directed_adj, bidirected_adj)
    # Count upper triangular entries (since symmetric)
    n = cpc.shape[0]
    count = 0
    for i in range(n):
        for j in range(i + 1, n):
            if cpc[i, j] > 0:
                count += 1
    return count


def remove_bidirected_edge(bidirected_adj: np.ndarray, i: int, j: int) -> np.ndarray:
    """
    Remove a bidirected edge from the bidirected adjacency matrix.
    
    Parameters:
        bidirected_adj: Symmetric adjacency matrix for bidirected edges
        i, j: Indices of the edge to remove
    
    Returns:
        New bidirected adjacency matrix with edge removed
    """
    B_new = bidirected_adj.copy()
    B_new[i, j] = 0
    B_new[j, i] = 0
    return B_new


def greedy_confounding_path_closure(directed_adj: np.ndarray, bidirected_adj: np.ndarray, 
                                     verbose: bool = False) -> Tuple[List[Tuple[int, int]], List[Tuple[int, int]]]:
    """
    Greedy Confounding Path Closure (GreedyCPC) algorithm.
    
    Takes a mixed graph with directed and bidirected edges and computes a set of 
    bidirected edge deletions and additions that make the bidirected edge adjacency 
    matrix equal to the confounding path matrix.
    
    The algorithm greedily removes bidirected edges that maximize the reduction in 
    confounding path closure size, then adds all edges needed to complete the closure.
    
    Algorithm:
        1. Initialize H = G (input graph)
        2. Repeat:
           - For each bidirected edge e in H, compute gain = |cpc(H)| - |cpc(H \ e)| - 1
           - If best gain > 0, remove the best edge and add it to B_del
        3. Until no positive gain
        4. B_add = cpc(G \ B_del) \ B(G \ B_del)
        5. Return (B_del, B_add)
    
    Parameters:
        directed_adj: n x n adjacency matrix for directed edges (A[i,j] = 1 means i -> j)
        bidirected_adj: n x n symmetric adjacency matrix for bidirected edges
        verbose: If True, print progress information
    
    Returns:
        B_del: List of bidirected edges to delete (as tuples (i, j) with i < j)
        B_add: List of bidirected edges to add to achieve confounding path closure
    """
    n = directed_adj.shape[0]
    
    # Initialize
    B_del = []
    H_directed = directed_adj.copy().astype(float)
    H_bidirected = bidirected_adj.copy().astype(float)
    
    iteration = 0
    while True:
        iteration += 1
        
        # Current bidirected edges in H (upper triangular to avoid duplicates)
        current_bidirected = [(i, j) for i in range(n) for j in range(i + 1, n) 
                              if H_bidirected[i, j] > 0]
        
        if not current_bidirected:
            break
        
        # Compute |cpc(H)|
        cpc_H_size = count_cpc_edges(H_directed, H_bidirected)
        
        if verbose:
            print(f"\n--- Iteration {iteration} ---")
            print(f"Current bidirected edges: {current_bidirected}")
            print(f"|cpc(H)| = {cpc_H_size}")
            cpc_H = compute_confounding_paths(H_directed, H_bidirected)
            cpc_edges = [(i, j) for i in range(n) for j in range(i+1, n) if cpc_H[i, j] > 0]
            print(f"cpc(H) edges: {cpc_edges}")
            print(f"\nEvaluating each edge for removal:")
        
        # Find best bidirected edge to remove
        best_gain = 0
        e_star = None
        
        for e in current_bidirected:
            i, j = e
            # Create H \ e (remove bidirected edge)
            H_bidirected_minus_e = remove_bidirected_edge(H_bidirected, i, j)
            
            # Compute |cpc(H \ e)|
            cpc_H_minus_e_size = count_cpc_edges(H_directed, H_bidirected_minus_e)
            
            # Gain = |cpc(H)| - |cpc(H \ e)| - 1
            gain = cpc_H_size - cpc_H_minus_e_size - 1
            
            if verbose:
                cpc_minus_e = compute_confounding_paths(H_directed, H_bidirected_minus_e)
                cpc_minus_e_edges = [(ii, jj) for ii in range(n) for jj in range(ii+1, n) 
                                     if cpc_minus_e[ii, jj] > 0]
                print(f"  Edge {i}<->{j}: |cpc(H\\e)| = {cpc_H_minus_e_size}, "
                      f"gain = {cpc_H_size} - {cpc_H_minus_e_size} - 1 = {gain}")
                print(f"           cpc(H\\e) edges: {cpc_minus_e_edges}")
            
            if gain > best_gain:
                best_gain = gain
                e_star = e
        
        if verbose:
            print(f"\nBest gain = {best_gain}")
        
        if best_gain > 0:
            B_del.append(e_star)
            H_bidirected = remove_bidirected_edge(H_bidirected, e_star[0], e_star[1])
            if verbose:
                print(f"  -> Removed bidirected edge {e_star[0]} <-> {e_star[1]}")
        else:
            break
    
    # G' = G \ B_del (original graph with deleted bidirected edges removed)
    G_prime_bidirected = bidirected_adj.copy().astype(float)
    for i, j in B_del:
        G_prime_bidirected[i, j] = 0
        G_prime_bidirected[j, i] = 0
    
    # B_add = cpc(G') \ B(G')
    cpc_G_prime = compute_confounding_paths(directed_adj, G_prime_bidirected)
    
    B_add = []
    for i in range(n):
        for j in range(i + 1, n):
            # Edge is in cpc(G') but not in B(G')
            if cpc_G_prime[i, j] > 0 and G_prime_bidirected[i, j] == 0:
                B_add.append((i, j))
    
    if verbose:
        print(f"\nResult: {len(B_del)} deletions, {len(B_add)} additions")
        print(f"  B_del = {B_del}")
        print(f"  B_add = {B_add}")
    
    return B_del, B_add


def apply_confounding_path_closure(bidirected_adj: np.ndarray, 
                                    B_del: List[Tuple[int, int]], 
                                    B_add: List[Tuple[int, int]]) -> np.ndarray:
    """
    Apply confounding path closure operations to create the closed bidirected graph.
    
    Parameters:
        bidirected_adj: Original bidirected adjacency matrix
        B_del: Bidirected edges to delete
        B_add: Bidirected edges to add
    
    Returns:
        Adjacency matrix of the confounding path closed bidirected graph
    """
    result = bidirected_adj.copy()
    
    # Remove deleted edges
    for i, j in B_del:
        result[i, j] = 0
        result[j, i] = 0
    
    # Add new edges
    for i, j in B_add:
        result[i, j] = 1
        result[j, i] = 1
    
    return result


def is_confounding_path_closed(directed_adj: np.ndarray, bidirected_adj: np.ndarray) -> bool:
    """
    Check if a mixed graph's bidirected edges equal its confounding path matrix.
    
    Parameters:
        directed_adj: Adjacency matrix for directed edges
        bidirected_adj: Adjacency matrix for bidirected edges
    
    Returns:
        True if B(G) = cpc(G)
    """
    cpc = compute_confounding_paths(directed_adj, bidirected_adj)
    n = bidirected_adj.shape[0]
    
    for i in range(n):
        for j in range(n):
            if i != j:
                has_bidirected = bidirected_adj[i, j] > 0
                has_confounding = cpc[i, j] > 0
                if has_bidirected != has_confounding:
                    return False
    
    return True


def incompatibility_score(directed_adj: np.ndarray, bidirected_adj: np.ndarray, 
                         verbose: bool = False) -> Tuple[int, dict]:
    """
    Compute the incompatibility score of a mixed graph with directed and bidirected edges.
    
    The incompatibility score measures how many edge modifications are needed to transform
    the graph into a valid causal model (acyclic, transitively closed, confounding path closed).
    
    Algorithm:
    1. Run GreedyFAS on the directed part to make it acyclic (count deletions)
    2. Run GreedyTE on the acyclic graph to make it transitively closed (count deletions + additions)
    3. Add back the original bidirected edges and run GreedyCPC (count deletions + additions)
    
    Parameters:
        directed_adj: n x n adjacency matrix for directed edges (A[i,j] = 1 means i -> j)
        bidirected_adj: n x n symmetric adjacency matrix for bidirected edges
        verbose: If True, print detailed progress information
    
    Returns:
        score: Total number of edge modifications (lower is better, 0 = already compatible)
        details: Dictionary with breakdown of modifications at each step
    """
    n = directed_adj.shape[0]
    
    if verbose:
        print("=" * 60)
        print("Computing Incompatibility Score")
        print("=" * 60)
    
    # ========== Step 1: GreedyFAS to make directed part acyclic ==========
    if verbose:
        print("\n--- Step 1: GreedyFAS (make acyclic) ---")
    
    fas_edges = greedy_fas(directed_adj)
    directed_acyclic = remove_edges(directed_adj, fas_edges)
    
    fas_deletions = len(fas_edges)
    
    if verbose:
        print(f"FAS deletions: {fas_deletions}")
        if fas_edges:
            print(f"  Removed edges: {fas_edges}")
    
    # ========== Step 2: GreedyTE to make transitively closed ==========
    if verbose:
        print("\n--- Step 2: GreedyTE (make transitively closed) ---")
    
    te_E_del, te_E_add = greedy_transitivity_editing(directed_acyclic, verbose=False)
    directed_tc = apply_transitivity_editing(directed_acyclic, te_E_del, te_E_add)
    
    te_deletions = len(te_E_del)
    te_additions = len(te_E_add)
    
    if verbose:
        print(f"TE deletions: {te_deletions}, TE additions: {te_additions}")
        if te_E_del:
            print(f"  Removed edges: {te_E_del}")
        if te_E_add:
            print(f"  Added edges: {te_E_add}")
    
    # ========== Step 3: GreedyCPC with original bidirected edges ==========
    if verbose:
        print("\n--- Step 3: GreedyCPC (make confounding path closed) ---")
    
    cpc_B_del, cpc_B_add = greedy_confounding_path_closure(directed_tc, bidirected_adj, verbose=False)
    
    cpc_deletions = len(cpc_B_del)
    cpc_additions = len(cpc_B_add)
    
    if verbose:
        print(f"CPC deletions: {cpc_deletions}, CPC additions: {cpc_additions}")
        if cpc_B_del:
            print(f"  Removed bidirected edges: {cpc_B_del}")
        if cpc_B_add:
            print(f"  Added bidirected edges: {cpc_B_add}")
    
    # ========== Compute total score ==========
    total_score = fas_deletions + te_deletions + te_additions + cpc_deletions + cpc_additions
    
    details = {
        'fas_deletions': fas_deletions,
        'fas_edges': fas_edges,
        'te_deletions': te_deletions,
        'te_additions': te_additions,
        'te_E_del': te_E_del,
        'te_E_add': te_E_add,
        'cpc_deletions': cpc_deletions,
        'cpc_additions': cpc_additions,
        'cpc_B_del': cpc_B_del,
        'cpc_B_add': cpc_B_add,
        'final_directed': directed_tc,
        'final_bidirected': apply_confounding_path_closure(bidirected_adj, cpc_B_del, cpc_B_add)
    }
    
    if verbose:
        print("\n" + "=" * 60)
        print(f"TOTAL INCOMPATIBILITY SCORE: {total_score}")
        print(f"  FAS: {fas_deletions} deletions")
        print(f"  TE:  {te_deletions} deletions + {te_additions} additions = {te_deletions + te_additions}")
        print(f"  CPC: {cpc_deletions} deletions + {cpc_additions} additions = {cpc_deletions + cpc_additions}")
        print("=" * 60)
    
    return total_score, details


def visualize_confounding_path_closure(directed_adj: np.ndarray, bidirected_adj: np.ndarray,
                                        B_del: List[Tuple[int, int]], B_add: List[Tuple[int, int]],
                                        title: str = None, save_path: str = None):
    """
    Visualize the result of Greedy Confounding Path Closure.
    
    Creates a figure with three subplots:
    - Left: Original mixed graph with bidirected edges to delete highlighted in red
    - Middle: Intermediate graph after deletions
    - Right: Final confounding path closed graph with added edges in green
    
    Directed edges are shown as solid arrows, bidirected edges as dashed curved lines.
    
    Parameters:
        directed_adj: Adjacency matrix for directed edges
        bidirected_adj: Original bidirected adjacency matrix
        B_del: Bidirected edges to delete
        B_add: Bidirected edges to add
        title: Optional title for the figure
        save_path: Optional path to save the figure
    """
    n = directed_adj.shape[0]
    B_del_set = set(B_del)
    B_add_set = set(B_add)
    
    # Create figure
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    
    # Get directed edges
    directed_edges = [(i, j) for i in range(n) for j in range(n) if directed_adj[i, j] > 0]
    
    # Get original bidirected edges (upper triangular)
    original_bidirected = [(i, j) for i in range(n) for j in range(i + 1, n) 
                           if bidirected_adj[i, j] > 0]
    kept_bidirected = [e for e in original_bidirected if e not in B_del_set]
    
    # Create graph for layout (use directed edges for positioning)
    G = nx.DiGraph()
    G.add_nodes_from(range(n))
    G.add_edges_from(directed_edges)
    pos = nx.spring_layout(G, seed=42, k=2)
    
    # ========== LEFT: Original graph ==========
    ax1 = axes[0]
    
    # Draw nodes
    nx.draw_networkx_nodes(G, pos, ax=ax1, node_color='#3498db', 
                           node_size=700, edgecolors='black', linewidths=2)
    nx.draw_networkx_labels(G, pos, ax=ax1, font_size=12, font_weight='bold')
    
    # Draw directed edges (black solid)
    nx.draw_networkx_edges(G, pos, ax=ax1, edgelist=directed_edges,
                           edge_color='black', arrows=True, arrowsize=20,
                           connectionstyle='arc3,rad=0.1')
    
    # Draw kept bidirected edges (blue dashed)
    for i, j in kept_bidirected:
        ax1.annotate("", xy=pos[j], xytext=pos[i],
                    arrowprops=dict(arrowstyle="-", color='#3498db', lw=2,
                                   linestyle='dashed', connectionstyle="arc3,rad=0.3"))
    
    # Draw deleted bidirected edges (red dashed, thicker)
    for i, j in B_del_set:
        ax1.annotate("", xy=pos[j], xytext=pos[i],
                    arrowprops=dict(arrowstyle="-", color='#e74c3c', lw=3,
                                   linestyle='dashed', connectionstyle="arc3,rad=0.3"))
    
    ax1.set_title(f'Original Graph\n({len(original_bidirected)} bidirected, red = to delete)', 
                  fontsize=12, fontweight='bold')
    ax1.axis('off')
    
    # ========== MIDDLE: After deletions ==========
    ax2 = axes[1]
    
    # Draw nodes
    nx.draw_networkx_nodes(G, pos, ax=ax2, node_color='#f39c12', 
                           node_size=700, edgecolors='black', linewidths=2)
    nx.draw_networkx_labels(G, pos, ax=ax2, font_size=12, font_weight='bold')
    
    # Draw directed edges
    nx.draw_networkx_edges(G, pos, ax=ax2, edgelist=directed_edges,
                           edge_color='black', arrows=True, arrowsize=20,
                           connectionstyle='arc3,rad=0.1')
    
    # Draw kept bidirected edges
    for i, j in kept_bidirected:
        ax2.annotate("", xy=pos[j], xytext=pos[i],
                    arrowprops=dict(arrowstyle="-", color='#3498db', lw=2,
                                   linestyle='dashed', connectionstyle="arc3,rad=0.3"))
    
    ax2.set_title(f'After Deletions\n({len(kept_bidirected)} bidirected)', 
                  fontsize=12, fontweight='bold')
    ax2.axis('off')
    
    # ========== RIGHT: Final closed graph ==========
    ax3 = axes[2]
    
    final_bidirected = kept_bidirected + list(B_add_set)
    
    # Draw nodes
    nx.draw_networkx_nodes(G, pos, ax=ax3, node_color='#2ecc71', 
                           node_size=700, edgecolors='black', linewidths=2)
    nx.draw_networkx_labels(G, pos, ax=ax3, font_size=12, font_weight='bold')
    
    # Draw directed edges
    nx.draw_networkx_edges(G, pos, ax=ax3, edgelist=directed_edges,
                           edge_color='black', arrows=True, arrowsize=20,
                           connectionstyle='arc3,rad=0.1')
    
    # Draw kept bidirected edges (blue)
    for i, j in kept_bidirected:
        ax3.annotate("", xy=pos[j], xytext=pos[i],
                    arrowprops=dict(arrowstyle="-", color='#3498db', lw=2,
                                   linestyle='dashed', connectionstyle="arc3,rad=0.3"))
    
    # Draw added bidirected edges (green)
    for i, j in B_add_set:
        ax3.annotate("", xy=pos[j], xytext=pos[i],
                    arrowprops=dict(arrowstyle="-", color='#27ae60', lw=2.5,
                                   linestyle='dashed', connectionstyle="arc3,rad=0.3"))
    
    ax3.set_title(f'Confounding Path Closed\n({len(final_bidirected)} bidirected, green = added)', 
                  fontsize=12, fontweight='bold')
    ax3.axis('off')
    
    # Legend
    from matplotlib.lines import Line2D
    legend_elements = [
        Line2D([0], [0], color='black', lw=2, label='Directed edges'),
        Line2D([0], [0], color='#3498db', lw=2, linestyle='--', label='Kept bidirected'),
        Line2D([0], [0], color='#e74c3c', lw=3, linestyle='--', label=f'Deleted ({len(B_del)})'),
        Line2D([0], [0], color='#27ae60', lw=2.5, linestyle='--', label=f'Added ({len(B_add)})')
    ]
    fig.legend(handles=legend_elements, loc='lower center', ncol=4, fontsize=11,
               bbox_to_anchor=(0.5, -0.02))
    
    if title:
        fig.suptitle(title, fontsize=14, fontweight='bold', y=1.02)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Figure saved to: {save_path}")
    
    plt.show()
    
    return fig


def greedy_fas(A: np.ndarray) -> List[Tuple[int, int]]:
    """
    Greedy Feedback Arc Set (FAS) algorithm.
    
    Given a directed graph, finds a set of edges whose removal makes the graph acyclic.
    Uses the greedy heuristic based on the difference between out-degree and in-degree.
    
    Algorithm:
    1. Iteratively process vertices, adding them to either the "left" or "right" sequence
    2. At each step, choose a vertex with maximum (out-degree - in-degree) for right,
       or minimum for left (i.e., sinks go left, sources go right)
    3. The final ordering is: left_sequence (reversed) + right_sequence
    4. Back edges (edges going from later to earlier in this order) form the FAS
    
    Parameters:
        A: Adjacency matrix where A[i,j] = 1 means edge i -> j
    
    Returns:
        fas: List of edges (i, j) that form the feedback arc set
    """
    n = A.shape[0]
    
    # Work with a copy to modify during algorithm
    adj = A.copy().astype(float)
    
    # Track remaining vertices
    remaining = set(range(n))
    
    # Sequences for building the final order
    s_left = []   # Will be reversed at the end
    s_right = []
    
    while remaining:
        # Find and remove sinks (vertices with out-degree 0)
        while True:
            sinks = [v for v in remaining if np.sum(adj[v, :]) == 0]
            if not sinks:
                break
            for v in sinks:
                s_left.append(v)
                remaining.remove(v)
                adj[:, v] = 0  # Remove incoming edges
        
        if not remaining:
            break
            
        # Find and remove sources (vertices with in-degree 0)
        while True:
            sources = [v for v in remaining if np.sum(adj[:, v]) == 0]
            if not sources:
                break
            for v in sources:
                s_right.append(v)
                remaining.remove(v)
                adj[v, :] = 0  # Remove outgoing edges
        
        if not remaining:
            break
        
        # Choose vertex with maximum (out-degree - in-degree)
        best_v = None
        best_delta = float('-inf')
        for v in remaining:
            out_deg = np.sum(adj[v, :])
            in_deg = np.sum(adj[:, v])
            delta = out_deg - in_deg
            if delta > best_delta:
                best_delta = delta
                best_v = v
        
        # Add to right sequence and remove from graph
        s_right.append(best_v)
        remaining.remove(best_v)
        adj[best_v, :] = 0
        adj[:, best_v] = 0
    
    # Build final ordering: reversed left + right
    ordering = list(reversed(s_left)) + s_right
    
    # Create position map for the ordering
    position = {v: i for i, v in enumerate(ordering)}
    
    # Find back edges (edges going from later to earlier in ordering)
    fas = []
    for i in range(n):
        for j in range(n):
            if A[i, j] > 0:  # There is an edge i -> j
                if position[i] > position[j]:  # i comes after j in ordering
                    fas.append((i, j))
    
    return fas


def is_acyclic(A: np.ndarray) -> bool:
    """
    Check if a directed graph (given as adjacency matrix) is acyclic.
    
    Uses the property that a DAG has a topological ordering, which can be
    found by repeatedly removing vertices with no incoming edges.
    
    Parameters:
        A: Adjacency matrix where A[i,j] = 1 means edge i -> j
    
    Returns:
        True if the graph is acyclic, False otherwise
    """
    n = A.shape[0]
    adj = A.copy().astype(float)
    remaining = set(range(n))
    
    while remaining:
        # Find vertices with no incoming edges from remaining vertices
        sources = []
        for v in remaining:
            in_deg = sum(adj[u, v] for u in remaining)
            if in_deg == 0:
                sources.append(v)
        
        if not sources:
            # No source found but vertices remain -> cycle exists
            return False
        
        # Remove one source
        v = sources[0]
        remaining.remove(v)
    
    return True


def remove_edges(A: np.ndarray, edges: List[Tuple[int, int]]) -> np.ndarray:
    """
    Remove a set of edges from an adjacency matrix.
    
    Parameters:
        A: Adjacency matrix
        edges: List of edges (i, j) to remove
    
    Returns:
        New adjacency matrix with edges removed
    """
    A_new = A.copy()
    for i, j in edges:
        A_new[i, j] = 0
    return A_new


def transitive_closure(A: np.ndarray) -> np.ndarray:
    """
    Compute the transitive closure of an acyclic directed graph.
    
    For a DAG with adjacency matrix A, the transitive closure is computed as:
        tc(A) = (I - A)^{-1} - I
    
    The resulting matrix has entry [i,j] = 1 if there is a directed path from i to j.
    
    Parameters:
        A: Adjacency matrix of a DAG where A[i,j] = 1 means edge i -> j
    
    Returns:
        tc_adj: Adjacency matrix of the transitive closure (binary, no self-loops)
    """
    n = A.shape[0]
    I = np.eye(n)
    
    # (I - A)^{-1} gives the reachability matrix
    # Entry [i,j] counts number of paths from i to j (including length 0 path i to i)
    I_minus_A_inv = np.linalg.inv(I - A)
    
    # Subtract I to remove self-loops, then binarize
    tc_adj = (np.abs(I_minus_A_inv - I) > 1e-10).astype(int)
    
    return tc_adj


def count_tc_edges(A: np.ndarray) -> int:
    """
    Count the number of edges in the transitive closure of a DAG.
    
    Parameters:
        A: Adjacency matrix of a DAG
    
    Returns:
        Number of edges in the transitive closure
    """
    tc = transitive_closure(A)
    return int(np.sum(tc))


def greedy_transitivity_editing(A: np.ndarray, verbose: bool = False) -> Tuple[List[Tuple[int, int]], List[Tuple[int, int]]]:
    """
    Greedy Transitivity Editing (GreedyTE) algorithm.
    
    Takes an acyclic directed graph and computes a set of edge deletions and additions
    that transform it into a transitively closed graph.
    
    The algorithm greedily removes edges that maximize the reduction in transitive
    closure size, then adds all edges needed to complete the transitive closure.
    
    Algorithm:
        1. Initialize H = D (input graph)
        2. Repeat:
           - For each edge e in H, compute gain = |tc(H)| - |tc(H \ e)| - 1
           - If best gain > 0, remove the best edge and add it to E_del
        3. Until no positive gain
        4. E_add = tc(D \ E_del) \ (D \ E_del)
        5. Return (E_del, E_add)
    
    Parameters:
        A: Adjacency matrix of an acyclic directed graph where A[i,j] = 1 means edge i -> j
        verbose: If True, print progress information
    
    Returns:
        E_del: List of edges to delete from the original graph
        E_add: List of edges to add to achieve transitive closure
    """
    n = A.shape[0]
    
    # Verify input is acyclic
    if not is_acyclic(A):
        raise ValueError("Input graph must be acyclic")
    
    # Initialize
    E_del = []
    H = A.copy().astype(float)
    
    iteration = 0
    while True:
        iteration += 1
        
        # Current edges in H
        current_edges = [(i, j) for i in range(n) for j in range(n) if H[i, j] > 0]
        
        if not current_edges:
            break
        
        # Compute |tc(H)|
        tc_H_size = count_tc_edges(H)
        
        # Find best edge to remove
        best_gain = 0
        e_star = None
        
        for e in current_edges:
            i, j = e
            # Create H \ e
            H_minus_e = H.copy()
            H_minus_e[i, j] = 0
            
            # Compute |tc(H \ e)|
            tc_H_minus_e_size = count_tc_edges(H_minus_e)
            
            # Gain = |tc(H)| - |tc(H \ e)| - 1
            gain = tc_H_size - tc_H_minus_e_size - 1
            
            if gain > best_gain:
                best_gain = gain
                e_star = e
        
        if verbose:
            print(f"Iteration {iteration}: |H| = {len(current_edges)} edges, |tc(H)| = {tc_H_size}, best_gain = {best_gain}")
        
        if best_gain > 0:
            E_del.append(e_star)
            H[e_star[0], e_star[1]] = 0
            if verbose:
                print(f"  -> Removed edge {e_star}")
        else:
            break
    
    # D' = D \ E_del (original graph with deleted edges removed)
    D_prime = remove_edges(A, E_del)
    
    # E_add = tc(D') \ D'
    tc_D_prime = transitive_closure(D_prime)
    
    E_add = []
    for i in range(n):
        for j in range(n):
            # Edge is in tc(D') but not in D'
            if tc_D_prime[i, j] > 0 and D_prime[i, j] == 0:
                E_add.append((i, j))
    
    if verbose:
        print(f"\nResult: {len(E_del)} deletions, {len(E_add)} additions")
        print(f"  E_del = {E_del}")
        print(f"  E_add = {E_add}")
    
    return E_del, E_add


def apply_transitivity_editing(A: np.ndarray, E_del: List[Tuple[int, int]], 
                                E_add: List[Tuple[int, int]]) -> np.ndarray:
    """
    Apply transitivity editing operations to create the transitively closed graph.
    
    Parameters:
        A: Original adjacency matrix
        E_del: Edges to delete
        E_add: Edges to add
    
    Returns:
        Adjacency matrix of the transitively closed graph
    """
    result = A.copy()
    
    # Remove deleted edges
    for i, j in E_del:
        result[i, j] = 0
    
    # Add new edges
    for i, j in E_add:
        result[i, j] = 1
    
    return result


def is_transitively_closed(A: np.ndarray) -> bool:
    """
    Check if a directed graph is transitively closed.
    
    A graph is transitively closed if for any path i -> ... -> j, the edge i -> j exists.
    
    Parameters:
        A: Adjacency matrix
    
    Returns:
        True if the graph is transitively closed
    """
    tc = transitive_closure(A)
    
    # Check if A contains all edges in its transitive closure
    for i in range(A.shape[0]):
        for j in range(A.shape[0]):
            if tc[i, j] > 0 and A[i, j] == 0:
                return False
    
    return True


def visualize_transitivity_editing(A: np.ndarray, E_del: List[Tuple[int, int]], 
                                    E_add: List[Tuple[int, int]], 
                                    title: str = None, save_path: str = None):
    """
    Visualize the result of transitivity editing.
    
    Creates a figure with three subplots:
    - Left: Original graph with edges to delete highlighted in red
    - Middle: Intermediate graph after deletions
    - Right: Final transitively closed graph with added edges in green
    
    Parameters:
        A: Original adjacency matrix
        E_del: Edges to delete
        E_add: Edges to add
        title: Optional title for the figure
        save_path: Optional path to save the figure
    """
    n = A.shape[0]
    E_del_set = set(E_del)
    E_add_set = set(E_add)
    
    # Create figure
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    
    # Get all original edges
    original_edges = [(i, j) for i in range(n) for j in range(n) if A[i, j] > 0]
    kept_edges = [e for e in original_edges if e not in E_del_set]
    
    # Create graph for layout
    G = nx.DiGraph()
    G.add_nodes_from(range(n))
    G.add_edges_from(original_edges)
    pos = nx.spring_layout(G, seed=42, k=2)
    
    # ========== LEFT: Original graph ==========
    ax1 = axes[0]
    
    nx.draw_networkx_nodes(G, pos, ax=ax1, node_color='#3498db', 
                           node_size=700, edgecolors='black', linewidths=2)
    nx.draw_networkx_labels(G, pos, ax=ax1, font_size=12, font_weight='bold')
    
    # Draw kept edges (black)
    nx.draw_networkx_edges(G, pos, ax=ax1, edgelist=kept_edges,
                           edge_color='black', arrows=True, arrowsize=20,
                           connectionstyle='arc3,rad=0.1')
    
    # Draw deleted edges (red, dashed)
    nx.draw_networkx_edges(G, pos, ax=ax1, edgelist=list(E_del_set),
                           edge_color='#e74c3c', arrows=True, arrowsize=20,
                           width=3, style='dashed', connectionstyle='arc3,rad=0.1')
    
    ax1.set_title(f'Original Graph\n({len(original_edges)} edges, red = to delete)', 
                  fontsize=12, fontweight='bold')
    ax1.axis('off')
    
    # ========== MIDDLE: After deletions ==========
    ax2 = axes[1]
    
    G_mid = nx.DiGraph()
    G_mid.add_nodes_from(range(n))
    G_mid.add_edges_from(kept_edges)
    
    nx.draw_networkx_nodes(G_mid, pos, ax=ax2, node_color='#f39c12', 
                           node_size=700, edgecolors='black', linewidths=2)
    nx.draw_networkx_labels(G_mid, pos, ax=ax2, font_size=12, font_weight='bold')
    nx.draw_networkx_edges(G_mid, pos, ax=ax2, edgelist=kept_edges,
                           edge_color='black', arrows=True, arrowsize=20,
                           connectionstyle='arc3,rad=0.1')
    
    ax2.set_title(f'After Deletions\n({len(kept_edges)} edges)', 
                  fontsize=12, fontweight='bold')
    ax2.axis('off')
    
    # ========== RIGHT: Final transitively closed graph ==========
    ax3 = axes[2]
    
    final_edges = kept_edges + list(E_add_set)
    
    G_final = nx.DiGraph()
    G_final.add_nodes_from(range(n))
    G_final.add_edges_from(final_edges)
    
    nx.draw_networkx_nodes(G_final, pos, ax=ax3, node_color='#2ecc71', 
                           node_size=700, edgecolors='black', linewidths=2)
    nx.draw_networkx_labels(G_final, pos, ax=ax3, font_size=12, font_weight='bold')
    
    # Draw original kept edges (black)
    nx.draw_networkx_edges(G_final, pos, ax=ax3, edgelist=kept_edges,
                           edge_color='black', arrows=True, arrowsize=20,
                           connectionstyle='arc3,rad=0.1')
    
    # Draw added edges (green)
    nx.draw_networkx_edges(G_final, pos, ax=ax3, edgelist=list(E_add_set),
                           edge_color='#27ae60', arrows=True, arrowsize=20,
                           width=2.5, connectionstyle='arc3,rad=0.1')
    
    ax3.set_title(f'Transitively Closed\n({len(final_edges)} edges, green = added)', 
                  fontsize=12, fontweight='bold')
    ax3.axis('off')
    
    # Legend
    from matplotlib.lines import Line2D
    legend_elements = [
        Line2D([0], [0], color='black', lw=2, label='Kept edges'),
        Line2D([0], [0], color='#e74c3c', lw=3, linestyle='--', label=f'Deleted ({len(E_del)})'),
        Line2D([0], [0], color='#27ae60', lw=2.5, label=f'Added ({len(E_add)})')
    ]
    fig.legend(handles=legend_elements, loc='lower center', ncol=3, fontsize=11,
               bbox_to_anchor=(0.5, -0.02))
    
    if title:
        fig.suptitle(title, fontsize=14, fontweight='bold', y=1.02)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Figure saved to: {save_path}")
    
    plt.show()
    
    return fig


def visualize_dag_and_statement_graph(A: np.ndarray, hidden_variables: Set[int], 
                                       title: str = None, save_path: str = None):
    """
    Visualize a DAG with hidden variables and its corresponding statement graph.
    
    Creates a figure with two subplots:
    - Left: Original DAG with hidden variables shown in a different color
    - Right: Statement graph showing directed and bidirected edges between observed variables
    
    Parameters:
        A: Adjacency matrix of the DAG where A[i,j] = 1 means edge i -> j
        hidden_variables: Set of indices of hidden variables
        title: Optional title for the figure
        save_path: Optional path to save the figure
    """
    n = A.shape[0]
    observed = sorted(set(range(n)) - hidden_variables)
    
    # Compute statement graph
    directed_adj, bidirected_adj, obs_list = compute_statement_graph(A, hidden_variables)
    
    # Create figure with two subplots
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    
    # ========== LEFT PLOT: Original DAG ==========
    ax1 = axes[0]
    
    # Create networkx graph for the original DAG
    G_orig = nx.DiGraph()
    G_orig.add_nodes_from(range(n))
    
    # Add edges from adjacency matrix
    for i in range(n):
        for j in range(n):
            if A[i, j] > 0:
                G_orig.add_edge(i, j)
    
    # Node colors: hidden = red, observed = blue
    node_colors = ['#e74c3c' if i in hidden_variables else '#3498db' for i in range(n)]
    
    # Layout
    pos_orig = nx.spring_layout(G_orig, seed=42, k=2)
    
    # Draw nodes
    nx.draw_networkx_nodes(G_orig, pos_orig, ax=ax1, node_color=node_colors, 
                           node_size=700, edgecolors='black', linewidths=2)
    
    # Draw node labels
    nx.draw_networkx_labels(G_orig, pos_orig, ax=ax1, font_size=12, font_weight='bold')
    
    # Draw directed edges
    nx.draw_networkx_edges(G_orig, pos_orig, ax=ax1, edge_color='black', 
                           arrows=True, arrowsize=20, connectionstyle='arc3,rad=0.1')
    
    ax1.set_title('Original DAG\n(Red = Hidden, Blue = Observed)', fontsize=12, fontweight='bold')
    ax1.axis('off')
    
    # Add legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#3498db', edgecolor='black', label='Observed'),
        Patch(facecolor='#e74c3c', edgecolor='black', label='Hidden')
    ]
    ax1.legend(handles=legend_elements, loc='upper left', fontsize=10)
    
    # ========== RIGHT PLOT: Statement Graph ==========
    ax2 = axes[1]
    
    # Create networkx graph for statement graph
    G_stmt = nx.DiGraph()
    n_obs = len(obs_list)
    
    # Use original variable indices as labels
    G_stmt.add_nodes_from(obs_list)
    
    # Add directed edges
    directed_edges = []
    for i in range(n_obs):
        for j in range(n_obs):
            if directed_adj[i, j] > 0:
                directed_edges.append((obs_list[i], obs_list[j]))
    G_stmt.add_edges_from(directed_edges)
    
    # Find bidirected edges (only upper triangle to avoid duplicates)
    bidirected_edges = []
    for i in range(n_obs):
        for j in range(i + 1, n_obs):
            if bidirected_adj[i, j] > 0:
                bidirected_edges.append((obs_list[i], obs_list[j]))
    
    # Layout
    pos_stmt = nx.spring_layout(G_stmt, seed=42, k=2)
    
    # Draw nodes (all observed, so all blue)
    nx.draw_networkx_nodes(G_stmt, pos_stmt, ax=ax2, node_color='#3498db', 
                           node_size=700, edgecolors='black', linewidths=2)
    
    # Draw node labels
    nx.draw_networkx_labels(G_stmt, pos_stmt, ax=ax2, font_size=12, font_weight='bold')
    
    # Draw directed edges (black, solid)
    nx.draw_networkx_edges(G_stmt, pos_stmt, ax=ax2, edgelist=directed_edges,
                           edge_color='black', arrows=True, arrowsize=20,
                           connectionstyle='arc3,rad=0.1')
    
    # Draw bidirected edges (red, dashed, curved)
    for (u, v) in bidirected_edges:
        # Draw as two curved arrows pointing at each other
        ax2.annotate("", xy=pos_stmt[u], xytext=pos_stmt[v],
                    arrowprops=dict(arrowstyle="<->", color='#e74c3c', 
                                   connectionstyle="arc3,rad=0.3", lw=2, linestyle='--'))
    
    ax2.set_title('Statement Graph\n(Black = Directed, Red dashed = Bidirected)', 
                  fontsize=12, fontweight='bold')
    ax2.axis('off')
    
    if title:
        fig.suptitle(title, fontsize=14, fontweight='bold', y=1.02)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Figure saved to: {save_path}")
    
    plt.show()
    
    return fig


def visualize_random_dags(n: int = 4, m: int = 2, p: float = 0.5, 
                          num_examples: int = 4, seed: int = 42,
                          save_path: str = None):
    """
    Generate and visualize multiple random DAGs with their statement graphs.
    
    Parameters:
        n: Number of observed variables
        m: Number of hidden variables
        p: Edge probability
        num_examples: Number of random DAGs to generate
        seed: Base random seed
        save_path: Optional path to save the figure
    """
    fig, axes = plt.subplots(num_examples, 2, figsize=(14, 5 * num_examples))
    
    for idx in range(num_examples):
        # Generate random DAG
        A, perm, hidden = generate_random_dag(n, m, p, seed=seed + idx)
        total_vars = n + m
        observed = sorted(set(range(total_vars)) - hidden)
        
        # Compute statement graph
        directed_adj, bidirected_adj, obs_list = compute_statement_graph(A, hidden)
        
        # ========== LEFT: Original DAG ==========
        ax1 = axes[idx, 0] if num_examples > 1 else axes[0]
        
        G_orig = nx.DiGraph()
        G_orig.add_nodes_from(range(total_vars))
        
        for i in range(total_vars):
            for j in range(total_vars):
                if A[i, j] > 0:
                    G_orig.add_edge(i, j)
        
        node_colors = ['#e74c3c' if i in hidden else '#3498db' for i in range(total_vars)]
        pos_orig = nx.spring_layout(G_orig, seed=42 + idx, k=2)
        
        nx.draw_networkx_nodes(G_orig, pos_orig, ax=ax1, node_color=node_colors, 
                               node_size=500, edgecolors='black', linewidths=1.5)
        nx.draw_networkx_labels(G_orig, pos_orig, ax=ax1, font_size=10, font_weight='bold')
        nx.draw_networkx_edges(G_orig, pos_orig, ax=ax1, edge_color='black', 
                               arrows=True, arrowsize=15, connectionstyle='arc3,rad=0.1')
        
        ax1.set_title(f'DAG {idx + 1}: Hidden = {hidden}', fontsize=11, fontweight='bold')
        ax1.axis('off')
        
        # ========== RIGHT: Statement Graph ==========
        ax2 = axes[idx, 1] if num_examples > 1 else axes[1]
        
        G_stmt = nx.DiGraph()
        n_obs = len(obs_list)
        G_stmt.add_nodes_from(obs_list)
        
        directed_edges = []
        for i in range(n_obs):
            for j in range(n_obs):
                if directed_adj[i, j] > 0:
                    directed_edges.append((obs_list[i], obs_list[j]))
        G_stmt.add_edges_from(directed_edges)
        
        bidirected_edges = []
        for i in range(n_obs):
            for j in range(i + 1, n_obs):
                if bidirected_adj[i, j] > 0:
                    bidirected_edges.append((obs_list[i], obs_list[j]))
        
        pos_stmt = nx.spring_layout(G_stmt, seed=42 + idx, k=2)
        
        nx.draw_networkx_nodes(G_stmt, pos_stmt, ax=ax2, node_color='#3498db', 
                               node_size=500, edgecolors='black', linewidths=1.5)
        nx.draw_networkx_labels(G_stmt, pos_stmt, ax=ax2, font_size=10, font_weight='bold')
        nx.draw_networkx_edges(G_stmt, pos_stmt, ax=ax2, edgelist=directed_edges,
                               edge_color='black', arrows=True, arrowsize=15,
                               connectionstyle='arc3,rad=0.1')
        
        for (u, v) in bidirected_edges:
            ax2.annotate("", xy=pos_stmt[u], xytext=pos_stmt[v],
                        arrowprops=dict(arrowstyle="<->", color='#e74c3c', 
                                       connectionstyle="arc3,rad=0.3", lw=1.5, linestyle='--'))
        
        ax2.set_title(f'Statement Graph {idx + 1}', fontsize=11, fontweight='bold')
        ax2.axis('off')
    
    # Add overall legend at bottom
    from matplotlib.patches import Patch
    from matplotlib.lines import Line2D
    legend_elements = [
        Patch(facecolor='#3498db', edgecolor='black', label='Observed'),
        Patch(facecolor='#e74c3c', edgecolor='black', label='Hidden'),
        Line2D([0], [0], color='black', lw=2, label='Directed edge'),
        Line2D([0], [0], color='#e74c3c', lw=2, linestyle='--', label='Bidirected edge')
    ]
    fig.legend(handles=legend_elements, loc='lower center', ncol=4, fontsize=10,
               bbox_to_anchor=(0.5, -0.02))
    
    plt.suptitle(f'Random DAGs (n={n} observed, m={m} hidden, p={p})', 
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Figure saved to: {save_path}")
    
    plt.show()
    
    return fig


def generate_random_directed_graph(n: int, p: float, seed: int = None) -> np.ndarray:
    """
    Generate a random directed graph (possibly with cycles).
    
    Parameters:
        n: Number of vertices
        p: Probability of each directed edge
        seed: Random seed for reproducibility
    
    Returns:
        adjacency_matrix: n x n adjacency matrix where A[i,j] = 1 means edge i -> j
    """
    if seed is not None:
        np.random.seed(seed)
    
    # Sample each possible directed edge with probability p
    adjacency_matrix = (np.random.random((n, n)) < p).astype(int)
    
    # Remove self-loops
    np.fill_diagonal(adjacency_matrix, 0)
    
    return adjacency_matrix


def visualize_fas(A: np.ndarray, title: str = None, save_path: str = None):
    """
    Visualize a directed graph and highlight the Feedback Arc Set (FAS).
    
    Creates a figure with two subplots:
    - Left: Original graph with FAS edges highlighted in red
    - Right: Graph after removing FAS edges (should be acyclic)
    
    Parameters:
        A: Adjacency matrix of the directed graph
        title: Optional title for the figure
        save_path: Optional path to save the figure
    """
    n = A.shape[0]
    
    # Compute FAS
    fas = greedy_fas(A)
    fas_set = set(fas)
    
    # Create graph after removing FAS
    A_acyclic = remove_edges(A, fas)
    
    # Check if result is acyclic
    acyclic = is_acyclic(A_acyclic)
    
    # Create figure
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    
    # ========== LEFT: Original graph with FAS highlighted ==========
    ax1 = axes[0]
    
    G_orig = nx.DiGraph()
    G_orig.add_nodes_from(range(n))
    
    # Separate edges into FAS and non-FAS
    fas_edges = []
    non_fas_edges = []
    for i in range(n):
        for j in range(n):
            if A[i, j] > 0:
                if (i, j) in fas_set:
                    fas_edges.append((i, j))
                else:
                    non_fas_edges.append((i, j))
    
    G_orig.add_edges_from(fas_edges + non_fas_edges)
    
    pos = nx.spring_layout(G_orig, seed=42, k=2)
    
    # Draw nodes
    nx.draw_networkx_nodes(G_orig, pos, ax=ax1, node_color='#3498db', 
                           node_size=700, edgecolors='black', linewidths=2)
    nx.draw_networkx_labels(G_orig, pos, ax=ax1, font_size=12, font_weight='bold')
    
    # Draw non-FAS edges (black)
    nx.draw_networkx_edges(G_orig, pos, ax=ax1, edgelist=non_fas_edges,
                           edge_color='black', arrows=True, arrowsize=20,
                           connectionstyle='arc3,rad=0.1')
    
    # Draw FAS edges (red, thicker)
    nx.draw_networkx_edges(G_orig, pos, ax=ax1, edgelist=fas_edges,
                           edge_color='#e74c3c', arrows=True, arrowsize=20,
                           width=3, connectionstyle='arc3,rad=0.1')
    
    ax1.set_title(f'Original Graph\n(Red edges = FAS, {len(fas)} edges to remove)', 
                  fontsize=12, fontweight='bold')
    ax1.axis('off')
    
    # ========== RIGHT: Graph after FAS removal ==========
    ax2 = axes[1]
    
    G_acyclic = nx.DiGraph()
    G_acyclic.add_nodes_from(range(n))
    G_acyclic.add_edges_from(non_fas_edges)
    
    # Draw nodes
    nx.draw_networkx_nodes(G_acyclic, pos, ax=ax2, node_color='#2ecc71', 
                           node_size=700, edgecolors='black', linewidths=2)
    nx.draw_networkx_labels(G_acyclic, pos, ax=ax2, font_size=12, font_weight='bold')
    
    # Draw remaining edges
    nx.draw_networkx_edges(G_acyclic, pos, ax=ax2, edgelist=non_fas_edges,
                           edge_color='black', arrows=True, arrowsize=20,
                           connectionstyle='arc3,rad=0.1')
    
    status = "Acyclic" if acyclic else "Still has cycles!"
    ax2.set_title(f'After FAS Removal\n({status}, {len(non_fas_edges)} edges remaining)', 
                  fontsize=12, fontweight='bold')
    ax2.axis('off')
    
    # Legend
    from matplotlib.patches import Patch
    from matplotlib.lines import Line2D
    legend_elements = [
        Line2D([0], [0], color='black', lw=2, label='Kept edges'),
        Line2D([0], [0], color='#e74c3c', lw=3, label='FAS edges (removed)')
    ]
    fig.legend(handles=legend_elements, loc='lower center', ncol=2, fontsize=11,
               bbox_to_anchor=(0.5, -0.02))
    
    if title:
        fig.suptitle(title, fontsize=14, fontweight='bold', y=1.02)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Figure saved to: {save_path}")
    
    plt.show()
    
    return fig, fas


def visualize_random_graphs_fas(n: int = 5, p: float = 0.3, num_examples: int = 4, 
                                 seed: int = 42, save_path: str = None):
    """
    Generate and visualize multiple random directed graphs with their FAS solutions.
    
    Parameters:
        n: Number of vertices
        p: Edge probability
        num_examples: Number of random graphs to generate
        seed: Base random seed
        save_path: Optional path to save the figure
    """
    fig, axes = plt.subplots(num_examples, 2, figsize=(14, 5 * num_examples))
    
    for idx in range(num_examples):
        # Generate random directed graph
        A = generate_random_directed_graph(n, p, seed=seed + idx)
        
        # Compute FAS
        fas = greedy_fas(A)
        fas_set = set(fas)
        
        # Separate edges
        fas_edges = []
        non_fas_edges = []
        for i in range(n):
            for j in range(n):
                if A[i, j] > 0:
                    if (i, j) in fas_set:
                        fas_edges.append((i, j))
                    else:
                        non_fas_edges.append((i, j))
        
        # Create graphs
        G_orig = nx.DiGraph()
        G_orig.add_nodes_from(range(n))
        G_orig.add_edges_from(fas_edges + non_fas_edges)
        
        pos = nx.spring_layout(G_orig, seed=42 + idx, k=2)
        
        # ========== LEFT: Original with FAS highlighted ==========
        ax1 = axes[idx, 0] if num_examples > 1 else axes[0]
        
        nx.draw_networkx_nodes(G_orig, pos, ax=ax1, node_color='#3498db', 
                               node_size=500, edgecolors='black', linewidths=1.5)
        nx.draw_networkx_labels(G_orig, pos, ax=ax1, font_size=10, font_weight='bold')
        nx.draw_networkx_edges(G_orig, pos, ax=ax1, edgelist=non_fas_edges,
                               edge_color='black', arrows=True, arrowsize=15,
                               connectionstyle='arc3,rad=0.1')
        nx.draw_networkx_edges(G_orig, pos, ax=ax1, edgelist=fas_edges,
                               edge_color='#e74c3c', arrows=True, arrowsize=15,
                               width=2.5, connectionstyle='arc3,rad=0.1')
        
        total_edges = len(fas_edges) + len(non_fas_edges)
        ax1.set_title(f'Graph {idx + 1}: {total_edges} edges, FAS = {len(fas)} edges', 
                      fontsize=11, fontweight='bold')
        ax1.axis('off')
        
        # ========== RIGHT: After FAS removal ==========
        ax2 = axes[idx, 1] if num_examples > 1 else axes[1]
        
        A_acyclic = remove_edges(A, fas)
        acyclic = is_acyclic(A_acyclic)
        
        nx.draw_networkx_nodes(G_orig, pos, ax=ax2, node_color='#2ecc71', 
                               node_size=500, edgecolors='black', linewidths=1.5)
        nx.draw_networkx_labels(G_orig, pos, ax=ax2, font_size=10, font_weight='bold')
        nx.draw_networkx_edges(G_orig, pos, ax=ax2, edgelist=non_fas_edges,
                               edge_color='black', arrows=True, arrowsize=15,
                               connectionstyle='arc3,rad=0.1')
        
        status = "Acyclic" if acyclic else "Has cycles"
        ax2.set_title(f'After FAS removal: {len(non_fas_edges)} edges ({status})', 
                      fontsize=11, fontweight='bold')
        ax2.axis('off')
    
    # Legend
    from matplotlib.patches import Patch
    from matplotlib.lines import Line2D
    legend_elements = [
        Patch(facecolor='#3498db', edgecolor='black', label='Original nodes'),
        Patch(facecolor='#2ecc71', edgecolor='black', label='After FAS removal'),
        Line2D([0], [0], color='black', lw=2, label='Kept edges'),
        Line2D([0], [0], color='#e74c3c', lw=3, label='FAS edges')
    ]
    fig.legend(handles=legend_elements, loc='lower center', ncol=4, fontsize=10,
               bbox_to_anchor=(0.5, -0.02))
    
    plt.suptitle(f'Greedy FAS on Random Directed Graphs (n={n}, p={p})', 
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Figure saved to: {save_path}")
    
    plt.show()
    
    return fig


if __name__ == "__main__":
    # Example usage
    n = 4  # observed variables
    m = 2  # hidden variables
    p = 0.5  # edge probability
    
    adj_matrix, perm, hidden = generate_random_dag(n, m, p, seed=42)
    
    print(f"Total variables: {n + m}")
    print(f"Observed variables: {get_observed_variables(n + m, hidden)}")
    print(f"Hidden variables: {hidden}")
    print(f"\nTopological order (permutation): {perm}")
    print(f"\nAdjacency matrix:")
    print(adj_matrix)
    
    # Count edges
    num_edges = np.sum(adj_matrix)
    max_edges = (n + m) * (n + m - 1) // 2
    print(f"\nNumber of edges: {num_edges} / {max_edges} possible")
    
    # Visualize a single DAG and its statement graph
    print("\n" + "=" * 60)
    print("Visualizing single DAG and statement graph...")
    visualize_dag_and_statement_graph(adj_matrix, hidden, 
                                       title=f"Example: n={n}, m={m}, p={p}")
    
    # Visualize multiple random DAGs
    print("\n" + "=" * 60)
    print("Visualizing multiple random DAGs...")
    visualize_random_dags(n=4, m=2, p=0.5, num_examples=4, seed=42)
    
    # Visualize FAS on random directed graphs
    print("\n" + "=" * 60)
    print("Visualizing Greedy FAS on random directed graphs...")
    visualize_random_graphs_fas(n=6, p=0.35, num_examples=4, seed=123)
    
    # Demonstrate Greedy Transitivity Editing
    print("\n" + "=" * 60)
    print("Demonstrating Greedy Transitivity Editing (GreedyTE)...")
    
    # Create a sample DAG
    dag_adj, dag_perm, _ = generate_random_dag(n=5, m=0, p=0.4, seed=99)
    
    print(f"\nOriginal DAG adjacency matrix:")
    print(dag_adj)
    print(f"Number of edges: {np.sum(dag_adj)}")
    print(f"Is transitively closed: {is_transitively_closed(dag_adj)}")
    
    # Run GreedyTE
    E_del, E_add = greedy_transitivity_editing(dag_adj, verbose=True)
    
    # Apply and verify
    result = apply_transitivity_editing(dag_adj, E_del, E_add)
    print(f"\nResult adjacency matrix:")
    print(result)
    print(f"Number of edges: {np.sum(result)}")
    print(f"Is transitively closed: {is_transitively_closed(result)}")
    
    # Visualize
    visualize_transitivity_editing(dag_adj, E_del, E_add, 
                                    title="Greedy Transitivity Editing Example")
    
    # Demonstrate confounding path computation
    print("\n" + "=" * 60)
    print("Demonstrating confounding path computation...")
    
    # Create example with directed and bidirected edges
    # Directed: 0 -> 1, 1 -> 2, 0 -> 3
    directed = np.array([
        [0, 1, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ], dtype=float)
    
    # Bidirected: 0 <-> 2, 1 <-> 3
    bidirected = np.array([
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 1, 0, 0]
    ], dtype=float)
    
    print("Directed edges (i -> j):")
    print(directed)
    print("\nBidirected edges (i <-> j):")
    print(bidirected)
    
    confounding = compute_confounding_paths(directed, bidirected)
    print("\nConfounding path matrix:")
    print(confounding)
    
    # List confounding pairs
    print("\nConfounding pairs:")
    for i in range(confounding.shape[0]):
        for j in range(i + 1, confounding.shape[0]):
            if confounding[i, j] > 0:
                print(f"  {i} <-> {j} (confounding path exists)")
    
    # Demonstrate Greedy Confounding Path Closure
    print("\n" + "=" * 60)
    print("Demonstrating Greedy Confounding Path Closure (GreedyCPC)...")
    
    # Create a mixed graph example
    # Directed: 0 -> 1 -> 2 -> 3, 0 -> 2
    directed_cpc = np.array([
        [0, 1, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0]
    ], dtype=float)
    
    # Bidirected: 0 <-> 1, 0 <-> 3, 1 <-> 2
    bidirected_cpc = np.array([
        [0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]
    ], dtype=float)
    
    print("Directed edges (i -> j):")
    print(directed_cpc)
    print("\nOriginal bidirected edges (i <-> j):")
    print(bidirected_cpc)
    
    print(f"\nIs confounding path closed: {is_confounding_path_closed(directed_cpc, bidirected_cpc)}")
    
    # Run GreedyCPC
    B_del, B_add = greedy_confounding_path_closure(directed_cpc, bidirected_cpc, verbose=True)
    
    # Apply and verify
    result_bidirected = apply_confounding_path_closure(bidirected_cpc, B_del, B_add)
    print(f"\nResult bidirected adjacency matrix:")
    print(result_bidirected)
    print(f"\nIs confounding path closed: {is_confounding_path_closed(directed_cpc, result_bidirected)}")
    
    # List final bidirected edges
    print("\nFinal bidirected edges:")
    for i in range(result_bidirected.shape[0]):
        for j in range(i + 1, result_bidirected.shape[0]):
            if result_bidirected[i, j] > 0:
                print(f"  {i} <-> {j}")
    
    # Visualize GreedyCPC
    visualize_confounding_path_closure(directed_cpc, bidirected_cpc, B_del, B_add,
                                        title="Greedy Confounding Path Closure Example")
    
    # Demonstrate Incompatibility Score
    print("\n" + "=" * 60)
    print("Demonstrating Incompatibility Score...")
    
    # Create a mixed graph example (possibly with cycles)
    # Directed: 0 -> 1, 1 -> 2, 2 -> 0 (cycle!), 0 -> 3, 2 -> 3
    directed_compat = np.array([
        [0, 1, 0, 1],
        [0, 0, 1, 0],
        [1, 0, 0, 1],
        [0, 0, 0, 0]
    ], dtype=float)
    
    # Bidirected: 0 <-> 2, 1 <-> 3
    bidirected_compat = np.array([
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 1, 0, 0]
    ], dtype=float)
    
    print("\nInput directed edges:")
    print(directed_compat)
    print("\nInput bidirected edges:")
    print(bidirected_compat)
    
    score, details = incompatibility_score(directed_compat, bidirected_compat, verbose=True)
    
    print(f"\nFinal directed adjacency matrix:")
    print(details['final_directed'])
    print(f"\nFinal bidirected adjacency matrix:")
    print(details['final_bidirected'])
