data_dir: experiments/datasets
verbose: False

dataset: affNIST
batch_size: 1
num_workers: 1

energy: resnet18_mnist_classifier_logsumexp
outer: focal
num_hypothesis: 1
init_scale: 0.3
init_points: 5
n_iter: 5
opt_range_lower: -1.0
opt_range_upper: 1.0
seed: 1
