data_dir: experiments/datasets
verbose: False

dataset: affNIST
batch_size: 128
num_workers: 1

energy: resnet18_mnist_classifier_logsumexp
outer: its
its_mode: 8
n_samples: 16
n_hypotheses: 3
mc_steps: 16
change_of_mind: score
en_unique_class_condition: True
