_target_: srl.baselines.PDFM.trainer.PDFMLightningModule
basedir: "${paths.data_dir}/svi_data/place-pulse-2.0/pdfm/"
precomputed_features: False
plot_representation_space:
  save_representations_val: false
  save_representations_test: True
  save_plots: False
  show_plots: false
  plot_val: False
  val_n_epochs: 5
  plot_test: true
  token_index: 0
  title: "Image is Masked, CLS"
  save_dir: ${hydra:run.dir}/plots # Uses Hydra's run directory
