python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_tulu_qc_top10-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_tulu_qc_top10-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_tulu_qc_top10-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_tulu_qc_top10-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top3-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top3-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top3-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top3-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-falcon-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-falcon-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-falcon-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-falcon-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-25p-DCLM-baseline-75p-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-25p-DCLM-baseline-75p-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-25p-DCLM-baseline-75p-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-25p-DCLM-baseline-75p-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-50p-DCLM-baseline-50p-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-50p-DCLM-baseline-50p-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-50p-DCLM-baseline-50p-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-50p-DCLM-baseline-50p-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dolma1_7-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dolma1_7-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-75p-DCLM-baseline-25p-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-75p-DCLM-baseline-25p-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-dolma1_7-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-75p-DCLM-baseline-25p-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-75p-DCLM-baseline-25p-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-dolma1_7-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-60M-5xC/step29062-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top10p-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top10p-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top10p-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top10p-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw3-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw3-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw3-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw3-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_math_no_code-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_math_no_code-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_math_no_code-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_math_no_code-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_flan-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_flan-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_flan-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_flan-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-falcon-and-cc-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-falcon-and-cc-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-falcon-and-cc-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-falcon-and-cc-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top20p-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top20p-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top20p-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top20p-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_reddit-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_reddit-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_reddit-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_reddit-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top10-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top10-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top10-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top10-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/DCLM-baseline-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/DCLM-baseline-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-dclm-baseline-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/DCLM-baseline-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dclm-baseline-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/DCLM-baseline-4M-5xC/step5745-unsharded-hf" --repo_name DataDecide-dclm-baseline-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma-v1-6-and-sources-baseline-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-dolma1_6plus-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma-v1-6-and-sources-baseline-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dolma1_6plus-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma-v1-6-and-sources-baseline-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-dolma1_6plus-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma-v1-6-and-sources-baseline-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-dolma1_6plus-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/fineweb_edu_dedup-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-fineweb-edu-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/fineweb_edu_dedup-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-fineweb-edu-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/fineweb_edu_dedup-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-fineweb-edu-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/fineweb_edu_dedup-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-fineweb-edu-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_og_eli5_oh_top10p-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_og_eli5_oh_top10p-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_og_eli5_oh_top10p-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_og_eli5_oh_top10p-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_code-60M-5xC/step29062-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_code-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_code-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_code-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/c4-20M-5xC/step14594-unsharded-hf" --repo_name DataDecide-c4-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/c4-60M-5xC/step29052-unsharded-hf" --repo_name DataDecide-c4-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/c4-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-c4-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/c4-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-c4-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw2-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw2-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw2-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw2-4M-5xC/step5725-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/prox_fineweb_pro-60M-5xC/step29042-unsharded-hf" --repo_name DataDecide-fineweb-pro-60M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/prox_fineweb_pro-90M-5xC/step29901-unsharded-hf" --repo_name DataDecide-fineweb-pro-90M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/prox_fineweb_pro-20M-5xC/step14584-unsharded-hf" --repo_name DataDecide-fineweb-pro-20M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/prox_fineweb_pro-4M-5xC/step5735-unsharded-hf" --repo_name DataDecide-fineweb-pro-4M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_code-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top3-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top10p-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/c4-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-c4-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw3-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/fineweb_edu_dedup-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-fineweb-edu-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/baseline-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dolma1_7-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma-v1-6-and-sources-baseline-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dolma1_6plus-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw2-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_tulu_qc_top10-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/DCLM-baseline-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dclm-baseline-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top20p-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/prox_fineweb_pro-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-fineweb-pro-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-75p-DCLM-baseline-25p-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-50p-DCLM-baseline-50p-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-falcon-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-falcon-and-cc-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_math_no_code-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_reddit-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_flan-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_og_eli5_oh_top10p-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-25p-DCLM-baseline-75p-150M-5xC-2/step38157-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top10-150M-5xC/step38157-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/baseline-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dolma1_7-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-75p-DCLM-baseline-25p-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top10p-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-falcon-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw3-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw2-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/DCLM-baseline-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-falcon-and-cc-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/DCLM-baseline-50p-1B-5xC-2/step69369-unsharded-hf" --repo_name None --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-50p-DCLM-baseline-50p-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_og_eli5_oh_top10p-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top20p-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/fineweb_edu_dedup-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-fineweb-edu-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_math_no_code-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/prox_fineweb_pro-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-fineweb-pro-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_tulu_qc_top10-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma-v1-6-and-sources-baseline-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dolma1_6plus-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-25p-DCLM-baseline-75p-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_code-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_flan-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_reddit-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/c4-1B-5xC-2/step69369-unsharded-hf" --repo_name DataDecide-c4-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-50p-DCLM-baseline-50p-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-75p-DCLM-baseline-25p-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/fineweb_edu_dedup-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-fineweb-edu-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_flan-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top10p-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/prox_fineweb_pro-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-fineweb-pro-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/DCLM-baseline-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dclm-baseline-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw2-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dolma1_7-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top3-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top20p-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_og_eli5_oh_top10p-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw3-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_tulu_qc_top10-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_code-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-falcon-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_math_no_code-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/c4-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-c4-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma-v1-6-and-sources-baseline-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dolma1_6plus-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_reddit-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-25p-DCLM-baseline-75p-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc-750M-5xC-2/step63589-unsharded-hf" --repo_name DataDecide-falcon-and-cc-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top10-750M-5xC/step62500-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-300M-5xC/step45797-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-530M-5xC/step57776-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-1B-5xC/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-150M-5xC/step38167-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-750M-5xC/step63599-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top3-1B-5xC/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-150M-5xC/step38167-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-150M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-750M-5xC/step63599-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-750M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-530M-5xC/step57786-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-300M-5xC/step45797-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-1B-5xC/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top10-1B-5xC/step69369-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-1B --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/prox_fineweb_pro-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-fineweb-pro-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/fineweb_edu_dedup-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-fineweb-edu-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_tulu_qc_top10-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top10p-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw3-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_reddit-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/baseline-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dolma1_7-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma-v1-6-and-sources-baseline-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dolma1_6plus-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-25p-DCLM-baseline-75p-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-50p-DCLM-baseline-50p-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_flan-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top20p-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-falcon-and-cc-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/DCLM-baseline-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dclm-baseline-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/c4-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-c4-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-75p-DCLM-baseline-25p-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-falcon-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_og_eli5_oh_top10p-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_code-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top3-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw2-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_math_no_code-530M-5xC-2/step57776-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw2-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_flan-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_math_no_code-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-50p-DCLM-baseline-50p-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_og_eli5_oh_top10p-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/fineweb_edu_dedup-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-fineweb-edu-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_tulu_qc_top10-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-falcon-and-cc-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/DCLM-baseline-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dclm-baseline-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top10p-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon_and_cc_eli5_oh_top20p-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_reddit-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-25p-DCLM-baseline-75p-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/prox_fineweb_pro-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-fineweb-pro-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma-v1-6-and-sources-baseline-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dolma1_6plus-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dolma17-75p-DCLM-baseline-25p-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/no_code-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/baseline-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dolma1_7-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/c4-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-c4-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top3-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/falcon-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-falcon-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_ft7percentile_fw3-300M-5xC-2/step45787-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top10-530M-5xC/step57776-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-530M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/benb/dclm_fw_top10-300M-5xC/step45787-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-300M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-falcon-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_flan-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma-v1-6-and-sources-baseline-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dolma1_6plus-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/fineweb_edu_dedup-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-fineweb-edu-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-25p-DCLM-baseline-75p-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-50p-DCLM-baseline-50p-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_math_no_code-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/prox_fineweb_pro-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-fineweb-pro-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_reddit-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw2-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_code-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw3-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/c4-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-c4-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_og_eli5_oh_top10p-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top10p-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-falcon-and-cc-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top3-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-75p-DCLM-baseline-25p-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dolma1_7-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top20p-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_tulu_qc_top10-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top10-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/DCLM-baseline-10M-5xC/step15117-unsharded-hf" --repo_name DataDecide-dclm-baseline-10M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma-v1-6-and-sources-baseline-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dolma1_6plus-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_code-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dolma1_7-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-25p-DCLM-baseline-75p-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/fineweb_edu_dedup-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-fineweb-edu-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_reddit-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top3-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top10p-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-falcon-and-cc-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_og_eli5_oh_top10p-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top10-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-falcon-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top20p-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_math_no_code-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/DCLM-baseline-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/prox_fineweb_pro-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-fineweb-pro-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_tulu_qc_top10-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw2-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/c4-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-c4-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_flan-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-75p-DCLM-baseline-25p-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw3-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-50p-DCLM-baseline-50p-8M-5xC/step13039-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-8M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-75p-DCLM-baseline-25p-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-25p-DCLM-baseline-75p-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_flan-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/c4-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-c4-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-50p-DCLM-baseline-50p-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top10p-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma-v1-6-and-sources-baseline-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dolma1_6plus-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dolma1_7-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top20p-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_code-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_reddit-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/DCLM-baseline-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw2-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-falcon-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-falcon-and-cc-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_math_no_code-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/prox_fineweb_pro-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-fineweb-pro-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top10-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top3-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_og_eli5_oh_top10p-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/fineweb_edu_dedup-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-fineweb-edu-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw3-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_tulu_qc_top10-14M-5xC/step21953-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-14M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-falcon-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/DCLM-baseline-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dolma1_7-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_flan-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-25p-DCLM-baseline-75p-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/c4-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-c4-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-75p-DCLM-baseline-25p-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_math_no_code-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_tulu_qc_top10-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw3-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/fineweb_edu_dedup-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-fineweb-edu-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top10-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top10p-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_reddit-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_og_eli5_oh_top10p-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top20p-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_code-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-falcon-and-cc-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw2-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-50p-DCLM-baseline-50p-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/prox_fineweb_pro-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-fineweb-pro-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top3-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma-v1-6-and-sources-baseline-16M-5xC/step24432-unsharded-hf" --repo_name DataDecide-dolma1_6plus-16M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-falcon-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw3-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw3-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-75p-DCLM-baseline-25p-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-25p-dolma1.7-75p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_ft7percentile_fw2-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-7p-fw2-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-falcon-and-cc-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top20p-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-20p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-25p-DCLM-baseline-75p-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-75p-dolma1.7-25p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top10-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-10p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dclm_fw_top3-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-fw-3p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_code-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dolma1_7-no-code-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_eli5_oh_top10p-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-10p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_og_eli5_oh_top10p-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-orig-10p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/prox_fineweb_pro-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-fineweb-pro-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top10p-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-10p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dolma1_7-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_math_no_code-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dolma1_7-no-math-code-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_flan-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dolma1_7-no-flan-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/pos_eli5_oh_neg_dclm_refinedweb_steps_2000_lr3e4_top20p-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-qc-20p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/falcon_and_cc_tulu_qc_top10-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-falcon-and-cc-qc-tulu-10p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/DCLM-baseline-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma17-50p-DCLM-baseline-50p-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dclm-baseline-50p-dolma1.7-50p-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/fineweb_edu_dedup-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-fineweb-edu-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/dolma-v1-6-and-sources-baseline-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dolma1_6plus-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/c4-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-c4-6M --private
python upload_model.py --model_path "/data/input//ai2-llm/checkpoints/OLMo-ladder/davidh/no_reddit-6M-5xC/step9182-unsharded-hf" --repo_name DataDecide-dolma1_7-no-reddit-6M --private
