dataset: "credit"
train_batch_size: 10000
test_batch_size: 256
calib_batch_size: 256
n_calib: 0.2
n_test: 0.1
n_calib_val: 0.15
n_train: 50000
n_val: 0.1
data_root: "data/credit/"
m: 4

optimizer: "adam"
score_fn: "saps"
lr: 0.005
epochs: 15

h_params_raps:
  T: 0.2
  kreg: 3
  lamda: 0.5