import re
import os
import json
import tqdm
import torch
import numpy as np
from PIL import Image
import diffusion_feature

from components.caption_dataset import get_dataset

from configs.current_model import ModelConfig
from configs.current_dataset import DatasetConfig


# settings
model_config = ModelConfig()
dataset_config = DatasetConfig()

# a. basic setting
version = model_config.version
img_size = model_config.img_size
device = 'cuda'
add_background_token = dataset_config.add_background_token
add_missing_class = dataset_config.add_missing_class

input_file = dataset_config.caption_input_file
output_file = dataset_config.caption_output_file.replace(
    dataset_config.name, f'{dataset_config.name}-{model_config.name}'
)
pre_path = output_file[:output_file.rfind('/')]
os.makedirs(pre_path, exist_ok=True)

test_set = get_dataset(
    dataset_config.which_dataset,
    dataset_config.sample,
    dataset_config.label,
    dataset_config.limit,
    dataset_config.additional_annotation if hasattr(dataset_config, 'additional_annotation') else None,
)


# 0. prepare captioner

df = diffusion_feature.FeatureExtractor(
    layer={},
    version=version,
    img_size=img_size,
    device='cuda',
)

with open(input_file) as f:
    all_captions = json.load(f)

# tokenizers

def raw_tokenization(s):
    out = df.pipe.tokenizer(
        s,
        padding="max_length",
        max_length=df.pipe.tokenizer.model_max_length,
        truncation=True,
    )
    input_ids = out['input_ids']
    vocab = df.pipe.tokenizer.get_vocab()
    vocab = {v:k for k, v in vocab.items()}
    input_tokens = [vocab[id] for id in input_ids]
    return input_tokens

def raw_tokenization_2(s):
    out = df.pipe.tokenizer_2(
        s,
        padding="max_length",
        max_length=df.pipe.tokenizer_2.model_max_length,
        truncation=True,
    )
    input_ids = out['input_ids']
    vocab = df.pipe.tokenizer_2.get_vocab()
    vocab = {v:k for k, v in vocab.items()}
    input_tokens = [vocab[id] for id in input_ids]
    return input_tokens

def sd15_tokenization(s):
    raw = raw_tokenization(s)
    refined = []
    for token in raw:
        if token == '<|startoftext|>':
            token = '<sos>'
        elif token == '<|endoftext|>':
            token = '<pad>'
        else:
            token = token.replace('</w>', '')
        refined.append(token)
    special_tokens = ['<sos>', '<pad>']
    global_tokens = ['<sos>']
    return refined, special_tokens, global_tokens

def t5_tokenization(s):
    raw = raw_tokenization(s)
    refined = []
    for token in raw:
        if token == '▁':
            token = '<insert>'
        elif token == '</s>':
            token = '<eos>'
        elif token == '<pad>':
            token = '<pad>'
        else:
            token = token.replace('▁', '')
        refined.append(token)
    special_tokens = ['<insert>', '<eos>', '<pad>']
    global_tokens = ['<eos>']
    return refined, special_tokens, global_tokens

def bert_tokenization(s):
    raw = raw_tokenization(s)
    refined = []
    for token in raw:
        if token == '[CLS]':
            token = '<sos>'
        elif token in ['[PAD]', '[SEP]']:
            token = '<pad>'
        refined.append(token)
    special_tokens = ['<sos>', '<pad>']
    global_tokens = ['<sos>']
    return refined, special_tokens, global_tokens

def bert_t5_tokenization(s):
    raw = raw_tokenization(s)
    raw_2 = raw_tokenization_2(s)
    refined = []
    for token in raw:
        if token == '[CLS]':
            token = '<sos>'
        elif token in ['[PAD]', '[SEP]']:
            token = '<pad>'
        refined.append(token)
    for token in raw_2:
        if token == '▁':
            token = '<insert>'
        elif token == '</s>':
            token = '<eos>'
        elif token == '<pad>':
            token = '<pad>'
        else:
            token = token.replace('▁', '')
        refined.append(token)

    special_tokens = ['<insert>', '<sos>', '<eos>', '<pad>']
    global_tokens = ['<sos>', '<eos>']
    return refined, special_tokens, global_tokens


to_save = {}
name_to_id = test_set.class_name
name_to_id = {idx: name for idx, name in enumerate(name_to_id)}
for i, (img, existent_objects_gt) in enumerate(tqdm.tqdm(test_set)):
    img_path = img
    sample_name = img_path.split('/')[-1]
    img = Image.open(img)

    with torch.no_grad():
        # generate caption
        caption = all_captions[sample_name]['caption']
        if caption[-1] == '.':
            caption = caption[:-1]
        if add_background_token:
            caption += ', background'
        # caption = 'a realistic photo, ' + caption
        caption = caption.lower()

        # the following function is generated by gpt-4o
        # to parse captions in certain format
        def split_with_parentheses(s):
            # Updated regex to split by commas that are *not* inside parentheses
            pattern = r'\([^)]*\)|[^,]+'
            temp_matches = re.findall(pattern, s)
            
            # Combine and clean up the matches
            result = []
            buffer = ""
            
            for part in temp_matches:
                if part.startswith("(") and part.endswith(")"):
                    result.append(part.strip())  # Full parentheses block
                elif "(" in part:  # Start of parentheses
                    buffer = part.strip()
                elif ")" in part:  # End of parentheses
                    buffer += f", {part.strip()}"
                    result.append(buffer)
                    buffer = ""
                elif len(buffer) > 0:  # Inside a parentheses buffer
                    buffer += f", {part.strip()}"
                else:
                    result.append(part.strip())
            
            return result
        entities = split_with_parentheses(caption)
        # entities = list(set(entities))
        entities = list({e: None for e in entities}.keys())

        # filter closures that contain multiple classes
        new_entities = []
        for e in entities:
            if '(' in e:
                # check what classes are contained in this closure
                we_have = e.replace('(','').replace(')', '').split(', ')
                results = []
                for object_idx, we_have_one in enumerate(we_have):
                    for idx, name in name_to_id.items():
                        if we_have_one in name and idx in existent_objects_gt:
                            results.append(object_idx)
                            break
                if len(results) < 2:
                    # case#1 no multiple classes, keep the supporting object
                    new_entities.append(e)
                else:
                    # case#2 multiple classes, exclude the supporting object
                    for idx in results:
                        new_entities.append(we_have[idx])
            else:
                # case#3 none closure
                new_entities.append(e)
        entities = list({e: None for e in new_entities}.keys())

        entities = [
            {'prompt': e.replace('(','').replace(')', ''), 'aligned class': None, 'is_closure': '(' in e}
            for e in entities
        ]

        # complement missing classes
        if add_missing_class:
            included_class = set()
            for e in entities:
                if e['is_closure']:
                    we_have = e['prompt'].split(', ')
                else:
                    we_have = [e['prompt']]
                results = []
                for we_have_one in we_have:
                    for idx, name in name_to_id.items():
                        if we_have_one in name and idx in existent_objects_gt:
                            results.append(idx)
                            break
                if len(results) > 0:
                    idx = results[0]
                    included_class.add(idx)
            missing_class = set(existent_objects_gt) - included_class
            for c in missing_class:
                entities.append({'prompt': name_to_id[c][0], 'aligned class': None, 'is_closure': False})

        caption = ', '.join([e['prompt'] for e in entities])
        # print(caption)
        # print(entities)

        # match entities with candidate classes
        existent_objects = {}
        for e in entities:
            if e['is_closure']:
                we_have = e['prompt'].split(', ')
            else:
                we_have = [e['prompt']]
            results = []
            for we_have_one in we_have:
                for idx, name in name_to_id.items():
                    if we_have_one in name and idx in existent_objects_gt:
                        results.append(idx)
                        break
            if len(results) > 0:
                idx = results[0]
                e['aligned class'] = idx
                existent_objects[idx] = []

        # compute token ids
        # tokenize the caption
        if version == '1-5':
            tokenizer = sd15_tokenization
        elif version == 'xl':
            tokenizer = sd15_tokenization
        elif version == 'pixart-sigma':
            tokenizer = t5_tokenization
        elif version == 'pixart-alpha':
            tokenizer = t5_tokenization
        elif version == 'hunyuan':
            tokenizer = bert_t5_tokenization
            df.pipe.tokenizer.model_max_length = 77
            df.pipe.tokenizer_2.model_max_length = 256
        elif version == 'flux':
            tokenizer = t5_tokenization
            df.pipe.tokenizer = df.pipe.tokenizer_2
            df.pipe.tokenizer.model_max_length = 512
        else:
            raise NotImplementedError
        caption_tokens, special_tokens, global_tokens = tokenizer(caption)
        caption_tokens = [{'token': t} for t in caption_tokens]


        # align entities to character ids
        for e in entities:
            start = caption.find(e['prompt'])
            end = start + len(e['prompt'])
            e['char_ids'] = (start, end)

        # align tokens to character ids
        idx = 0
        for t in caption_tokens:
            token = t['token']
            if token in special_tokens:
                t['char_ids'] = None
            else:
                offset = caption[idx:].find(token)
                start = idx + offset
                end = start + len(token)
                t['char_ids'] = (start, end)
                idx = end
            if idx == len(caption):
                idx = 0

        # align tokens to entities according to character ids
        for t in caption_tokens:
            # if t['token'] == 'realistic' or (t['token'] == 'photo' and t['char_ids'][1] <= 17):
            #     continue
            if t['char_ids']:
                if t['token'].lower() in ['a', 'an', 'the', 'and', ',', '.', '-']:
                    continue
                for idx, e in enumerate(entities):
                    if t['char_ids'][0] >= e['char_ids'][0] and t['char_ids'][1] <= e['char_ids'][1]:
                        t['entity'] = idx
                        break

        # compute token ids for classes and rescaling
        rescaling_token_id = []
        global_token_id = []
        background_objects = {}
        for token_id, t in enumerate(caption_tokens):
            if 'entity' in t:
                rescaling_token_id.append(token_id)
                class_id = entities[t['entity']]['aligned class']
                if class_id:
                    existent_objects[class_id].append(token_id)
                else:
                    entity_id = t['entity']
                    if entity_id not in background_objects:
                        background_objects[entity_id] = []
                    background_objects[entity_id].append(token_id)
            if t['token'] in global_tokens:
                global_token_id.append(token_id)
        background_objects = list(background_objects.values())

        # debug
        # if len(existent_objects) == 0:
        # for e in entities:
        #     print(e)
        # for c in caption_tokens:
        #     print(c)
            # print(caption)

        # final result
        # print(caption)
        # print(rescaling_token_id)
        # print(existent_objects)
        to_save[sample_name] = {
            'caption': caption,
            'rescaling_token_id': rescaling_token_id,
            'existent_objects': existent_objects,
            'global_token_id': global_token_id,
            'background_objects': background_objects,
        }

with open(output_file, 'w') as f:
    f.write(json.dumps(to_save))
