CUDA_VISIBLE_DEVICES=0 python -u finetune_lm.py \
    --model_name_or_path [model_path] \
    --config_name "llama_1_50_7b" \
    --dataset_name c4 \
    --num_train_epochs 1 \
    --block_size 2048 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --max_train_samples 30000 \
    --max_eval_samples 128 \
    --learning_rate 5e-5 \
    --overwrite_output_dir \
    --output_dir [output_dir]
