experiment:
  seed: 42
  dataset_path: ${oc.env:DATA_PATH}/Market-1501-v15.09.15
  data_dir: ${oc.env:DATA_PATH}/market1501
  output_dir: results/reid
  pca_enabled: false

splits: ['gallery', 'train', 'query']
encoders: [openai/clip-vit-base-patch16]
