experiment:
  seed: 42
  dataset: cifar100
  output_dir: ./results/semanticity
  data_dir: ${oc.env:DATA_PATH}/cifar100/
  pca_enabled: false
  stratified: false
  sample_counts: [45000]
  add_model: false

splits: [train, validation, test]

data:
  validation_size: 5000
  stratify_column: fine_label

transforms:
  canny:
    auto_k: 0.5
    thicken: 1
    p_corruption: 0.85
    p_complete: 1.0
  scharr:
    thicken: 1
    p_corruption: 0.85
    p_complete: 1.0
  dog:
    sigma1: 1.0
    sigma2: 2.5
    p_corruption: 0.85
    p_complete: 1.0
  gaussian:
    blur_sigma: 10
    noise_std: 25.0
    p_corruption: 0.85
    p_complete: 1.0


experiments:
  standard:
    modes: [complete]
    kinds: [colour]
    encoders:
      - [microsoft/resnet-18, WinKawaks/vit-tiny-patch16-224]
    added_model: WinKawaks/vit-tiny-patch16-224
    
classifier:
  epochs: 100
  patience: 10
  lr: 0.001
