dataset_name: neulab/ted_multi
data_dir: ${oc.env:DATA_PATH}
pca_enabled: true
encoder_to_lang:
  roberta-base: en
  aubmindlab/bert-base-arabertv02: ar
  google-bert/bert-base-chinese: zh-cn
full_to_short_names:
  roberta-base: ROBER
  aubmindlab/bert-base-arabertv02: ARABE
  google-bert/bert-base-chinese: GCHROB
short_to_full_names:
  ROBER: roberta-base
  ARABE: aubmindlab/bert-base-arabertv02
  GCHROB: google-bert/bert-base-chinese
encoder_map:
  en: roberta-base
  ar: aubmindlab/bert-base-arabertv02
  he: avichr/heBERT
  ru: DeepPavlov/rubert-base-cased
  ko: kykim/bert-kor-base
  it: dbmdz/bert-base-italian-uncased
  ja: cl-tohoku/bert-base-japanese
  es: dccuchile/bert-base-spanish-wwm-uncased
  zh-cn: google-bert/bert-base-chinese
  fr: camembert-base
splits:
- train
- test
run_name: 9_multiret_m3_diverse
