[tool.poetry]
name = "xac"
version = "0.1.0"
description = ""
authors = ["anonymous"]
readme = "README.md"
packages = [{include = "xac", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
torch = "^2.7.0"
botorch = "^0.14.0"
gpytorch = "^1.14"
hydra-core = "^1.3.2"
wandb = "^0.19.11"
matplotlib = "^3.10.3"
pandas = "<2.3"
yahpo-gym = "^1.0.2"
openml = "^0.15.1"
seaborn = "^0.13.2"
threadpoolctl = "^3.6.0"
hydra-joblib-launcher = "^1.2.0"
shapiq = "^1.4.1"
xgboost = "3.0.5"
numpy = "<2"
shap = "<0.50"
tabpfn = "^6.2.0"
tabpfn-client = "^0.2.8"
lightgbm = "^4.6.0"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
ruff = "^0.11.11"
pre-commit = "^4.2.0"
mypy = "^1.15.0"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"