algorithm:
  name: FedFewS
  params:
    num_server_models: 6
experiment:
  name: agnews_fedfews_k6_noniid_dir_20_a0p5
  description: AG News - Dirichlet(α=0.5) - 20 clients - FedFewS (K=6)
  goal: k6
