algorithm:
  name: FedFewS
  params:
    num_server_models: 3
experiment:
  name: cifar10_fedfews_noniid_pat_20
  description:
    CIFAR-10 - Pathological - 20 clients - FedFewS (STCH-Set dual-layer
    weights)
  goal: ours
