from .voting0 import *
from .voting1 import *
from .voting2 import *
from .voting3 import *
from .voting4 import *
from .election1 import *
from .election2 import *
from .golf import *
from .golf2 import *
from .golf_geo import *
from .golf_geo2 import *
from .golf_geo3 import *