# General
pypot_from_matplot: True
# Prediction Plots:
pred_vega: True
pred_vega_add_calib: True
pred_matplot: True
pred_full_ts_matplot: True
ensemble_matplot: True
# Epsilon Plots:
eps_matplot: True
# Prediction Table:
pred_table: True
# Rolling Metrics
rolling_overall: False
rolling_per_ts: False
rolling_as_list: False
rolling_window: 40
# Attention
att_plot_vega: False
att_plot_vega_topk: 30
att_hist_matplot: False
