_target_: src.models.nets.mlp.Model
_partial_: true
name: mlp
input_size: ${data.input_size}
output_size: ${data.output_size}
num_channels: ${data.num_channels}
loss_names: ['loss_tar']
dim: 128
if_snr: false
with_revin: true
eps: 1e-8