defaults:
  - train_on_curated_data
  - _self_

epochs: 30
scheduler_step: 15
load_ckpt: ""

data:
  train:
    dataset_name: "curated"  
    num_samples: -1
    train_val_split: 0.9
    augmentations:
      enabled: true
  val:
    dataset_name: "curated"
    num_samples: -1
    train_val_split: 0.9
