dataset:
  BZR:
    cutoff: 13
    dropout: 0.05
    hidden_paths: 350
    l2: 0.004
    lr: 0.0748
    norm: batch_norm
    norm_attr: true
  COLLAB:
    cutoff: null
    dropout: 0.4
    hidden_paths: 700
    l2: 0.0005
    lr: 0.0025
    norm: layer
    norm_attr: true
  DD:
    cutoff: 68
    dropout: 0.15
    hidden_paths: 300
    l2: 0.081
    lr: 0.0015
    norm: layer
    norm_attr: false
  IMDB-BINARY:
    cutoff: null
    dropout: 0.25
    hidden_paths: 700
    l2: 1.423e-05
    lr: 0.0526
    norm: batch_norm
    norm_attr: false
  IMDB-MULTI:
    cutoff: null
    dropout: 0.2
    hidden_paths: 300
    l2: 0.00253
    lr: 0.0325
    norm: batch_norm
    norm_attr: false
  MUTAG:
    cutoff: 5
    dropout: 0.4
    hidden_paths: 600
    l2: 0.0024
    lr: 0.0007
    norm: batch_norm
    norm_attr: true
  NCI1:
    cutoff: 38
    dropout: 0.2
    hidden_paths: 600
    l2: 1.96e-05
    lr: 0.001
    norm: batch_norm
    norm_attr: false
  PROTEINS:
    cutoff: 58
    dropout: 0.2
    hidden_paths: 400
    l2: 1.618e-05
    lr: 0.00895
    norm: batch_norm
    norm_attr: false
  PTC_MR:
    cutoff: 30
    dropout: 0.05
    hidden_paths: 200
    l2: 0.0002
    lr: 0.0873
    norm: batch_norm
    norm_attr: false
  REDDIT-BINARY:
    cutoff: 20
    dropout: 0.35
    hidden_paths: 500
    l2: 7.24e-05
    lr: 0.01886
    norm: batch_norm
    norm_attr: true
  REDDIT-MULTI-5K:
    cutoff: 20
    dropout: 0.2
    hidden_paths: 200
    l2: 0.2
    lr: 0.2
    norm: batch_norm
    norm_attr: false
