deepseek:
  model_name: "deepseek-chat"
  api_base: "https://api.deepseek.com"
  api_key: xxx
deepseek-reasoner:
  model_name: "deepseek-reasoner"
  api_base: "https://api.deepseek.com"
  api_key: xxx