hp:
  T: 13
  act_fn: gelu
  alpha: 0.001
  batch_size: 128
  dataset: CIFAR10
  epochs: 30
  model: ResNet10
  optim:
    w:
      lr: 0.0007512356633853034
      wd: 3.173334999061517e-05
    x:
      lr: 0.803756844383156
      momentum: 0.1
  precision_type: S
  Forward_type: FU
  se_flag: true
