# @package _global_
defaults:
  - /task/pno
  - override /optimizer: adamw
  - override /model: fno1d
  - _self_

evaluation:
  mode: stochastic

training:
  epochs: 100
  batch_size: 64
  check_val_every_n_epoch: 1
  share_xy_normalizer: false

# IMPORTANT: model must output (mu, rho) or 2*C channels for (mu, rho)
model:
  out_channels: 2

pno:
  test_samples_per_example: 32
