data_dir: experiments/datasets
verbose: False

dataset: homNIST
batch_size: 128
num_workers: 1

energy: resnet18_mnist_classifier_logsumexp
outer: kinetic_langevin
temperature: 1.0
step_size: 0.0002
steps: 1600
friction: 1.0
clip_norm: 20.0
num_hypothesis: 4
init_scale: 0.0
dtype: float64
ensemble: False
