data_dir: experiments/datasets
verbose: False

dataset: homNIST
batch_size: 128
num_workers: 1

energy: resnet18_mnist_classifier_logsumexp
outer: lielac
optimizer: adam
step_size: 0.01
steps: 100
num_hypothesis: 64
init_scale: 0.3
