data_dir: experiments/datasets
verbose: False

dataset: homNIST
batch_size: 128
num_workers: 16

energy: lielac_vae_ar
outer: diffusion
temperature: 0.05
steps: 50
noise_min: 0.05
noise_max: 0.5
clip_norm: 100.0
num_mc: 4
num_hypothesis: 32
dtype: float32
