_target_: loader.config.TSDataConfig
dataset_type: stock
paths:
  - /some_base_dir/data/stock/META.csv
  - /some_base_dir/data/stock/MSFT.csv
  - /some_base_dir/data/stock/NFLX.csv
  - /some_base_dir/data/stock/AAPL.csv
add_config:
