from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeRegressor

_mpl_id = f"{os.environ.get('SLURM_ARRAY_JOB_ID', os.getuid())}-{os.environ.get('SLURM_ARRAY_TASK_ID', 'local')}"
_mpl_dir = Path(os.environ.get("TMPDIR", "/tmp")) / f"matplotlib-{_mpl_id}"
_mpl_dir.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(_mpl_dir))
os.environ.setdefault("NUMBA_THREADING_LAYER", "workqueue")

from scripts.processors.guide_c import GuideConstantProcessor
from scripts.processors.guide_utils import (
    find_guide_training_out,
    parse_guide_train_r2_and_elapsed,
    parse_mse,
    parse_r2,
    run_rscript,
    update_guide_model_r,
)


METHODS = {"cart", "guide"}
LAMBDAS = [0.1, 0.08, 0.05, 0.03, 0.01, 0.008, 0.005, 0.003, 0.001, 0.0005, 0.0001]
GUIDE_NODES = [2, 4, 6, 8, 10, 12, 14, 16, 20, 24, 28, 32]
GUIDE_ALIASES = {
    "temperature_min": "t_min",
    "temperature_max": "t_max",
    "california_housing": "ch",
}
RESULT_COLUMNS = [
    "dataset",
    "outer",
    "method",
    "depth",
    "lambda",
    "cv_folds",
    "n_thresholds",
    "threshold_label",
    "thresholds_strategy",
    "min_leaf_node_size",
    "val_r2",
    "val_mse",
    "train_time_s",
    "train_mse",
    "train_r2",
    "test_mse",
    "test_r2",
    "n_leaves",
]


class GuideConstantThresholdProcessor(GuideConstantProcessor):
    def _make_inp(
        self,
        dsc_path: Path,
        inp_path: Path,
        out_path: Path,
        r_path: Path,
        depth: int,
        max_nodes: int | None,
    ):
        base = Path.cwd()
        dsc_abs = f"./{dsc_path.resolve().relative_to(base).as_posix()}"
        out_abs = f"./{out_path.resolve().relative_to(base).as_posix()}"
        r_abs = f"./{r_path.resolve().relative_to(base).as_posix()}"

        lines = [
            'GUIDE       (do not edit this file unless you know what you are doing)',
            ' 45.0      (version of GUIDE that generated this file)',
            ' 1          (1=model fitting, 2=importance or DIF scoring, 3=data conversion)',
            f'"{out_abs}"  (name of output file)',
            ' 1          (1=one tree, 2=ensemble)',
            ' 2          (1=classification, 2=regression, 3=propensity score tree)',
            ' 1          (1=linear, 2=quantile, 3=Poisson, 4=censored response, 5=multiresponse or itemresponse, 6=longitudinal with T vars, 7=logistic)',
            ' 1          (1=least squares, 2=least median of squares)',
            ' 3          (0=stepwise, 1=multiple linear, 2=best simple polynomial, 3=constant, 4=ANCOVA)',
            ' 2          (1=interaction tests, 2=skip them)',
            ' 0          (0=tree with fixed no. of nodes, 1=prune by CV, 2=no pruning)',
            f" {max_nodes if max_nodes is not None else 100000}          (maximum number of terminal nodes of pruned tree)",
            f'"{dsc_abs}"  (name of DSC file)',
            ' 1          (1=split point from quantiles, 2=use exhaustive search)',
            ' 2          (1=default max number of splits on N and S variables, 2=specify number in next line)',
            ' 20         (max number of splits on N and S variables)',
            ' 2          (1=default max. number of split levels, 2=specify no. in next line)',
            f" {depth}   (max. no. split levels)",
            ' 1          (1=default min. node size, 2=specify min. value in next line)',
            ' 0          (0=no LaTeX code, 1=tree without node numbers, 2=tree with node numbers)',
            ' 1          (1=no storage, 2=store fit and split variables, 3=store split variables and values)',
            ' 1          (1=do not save fitted values and node IDs, 2=save in a file)',
            ' 2          (1=do not write R function, 2=write R function)',
            f'"{r_abs}" (R code file)',
            ' 1          (rank of top variable to split root node)',
        ]
        inp_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


class QuantileBinner:
    def __init__(self, n_thresholds: int):
        self.n_thresholds = int(n_thresholds)
        self.cuts_: list[np.ndarray] = []

    def fit(self, X: np.ndarray):
        self.cuts_ = []
        for feature in range(X.shape[1]):
            values = np.asarray(X[:, feature], dtype=float)
            values = values[np.isfinite(values)]
            unique = np.unique(values)
            if unique.size <= 1:
                self.cuts_.append(np.array([], dtype=float))
                continue
            if unique.size <= self.n_thresholds + 1:
                cuts = (unique[:-1] + unique[1:]) / 2.0
            else:
                raw = np.quantile(values, np.linspace(0, 1, self.n_thresholds + 2)[1:-1])
                cuts = []
                for value in raw:
                    left = unique[unique <= value]
                    right = unique[unique > value]
                    if left.size and right.size:
                        cuts.append((left[-1] + right[0]) / 2.0)
                cuts = np.unique(np.asarray(cuts, dtype=float))
            self.cuts_.append(cuts)
        return self

    def transform(self, X: np.ndarray) -> np.ndarray:
        out = np.empty_like(X, dtype=float)
        for feature, cuts in enumerate(self.cuts_):
            out[:, feature] = np.searchsorted(cuts, X[:, feature], side="right")
        return out

    def fit_transform(self, X: np.ndarray) -> np.ndarray:
        return self.fit(X).transform(X)


def load_xy(csv_path: Path):
    df = pd.read_csv(csv_path).apply(pd.to_numeric, errors="coerce").fillna(0.0)
    return df.iloc[:, :-1].to_numpy(float), df.iloc[:, -1].to_numpy(float)


def mse(y, pred):
    return float(np.mean((np.asarray(y) - np.asarray(pred)) ** 2))


def r2(y, pred):
    y = np.asarray(y)
    ss_tot = np.sum((y - np.mean(y)) ** 2)
    return 1.0 if ss_tot == 0 else float(1.0 - np.sum((y - pred) ** 2) / ss_tot)


def parse_list(raw: str, cast):
    return [cast(x.strip()) for x in raw.split(",") if x.strip()]


def cv_fold_count(n_samples: int, requested: int):
    if n_samples < 2:
        return 0
    return max(2, min(int(requested), int(n_samples)))


def timed(fn):
    start = time.time()
    out = fn()
    return out, time.time() - start


def threshold_dir_label(args):
    return str(args.n_thresholds)


def make_row(args, method, lambda_value, val_r2, val_mse, final):
    return {
        "dataset": args.name,
        "outer": f"outer_{args.outer}",
        "method": method,
        "depth": args.depth,
        "lambda": lambda_value,
        "cv_folds": args.cv_folds,
        "n_thresholds": args.n_thresholds,
        "threshold_label": threshold_dir_label(args),
        "thresholds_strategy": args.thresholds_strategy,
        "min_leaf_node_size": args.min_leaf_node_size,
        "val_r2": val_r2,
        "val_mse": val_mse,
        **final,
    }


def log_progress(final, val_r2, step_time, total_time, done, total):
    eta = total_time / max(1, done) * (total - done)
    print(
        f"    -> val_r2={val_r2:.6f}, test_r2={final['test_r2']:.6f}, "
        f"leaves={final['n_leaves']}, time={step_time:.1f}s, "
        f"elapsed={total_time / 60:.1f}min, ETA={eta / 60:.1f}min",
        flush=True,
    )


def cart_arrays(args, X_train, X_test):
    if threshold_dir_label(args) == "full":
        return X_train, X_test
    binner = QuantileBinner(args.n_thresholds)
    return binner.fit_transform(X_train), binner.transform(X_test)


def fit_eval_cart(args, lambda_, X_train, y_train, X_test, y_test):
    X_train_cart, X_test_cart = cart_arrays(args, X_train, X_test)
    model = DecisionTreeRegressor(
        max_depth=int(args.depth),
        min_samples_leaf=int(args.min_leaf_node_size),
        ccp_alpha=float(lambda_),
        random_state=42,
    )
    start = time.time()
    model.fit(X_train_cart, y_train)
    train_time = time.time() - start

    pred_train = model.predict(X_train_cart)
    pred_test = model.predict(X_test_cart)
    return {
        "train_time_s": float(train_time),
        "train_mse": mse(y_train, pred_train),
        "train_r2": r2(y_train, pred_train),
        "test_mse": mse(y_test, pred_test),
        "test_r2": r2(y_test, pred_test),
        "n_leaves": int(model.get_n_leaves()),
    }


def cv_score_cart(args, X, y, lambda_):
    n_splits = cv_fold_count(len(X), args.cv_folds)
    if n_splits < 2:
        return float("nan"), float("inf")

    val_r2, val_mse = [], []
    for train_idx, val_idx in KFold(n_splits, shuffle=True, random_state=42).split(X):
        res = fit_eval_cart(args, lambda_, X[train_idx], y[train_idx], X[val_idx], y[val_idx])
        val_r2.append(res["test_r2"])
        val_mse.append(res["test_mse"])
    return float(np.mean(val_r2)), float(np.mean(val_mse))


def run_cart(args, X_train, y_train, X_test, y_test):
    rows, start = [], time.time()
    for i, lambda_ in enumerate(LAMBDAS, start=1):
        step_start = time.time()
        print(f"[{i}/{len(LAMBDAS)}] cart outer_{args.outer} | lambda={lambda_}", flush=True)
        val_r2, val_mse = cv_score_cart(args, X_train, y_train, lambda_)
        if not np.isfinite(val_mse):
            print(f"[WARN] skip cart lambda={lambda_}: invalid CV", flush=True)
            continue
        final = fit_eval_cart(args, lambda_, X_train, y_train, X_test, y_test)
        rows.append(make_row(args, "cart", float(lambda_), val_r2, val_mse, final))
        log_progress(final, val_r2, time.time() - step_start, time.time() - start, i, len(LAMBDAS))
    return rows


def write_guide_csv(path: Path, X, y):
    path.parent.mkdir(parents=True, exist_ok=True)
    df = pd.DataFrame(X, columns=[f"X{i + 1}" for i in range(X.shape[1])])
    df["target"] = y
    df.to_csv(path, index=False)


def relative_to_root(path: Path):
    try:
        return f"./{path.resolve().relative_to(PROJECT_ROOT).as_posix()}"
    except ValueError:
        return path.as_posix()


def guide_eval_r(r_path: Path, train_csv: Path, eval_csv: Path, eval_r: Path):
    text = r_path.read_text(encoding="utf-8", errors="ignore")
    for src, dst in [
        (relative_to_root(train_csv), relative_to_root(eval_csv)),
        (train_csv.resolve().as_posix(), eval_csv.resolve().as_posix()),
        (train_csv.as_posix(), eval_csv.as_posix()),
        (train_csv.name, eval_csv.name),
    ]:
        text = text.replace(src, dst)
    eval_r.write_text(text, encoding="utf-8")
    update_guide_model_r(eval_r)
    out = run_rscript(eval_r)
    return parse_r2(out), parse_mse(out)


def fit_guide(proc, args, train_csv: Path, work_dir: Path, max_nodes: int):
    work_dir.mkdir(parents=True, exist_ok=True)
    model = proc.build(
        csv_path=train_csv,
        depth=args.depth,
        max_nodes=int(max_nodes),
        work_dir=work_dir,
        n_thresholds=args.n_thresholds,
        threshold_label=threshold_dir_label(args),
    )
    artifact, fit_time = timed(lambda: proc.fit(model, None, None))

    train_r2, elapsed = float("nan"), float("nan")
    train_out = find_guide_training_out(work_dir)
    if train_out is not None:
        train_r2, elapsed = parse_guide_train_r2_and_elapsed(train_out)
    fit_time = elapsed if np.isfinite(elapsed) else (artifact.extras or {}).get("fit_time", fit_time)
    return artifact, work_dir / "guide_model.R", float(fit_time), train_r2


def guide_cv(proc, args, X, y, root: Path, max_nodes: int):
    n_splits = cv_fold_count(len(X), args.cv_folds)
    if n_splits < 2:
        return float("nan"), float("inf")

    val_r2, val_mse = [], []
    for fold, (train_idx, val_idx) in enumerate(KFold(n_splits, shuffle=True, random_state=42).split(X), start=1):
        fold_dir = root / f"n{max_nodes}" / f"cv{fold}"
        train_csv, val_csv = fold_dir / "train_cv.csv", fold_dir / "valid_cv.csv"
        write_guide_csv(train_csv, X[train_idx], y[train_idx])
        write_guide_csv(val_csv, X[val_idx], y[val_idx])
        try:
            _, r_path, _, _ = fit_guide(proc, args, train_csv, fold_dir / "work", max_nodes)
            r2_val, mse_val = guide_eval_r(r_path, train_csv, val_csv, fold_dir / "work" / "valid_eval.R")
        except Exception as exc:
            print(f"[WARN] guide CV failed for max_nodes={max_nodes} fold={fold}: {exc}", file=sys.stderr, flush=True)
            return float("nan"), float("inf")
        val_r2.append(r2_val)
        val_mse.append(mse_val)
    return float(np.mean(val_r2)), float(np.mean(val_mse))


def run_guide(args, X_train, y_train, X_test, y_test):
    proc = GuideConstantThresholdProcessor()
    root = (
        Path("guide_save_constant")
        / GUIDE_ALIASES.get(args.name, args.name)
        / f"d{args.depth}_t{threshold_dir_label(args)}"
        / f"outer{args.outer}"
    )
    train_csv, test_csv = root / "train_raw.csv", root / "test_raw.csv"
    write_guide_csv(train_csv, X_train, y_train)
    write_guide_csv(test_csv, X_test, y_test)

    rows, start = [], time.time()
    for i, max_nodes in enumerate(args.guide_nodes, start=1):
        step_start = time.time()
        print(f"[{i}/{len(args.guide_nodes)}] guide outer_{args.outer} | max_nodes={max_nodes}", flush=True)
        val_r2, val_mse = guide_cv(proc, args, X_train, y_train, root, max_nodes)
        if not np.isfinite(val_mse):
            print(f"[WARN] skip guide max_nodes={max_nodes}: invalid CV", flush=True)
            continue

        try:
            artifact, r_path, train_time, train_r2 = fit_guide(proc, args, train_csv, root / f"n{max_nodes}" / "final", max_nodes)
            test_r2, test_mse = guide_eval_r(r_path, train_csv, test_csv, r_path.with_name("test_eval.R"))
            train_eval_r2, train_mse = guide_eval_r(r_path, train_csv, train_csv, r_path.with_name("train_eval.R"))
        except Exception as exc:
            print(f"[WARN] skip guide max_nodes={max_nodes}: final fit failed: {exc}", file=sys.stderr, flush=True)
            continue

        try:
            leaves = int(artifact.complexity)
        except Exception:
            leaves = int(max_nodes)
        final = {
            "train_time_s": train_time,
            "train_mse": train_mse,
            "train_r2": train_r2 if np.isfinite(train_r2) else train_eval_r2,
            "test_mse": test_mse,
            "test_r2": test_r2,
            "n_leaves": leaves,
        }
        rows.append(make_row(args, "guide", float(max_nodes), val_r2, val_mse, final))
        log_progress(final, val_r2, time.time() - step_start, time.time() - start, i, len(args.guide_nodes))
    return rows


def save_rows(args, method, rows):
    if not rows:
        raise RuntimeError(f"No rows produced for {method} {args.name} outer_{args.outer}")
    out_dir = (
        Path("results")
        / "baseline"
        / method
        / f"constant_regression_tree_depth{args.depth}_threshold_{threshold_dir_label(args)}"
        / args.name
        / f"outer{args.outer}"
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    dataset_filename = Path(args.name).name
    out_csv = out_dir / f"{dataset_filename}_outer{args.outer}_d{args.depth}.csv"
    pd.DataFrame(rows, columns=RESULT_COLUMNS).to_csv(out_csv, index=False)
    return out_csv


def run_method(args, method):
    split_dir = Path("data") / args.name / "splits" / f"outer_{args.outer}"
    X_train, y_train = load_xy(split_dir / "train.csv")
    X_test, y_test = load_xy(split_dir / "test.csv")
    print(f"{args.name} outer_{args.outer} | {method} | train={X_train.shape} test={X_test.shape}", flush=True)

    rows = (
        run_guide(args, X_train, y_train, X_test, y_test)
        if method == "guide"
        else run_cart(args, X_train, y_train, X_test, y_test)
    )
    print(f"Saved to {save_rows(args, method, rows)}", flush=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--name", required=True)
    parser.add_argument("--outer", type=int, required=True)
    parser.add_argument("--method", default="guide,cart")
    parser.add_argument("--depth", type=int, default=5)
    parser.add_argument("--cv_folds", type=int, default=3)
    parser.add_argument("--n_thresholds", type=int, default=20)
    parser.add_argument(
        "--threshold_label",
        default=None,
        help="Disabled for constant runs; threshold label is fixed to 20.",
    )
    parser.add_argument("--thresholds_strategy", default="quantile")
    parser.add_argument("--min_leaf_node_size", type=int, default=1)
    parser.add_argument("--guide_nodes", default=",".join(map(str, GUIDE_NODES)))
    args = parser.parse_args()

    if args.cv_folds < 2:
        raise ValueError("--cv_folds must be at least 2")
    if args.n_thresholds <= 0:
        raise ValueError("--n_thresholds must be positive")
    if args.n_thresholds != 20:
        raise ValueError("constant experiments are fixed to --n_thresholds 20")
    if args.threshold_label:
        raise ValueError("constant experiments are fixed to threshold label 20")
    if args.min_leaf_node_size < 1:
        raise ValueError("--min_leaf_node_size must be at least 1")

    args.guide_nodes = parse_list(args.guide_nodes, int)
    methods = parse_list(args.method, str)
    invalid = sorted(set(methods) - METHODS)
    if invalid:
        raise ValueError(f"Unknown method(s): {invalid}. Valid methods: {sorted(METHODS)}")

    for method in methods:
        run_method(args, method)


if __name__ == "__main__":
    main()
