import argparse

parser = argparse.ArgumentParser()

# imdb
def imdb():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_imdb', help='model_name')
    parser.add_argument('--dataset', type=str, default='imdb', help='dataset')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--weight_soft', type=int, default=7, help='smooth-sharp paramter7')
    parser.add_argument('--order', type=int, default=3, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=2048, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=128, help='latent_dim')
    parser.add_argument('--T0', type=int, default=850, help='first stage epoch')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=5e-6, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=1.0, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=0.4, help='tao_temp4')
    parser.add_argument('--beta_up0', type=float, default=0.2, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.2, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.001, help='gaussian noise std0.0001')
    args = parser.parse_args()
    return args

# wisconsin
def wisconsin():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_wisconsin', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--weight_soft', type=int, default=1, help='smooth-sharp paramter')
    parser.add_argument('--order', type=int, default=1, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=256, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=32, help='latent_dim')
    parser.add_argument('--lr', type=float, default=5e-4, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=1e-5, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=1.0, help='init value for fusion logits')
    parser.add_argument('--T0', type=int, default=1300, help='first stage epoch')
    parser.add_argument('--tao', type=float, default=0.4, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.4, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.2, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.01, help='gaussian noise std')
    args = parser.parse_args()
    return args


def acm():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_acm', help='model_name')
    parser.add_argument('--train', type=bool, default=False, help='training mode')
    parser.add_argument('--dataset', type=str, default='acm', help='dataset: acm')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--T0', type=int, default=750, help='first stage epoch')
    parser.add_argument('--weight_soft', type=int, default=10, help='smooth-sharp paramter')
    parser.add_argument('--order', type=int, default=1, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=128, help='latent_dim')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=5e-6, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=0, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=0.2, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.9, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.4, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.007, help='gaussian noise std')
    args = parser.parse_args()
    return args



# texas
def texas():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_texas', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=42, help='')
    parser.add_argument('--weight_soft', type=int, default=3, help='smooth-sharp paramter')
    parser.add_argument('--order', type=int, default=1, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=512, help='latent_dim')
    parser.add_argument('--T0', type=int, default=1200, help='first stage epoch')
    parser.add_argument('--lr', type=float, default=5e-3, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=5e-7, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=0.2, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=1, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.8, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.2, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.007, help='gaussian noise std')
    args = parser.parse_args()
    return args


# chameleon
def chameleon():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_chameleon', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=42, help='')
    parser.add_argument('--weight_soft', type=int, default=3, help='smooth-sharp paramter')
    parser.add_argument('--order', type=int, default=4, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=4, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=512, help='latent_dim')
    parser.add_argument('--T0', type=int, default=1200, help='first stage epoch')
    parser.add_argument('--lr', type=float, default=1e-3, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=1e-5, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=0.5, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=0.4, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.8, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.2, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.001, help='gaussian noise std')
    args = parser.parse_args()
    return args

# dblp
def dblp():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_dblp', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--weight_soft', type=int, default=6, help='smooth-sharp paramter')
    parser.add_argument('--order', type=int, default=1, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=512, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=64, help='latent_dim')
    parser.add_argument('--T0', type=int, default=1200, help='first stage epoch')
    parser.add_argument('--lr', type=float, default=4e-4, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=1e-8, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=0.7, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=1, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.9999, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.0, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.001, help='gaussian noise std')
    args = parser.parse_args()
    return args

def acm00():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_acm', help='model_name')
    parser.add_argument('--train', type=bool, default=False, help='training mode')
    parser.add_argument('--dataset', type=str, default='acm', help='dataset: acm')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--T0', type=int, default=750, help='first stage epoch')
    parser.add_argument('--weight_soft', type=int, default=10, help='smooth-sharp paramter')
    parser.add_argument('--order', type=int, default=1, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=128, help='latent_dim')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=5e-6, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=0, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=0.2, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.9, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.4, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.007, help='gaussian noise std')
    args = parser.parse_args()
    return args

def acm01():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_acm', help='model_name')
    parser.add_argument('--train', type=bool, default=False, help='training mode')
    parser.add_argument('--dataset', type=str, default='acm', help='dataset: acm')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--T0', type=int, default=750, help='first stage epoch')
    parser.add_argument('--weight_soft', type=int, default=10, help='smooth-sharp paramter')
    parser.add_argument('--order', type=int, default=2, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=128, help='latent_dim')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=5e-6, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=0, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=0.2, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.9, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.4, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.007, help='gaussian noise std')
    args = parser.parse_args()
    return args

def acm02():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_acm', help='model_name')
    parser.add_argument('--train', type=bool, default=False, help='training mode')
    parser.add_argument('--dataset', type=str, default='acm', help='dataset: acm')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--T0', type=int, default=750, help='first stage epoch')
    parser.add_argument('--weight_soft', type=int, default=10, help='smooth-sharp paramter')
    parser.add_argument('--order', type=int, default=2, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=128, help='latent_dim')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=5e-6, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=0, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=0.2, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.9, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.4, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.007, help='gaussian noise std')
    args = parser.parse_args()
    return args

def acm03():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_acm', help='model_name')
    parser.add_argument('--train', type=bool, default=False, help='training mode')
    parser.add_argument('--dataset', type=str, default='acm', help='dataset: acm')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--T0', type=int, default=750, help='first stage epoch')
    parser.add_argument('--weight_soft', type=int, default=9, help='smooth-sharp paramter9')
    parser.add_argument('--order', type=int, default=2, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=128, help='latent_dim')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=5e-6, help='weight decay6')
    parser.add_argument('--fusion_logit_init', type=float, default=0, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=0.2, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.9999, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.4, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.007, help='gaussian noise std')
    args = parser.parse_args()
    return args

def acm04():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_acm', help='model_name')
    parser.add_argument('--train', type=bool, default=False, help='training mode')
    parser.add_argument('--dataset', type=str, default='acm', help='dataset: acm')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--T0', type=int, default=750, help='first stage epoch')
    parser.add_argument('--weight_soft', type=int, default=9, help='smooth-sharp paramter9')
    parser.add_argument('--order', type=int, default=2, help='aggregation orders2')
    parser.add_argument('--order_h', type=int, default=2, help='aggregation orders2')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=128, help='latent_dim')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=5e-6, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=0, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=0.2, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.8, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.4, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.007, help='gaussian noise std')
    args = parser.parse_args()
    return args

def acm05():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='MVHGC_acm', help='model_name')
    parser.add_argument('--train', type=bool, default=False, help='training mode')
    parser.add_argument('--dataset', type=str, default='acm', help='dataset: acm')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    parser.add_argument('--T0', type=int, default=750, help='first stage epoch')
    parser.add_argument('--weight_soft', type=int, default=10, help='smooth-sharp paramter')
    parser.add_argument('--order', type=int, default=2, help='aggregation orders')
    parser.add_argument('--order_h', type=int, default=1, help='aggregation orders')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden_dim')
    parser.add_argument('--latent_dim', type=int, default=128, help='latent_dim')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=5e-6, help='weight decay')
    parser.add_argument('--fusion_logit_init', type=float, default=0, help='init value for fusion logits')
    parser.add_argument('--tao', type=float, default=0.2, help='tao_temp')
    parser.add_argument('--beta_up0', type=float, default=0.9, help='up bound')
    parser.add_argument('--beta_low0', type=float, default=-0.4, help='low bound')
    parser.add_argument('--sigma', type=float, default=0.007, help='gaussian noise std')
    args = parser.parse_args()
    return args
def get_settings(dataset='acm'):
    args_dic = {
        'imdb': imdb(),
        'wisconsin': wisconsin(),
        'acm': acm(),
        'dblp': dblp(),
        'texas': texas(),
        'chameleon': chameleon(),
        'acm00': acm00(),
        'acm01': acm01(),
        'acm02': acm02(),
        'acm03': acm03(),
        'acm04': acm04(),
        'acm05': acm05(),
    }
    return args_dic[dataset]
