defaults:
  - cci: cci_from_adata_multi
  - cluster: identity
  - cci_transform: default
  - inputs: cancer
  - _self_

rep:
  obsm_key: X_pca_whiten

align:
  alphas: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  use_previous_initialization: true

cost:
  fn:
    _target_: cellbridge.ot.cost.pairwise_sqeuclidean
    _partial_: true

  pipeline_transform:
    _target_: cellbridge.ot.cost.CostPipeline
    steps:

      - _target_: cellbridge.ot.cost.scale_FGW_multi
        _partial_: true
        numIterFGW: ${solver.numIterFGW}
        numIterEMD: ${solver.numIterEMD}

solver:
  _target_: cellbridge.ot.solvers.two_step_unbalanced_fgw_multi
  _partial_: true
  reg: 0.
  reg_marginals: 1
  numIterFGW: 10000
  numIterEMD: 500000
  numItermax_uot: 1000
  stopThr_uot: 1e-10

hydra:
  run:
    dir: ${oc.env:EXPERIMENTS_ROOT,/mnt/data/nvth2.data/experiments}/${inputs.name}/align_sweep/${oc.env:RUN_GROUP,${now:%Y-%m-%d}/${now:%H-%M-%S}}
