name: causalpe
channels:
  - conda-forge
dependencies:
  - python=3.14.0
  - pip
  - graphviz
  - pip:
      - numpy==2.4.1
      - scipy==1.17.0
      - matplotlib==3.10.8
      - graphviz==0.21
      - PyPDF2==3.0.1
