algorithm:
  name: FedFewS
  params:
    num_server_models: 3
    smooth_mu: 0.1
experiment:
  name: cifar10_fedfews_mu0p1_noniid_dir_20_a0p5
  description: CIFAR-10 - Dirichlet(α=0.5) - 20 clients - FedFewS (μ=0.1)
  goal: mu0p1