name: cenv
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - pillow
  - tqdm
  - ipython
  - notebook
  - ipykernel
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
      - torchsummary
      - torchattacks
      - medmnist
      - torchhk
