Train:
  alpha_s: 0.3
  alpha_t: 0.03
  attack_lr: 0.005
  batch_size: 64
  bef_tgr_len: 6
  dataset: PEMS03
  epsilon: 0.2
  hidden_dim: 64
  is_attacker_trained: false
  is_clean_train: false
  label_len: 0
  lam_norm: 0.05
  learning_rate: 0.0001
  num_train_epochs: 20
  pattern_len: 7
  pattern_type: cone
  pred_len: 12
  seq_len: 12
  surrogate_name: FEDformer
  token_len: 12
  trigger_len: 4
  warmup: 5
