algorithm:
  name: FedFewS
  params:
    num_server_models: 3
experiment:
  name: cifar10_fedfews_noniid_dir_10_a0p5
  description:
    CIFAR-10 - Dirichlet(α=0.5) - 10 clients - FedFewS (STCH-Set dual-layer
    weights)
  goal: ours
