import re
from typing import Any, Tuple, Optional
import torch
import torch.nn.functional as F
import json
from openai import OpenAI
import requests
import os
import random

openai_api_key = "EMPTY"
openai_api_base_list = [
    os.environ.get("LLM_AS_A_JUDGE_BASE", "http://10.136.116.36:18901/v1"),
]

client_list = []
for api_base in openai_api_base_list:
    client = OpenAI(
        api_key=openai_api_key,
        base_url=api_base,
    )
    client_list.append(client)
model_name_list = []
for client in client_list:
    response = requests.get(f"{api_base}/models")
    models = response.json()
    model_name_list.append(models['data'][0]['id'])

CAPTION_REWARD_PROMPT = """# ROLE
You are a strict reward model judge for grounded image captions.

# INPUTS
You will be given:
(1) A ground-truth caption (GT), written in grounded-conversation caption style.
(2) A rollout caption (ROLL), generated by a policy model, using special tokens:
- <|object_ref_start|> ... <|object_ref_end|> wraps a referred phrase.
- <|mt_start|> <|mt_xxxx|> <|mt_yyyy|> <|mt_end|> is the mask token span for that phrase.
These special tokens are allowed and should NOT be treated as grammatical errors.

# OBJECTIVE
Output a single boolean judgement indicating caption quality:
- true  : the rollout caption is a fluent, natural sentence AND captures the main visual content of the image, consistent with GT.
- false : otherwise.

# EVALUATION CRITERIA (ALL MUST PASS FOR true)
A. Fluency & Naturalness (mandatory)
- The rollout caption must read as a coherent, natural image caption.
- It must NOT degenerate into list-style or recall-driven enumeration, e.g.:
  "X is ... . Y is ... . Z is ... ." with weak or no narrative connection.
- Minor grammatical imperfections are acceptable; fragmented, repetitive, or template-like constructions are not.

B. Main Content Alignment with GT (mandatory)
- Compare the rollout caption with GT at the level of core semantics:
  main subject(s), main action(s), and overall scene.
- Different wording or level of detail is allowed.
- Missing the primary event, contradicting it, or focusing mainly on secondary details ⇒ false.
- Introducing major hallucinated actions or scenes not implied by GT ⇒ false.

C. Grounded Caption Usage (soft constraint)
- The use of <|object_ref_start|> ... <|object_ref_end|> and mask token spans is valid.
- However, abusing these tokens to stack many weakly-related phrases without forming a coherent sentence
  should be judged as failing fluency.

# OUTPUT FORMAT (STRICT)
Output ONLY one lowercase word:
- true
- false

Do NOT output numbers, symbols, punctuation, explanations, or additional text.

# DATA
## Ground Truth Caption (GT)
{gt_caption}

## Rollout Caption (ROLL)
{rollout_caption}

# FINAL JUDGEMENT
Answer:"""


def extract_mt_token_ids_v1(text):
    pattern = r"<\|mt_(\d{4})\|>"
    return [int(x) for x in re.findall(pattern, text)]

def extract_mt_token_ids_v2(text):
    pattern = re.compile(r'<\|mt_start\|><\|mt_(\d{4})\|><\|mt_(\d{4})\|><\|mt_end\|>')
    matches = pattern.findall(text)
    ret_list = []
    for num1, num2 in matches:
        ret_list.append(int(num1))
        ret_list.append(int(num2))
    return ret_list

def fix_mt_format_comprehensive(text):
    """
    全面修正 <|mt_...> 格式的函数。
    它会处理以下几种情况：
    1. 标记太少 (1个): <|mt_start|><|mt_0198|><|mt_end|> -> <|mt_start|><|mt_0198|><|mt_-1|><|mt_end|>
    2. 标记太少 (1个, 无end): <|mt_start|><|mt_0198|> -> <|mt_start|><|mt_0198|><|mt_-1|><|mt_end|>
    3. 标记太多 (3个或以上): <|mt_start|><|mt_0186|><|mt_0410|><|mt_0186|><|mt_end|> -> <|mt_start|><|mt_0186|><|mt_0410|><|mt_end|>
    4. 正确格式: <|mt_start|><|mt_0044|><|mt_0442|><|mt_end|> -> 不变
    """
    # 规则 1: 处理标记太多的情况 (3个或以上)
    # 捕获前两个，匹配掉多余的，然后用前两个重构
    pattern_too_many = r'(<\|mt_start\|>)(<\|mt_\d+\|>)(<\|mt_\d+\|>)(?:<\|mt_\d+\|>)+<\|mt_end\|>'
    replacement_too_many = r'\1\2\3<|mt_end|>'
    text = re.sub(pattern_too_many, replacement_too_many, text)
    # 规则 2: 处理标记太少的情况 (只有1个，且有<|mt_end|>)
    pattern_too_few_with_end = r'(<\|mt_start\|>)(<\|mt_\d+\|>)(<\|mt_end\|>)'
    replacement_too_few = r'\1\2<|mt_9999|><|mt_end|>'
    text = re.sub(pattern_too_few_with_end, replacement_too_few, text)
    # 规则 3: 处理标记太少的情况 (只有1个，且没有<|mt_end|>)
    # 使用负向前瞻确保后面不是另一个mt_token
    pattern_too_few_no_end = r'(<\|mt_start\|>)(<\|mt_\d+\|>)(?!<\|mt_)'
    replacement_too_few_no_end = r'\1\2<|mt_9999|><|mt_end|>'
    text = re.sub(pattern_too_few_no_end, replacement_too_few_no_end, text)
    return text
    
def extract_think_and_answer_robust(response: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Extracts the content between <think> and <answer> tags from a string,
    regardless of their order or position, as long as the tags exist.
    Args:
        response (str): The input string, potentially containing <think> and <answer> tags.
    Returns:
        Tuple[Optional[str], Optional[str]]: 
            A tuple containing (think_content, answer_content).
            Each element will be a string if found, or None if the corresponding tag is not found.
    """
    think_content = None
    answer_content = None
    # Pattern for <think> tag content
    # re.DOTALL allows '.' to match any character, including newlines.
    # Non-greedy match (.*?) ensures it stops at the first </think>.
    think_pattern = re.compile(r"<think>(.*?)</think>", re.DOTALL)
    # Pattern for <answer> tag content
    answer_pattern = re.compile(r"<answer>(.*?)</answer>", re.DOTALL)
    # Search for <think> content
    think_match = think_pattern.search(response)
    if think_match:
        think_content = think_match.group(1) # group(1) gets the content of the first capture group
    # Search for <answer> content
    answer_match = answer_pattern.search(response)
    if answer_match:
        answer_content = answer_match.group(1) # group(1) gets the content of the first capture group
    
    if answer_content is None or think_content is None:
        if '<answer>' in response:
            head, tail = response.split('<answer>', 1)
            if think_content is None:
                think_content = head
            if answer_content is None:
                answer_content = tail
        elif '</think>' in response:
            head, tail = response.split('</think>', 1)
            if think_content is None:
                think_content = head
            if answer_content is None:
                answer_content = tail

    return think_content, answer_content

def downsample_masks_half(masks: torch.Tensor, mode: str = "nearest") -> torch.Tensor:
    """
    Downsample masks to half of original spatial size (H/2, W/2).
    masks: (N, H, W)
    Returns: (N, H//2, W//2)
    """
    if masks.dtype == torch.bool:
        masks = masks.float()
    N, H, W = masks.shape
    # Ensure even division; interpolate handles odd sizes by floor with target
    target_h = max(1, H // 2)
    target_w = max(1, W // 2)
    masks = masks.unsqueeze(1)  # (N,1,H,W)
    masks_ds = F.interpolate(masks, size=(target_h, target_w), mode=mode)
    masks_ds = masks_ds.squeeze(1)
    return masks_ds

def compute_pairwise_iou(gt_masks: torch.Tensor, pred_masks: torch.Tensor, threshold: float = None) -> torch.Tensor:
    """
    Compute pairwise mask IoU between gt_masks and pred_masks.
    gt_masks: (N, H, W), pred_masks: (M, H, W)
    If threshold is not None, binarize masks by threshold.
    Returns IoU matrix of shape (N, M).
    """
    if threshold is not None:
        gt = (gt_masks >= threshold).float()
        pred = (pred_masks >= threshold).float()
    else:
        gt = gt_masks.float()
        pred = pred_masks.float()
    N, H, W = gt.shape
    M = pred.shape[0]
    gt_flat = gt.reshape(N, -1)      # (N, HW)
    pred_flat = pred.reshape(M, -1)  # (M, HW)
    inter = torch.matmul(gt_flat, pred_flat.t())  # (N, M)
    gt_area = gt_flat.sum(dim=1, keepdim=True)    # (N, 1)
    pred_area = pred_flat.sum(dim=1, keepdim=True) # (M, 1)
    union = gt_area + pred_area.t() - inter
    eps = 1e-7
    iou = inter / (union + eps)
    return iou.clamp(0.0, 1.0)

def hungarian_maximize(iou_matrix: torch.Tensor):
    """
    Maximum bipartite matching maximizing IoU via Hungarian algorithm.
    Returns:
      - matches: list of (gt_idx, pred_idx)
      - ious: list of IoU values
    """
    try:
        import numpy as np
        from scipy.optimize import linear_sum_assignment
        cost = (1.0 - iou_matrix).cpu().numpy()
        row_ind, col_ind = linear_sum_assignment(cost)
        matches = [(int(r), int(c)) for r, c in zip(row_ind, col_ind)]
        ious = [float(iou_matrix[r, c].item()) for r, c in zip(row_ind, col_ind)]
        return matches, ious
    except Exception:
        # Greedy fallback
        iou = iou_matrix.clone()
        N, M = iou.shape
        vals, idxs = torch.topk(iou.view(-1), k=iou.numel())
        used_rows, used_cols = set(), set()
        matches, ious = [], []
        for val, flat_idx in zip(vals.tolist(), idxs.tolist()):
            if val <= 0:
                break
            r = flat_idx // M
            c = flat_idx % M
            if r in used_rows or c in used_cols:
                continue
            used_rows.add(r)
            used_cols.add(c)
            matches.append((int(r), int(c)))
            ious.append(float(val))
            if len(used_rows) == N or len(used_cols) == M:
                break
        return matches, ious
    
def bipartite_match_by_mask_iou_half(
    gt_masks: torch.Tensor,
    pred_masks: torch.Tensor,
    binarize_threshold: float = 0.5,
    interp_mode: str = "nearest"
):
    """
    Downsample to half size, compute IoU, and perform maximum-weight matching.
    Returns:
      - matches: list[(gt_idx, pred_idx)]
      - ious: list[float]
    """
    assert gt_masks.ndim == 3 and pred_masks.ndim == 3, "Masks must be (N,H,W) and (M,H,W)"
    # Downsample to half of original size
    # gt_ds = downsample_masks_half(gt_masks, mode=interp_mode)
    # pred_ds = downsample_masks_half(pred_masks, mode=interp_mode)
    gt_ds = gt_masks
    pred_ds = pred_masks
    # Compute IoU with optional binarization
    iou_mat = compute_pairwise_iou(gt_ds, pred_ds, threshold=binarize_threshold)
    # Hungarian max matching
    matches, ious = hungarian_maximize(iou_mat)
    return matches, ious

def format_reward(response: str) -> float:
    pattern = re.compile(r"<think>.*?</think>\s*<answer>.*?</answer>", re.DOTALL)
    format_match = re.fullmatch(pattern, response)
    return 1.0 if format_match else 0.0

def mask_accuracy_reward(gt_masks: torch.Tensor, pred_masks: torch.Tensor):
    if gt_masks is None and pred_masks is None:
        return 1.0
    if gt_masks is None or pred_masks is None:
        return 0.0
    if gt_masks.ndim == 2:
        gt_masks = gt_masks.unsqueeze(0)
    if pred_masks.ndim == 2:
        pred_masks = pred_masks.unsqueeze(0)
    
    matches, ious = bipartite_match_by_mask_iou_half(gt_masks, pred_masks)
    denominator = max(len(gt_masks), len(pred_masks))
    return sum(ious) / denominator

def mask_token_accuracy_reward(answer_content: list[str], ground_truth: list[str]):
    if answer_content is None:
        return 0.0
    regex_pattern = r"<\|mt_start\|><\|mt_\d{4}\|><\|mt_\d{4}\|><\|mt_end\|>"
    target_mask_tokens = re.findall(regex_pattern, ground_truth)
    pred_mask_tokens = re.findall(regex_pattern, answer_content)
    if len(target_mask_tokens) == 0 and len(pred_mask_tokens) == 0:
        return 1.0
    unique_target_mask_tokens = list(set(target_mask_tokens))
    unique_pred_mask_tokens = list(set(pred_mask_tokens))
    max_N = max(len(pred_mask_tokens), len(target_mask_tokens))
    recall_N = 0
    for mask_token in unique_pred_mask_tokens:
        max_match_score = 0.0
        for gt_mask_token in unique_target_mask_tokens:
            match_score = compute_mask_token_accuracy_by_grading(mask_token, gt_mask_token)
            if max_match_score < match_score:
                max_match_score = match_score
        recall_N += max_match_score
    return recall_N / max_N

def compute_mask_token_accuracy_by_grading(one_answer: str, one_ground_truth: str):
    answer_tokens = re.findall(r"<\|[^|]*\|>", one_answer)
    gt_tokens = re.findall(r"<\|[^|]*\|>", one_ground_truth)
    if one_answer == one_ground_truth:
        return 1.0
    elif ''.join(answer_tokens[:-1]) == ''.join(gt_tokens[:-1]):  # both of the two token are matched up
        return 0.8
    elif ''.join(answer_tokens[:-2]) == ''.join(gt_tokens[:-2]): # only the first token are matched up
        return 0.4
    else:
        return 0.0

def extract_gcg_patterns(text):
    """
    Extracts specific pattern substrings and their second parts from a GCG task string.
    Args:
        text (str): The input string containing GCG task information.
    Returns:
        list: A list of tuples, where each tuple is (full_match, second_part).
              full_match is the complete matched string,
              second_part is the substring starting from <|object_ref_end|> to <|mt_end|>.
    """
    # Define the regular expression pattern to match the desired structure.
    # The pattern looks for:
    # 1. <|object_ref_start|>
    # 2. (.*?) - Non-greedy capture of the phrase between start and end object refs.
    # 3. \s*<|object_ref_end|> - The end object ref, preceded by zero or more whitespace characters.
    # 4. \s* - Zero or more whitespace characters between <|object_ref_end|> and <|mt_start|>.
    # 5. (<|mt_start|>(<|mt_\d+|>){2}<|mt_end|>) - This entire part is captured as 'second_part'.
    #    - <|mt_start|> - Literal match for the mt start tag.
    #    - (<|mt_\d+|>){2} - Matches exactly two mt tags, e.g., <|mt_0198|><|mt_0373|>.
    #      - \d+ matches one or more digits.
    #    - <|mt_end|> - Literal match for the mt end tag.
    pattern = r"<\|object_ref_start\|>(.*?)\s*<\|object_ref_end\|>\s*(<\|mt_start\|>(<\|mt_\d+\|>){2}<\|mt_end\|>)"
    # Find all non-overlapping matches of the pattern in the text.
    # re.findall returns a list of tuples, where each tuple contains the captured groups.
    # For our pattern, it will return (phrase, second_part_full, mt_code_group_1, mt_code_group_2).
    matches = re.findall(pattern, text)
    results = []
    phrases = []
    # Iterate through each match found.
    # 'phrase' is the content between <|object_ref_start|> and <|object_ref_end|>.
    # 'second_part_full' is the entire <|mt_start|><|mt_...|><|mt_...|><|mt_end|> block.
    # The last two '_' are placeholders for the inner capture groups of the mt codes, which we don't need directly here.
    for phrase, second_part_full, _ in matches:
        # Reconstruct the full matched string by combining the object_ref part and the mt part.
        # .strip() is used on 'phrase' to remove any leading/trailing whitespace that might have been captured.
        # full_match = f"<|object_ref_start|>{phrase.strip()}<|object_ref_end|>{second_part_full}"
        results.append(f"<|object_ref_end|>{second_part_full}")
        words = [word.strip().lower() for word in phrase.split(' ') if word.strip().lower() != '']
        if len(words) > 0:
            phrases.append(' '.join(words))

    return results, phrases

def glamm_gcg_mask_token_accuracy_reward(answer_content: str, ground_truth: str):
    if answer_content is None:
        return 0.0
    target_mask_tokens, _ = extract_gcg_patterns(ground_truth)
    pred_mask_tokens, _ = extract_gcg_patterns(answer_content)

    # print("=========>target_mask_tokens: ", target_mask_tokens)
    # print("=========>pred_mask_tokens: ", pred_mask_tokens)
    # print("=========>answer_content: ", answer_content)

    unique_pred_mask_tokens = list(set(pred_mask_tokens))
    unique_target_mask_tokens = list(set(target_mask_tokens))
    max_N = max(len(pred_mask_tokens), len(target_mask_tokens))
    recall_N = 0
    for mask_token in unique_pred_mask_tokens:
        max_match_score = 0.0
        for gt_mask_token in unique_target_mask_tokens:
            match_score = compute_mask_token_accuracy_by_grading(mask_token, gt_mask_token)
            if max_match_score < match_score:
                max_match_score = match_score
        recall_N += max_match_score
    return recall_N / max_N

def glamm_gcg_phrases_accuracy_reward(answer_content: str, ground_truth: str):
    if answer_content is None:
        return 0.0
    
    _, target_phrases = extract_gcg_patterns(ground_truth)
    _, pred_phrases = extract_gcg_patterns(answer_content)

    if len(target_phrases) == 0:
        return 1.0
    unique_pred_phrases = list(set(pred_phrases))
    max_N = max(len(pred_phrases), len(target_phrases))
    recall_N = 0
    for pred_phrase in unique_pred_phrases:
        if pred_phrase in target_phrases:
            recall_N += 1
    return recall_N / max_N
            
def psg_accuracy_reward(answer_content: str, ground_truth: str):
    pred_triplets, pred_text_triplets = extract_scene_graph_dicts(answer_content)
    gt_triplets, gt_text_triplets = extract_scene_graph_dicts(ground_truth)

    non_repeat_score = psg_non_repeat_reward(pred_text_triplets)

    max_N = max(len(pred_text_triplets), len(gt_text_triplets))
    recall_N = 0

    scanned_text_triplets = []
    for pred_triplet, pred_text_triplet in zip(pred_triplets, pred_text_triplets):
        if pred_text_triplet in scanned_text_triplets:
            continue
        scanned_text_triplets.append(pred_text_triplet)
        if pred_text_triplet in gt_text_triplets:
            recall_N += 1.0
            continue
        try:
            pred_sub_label = pred_triplet['subject']['label']
            pred_predicate = pred_triplet['predicate']
            pred_obj_label = pred_triplet['object']['label']
            pred_sub_mask_2d = pred_triplet['subject']['mask_2d']
            pred_obj_mask_2d = pred_triplet['object']['mask_2d']
        except:
            continue
        max_score = 0.0
        for gt_triplet in gt_triplets:
            try:
                gt_sub_label = gt_triplet['subject']['label']
                gt_predicate = gt_triplet['predicate']
                gt_obj_label = gt_triplet['object']['label']
                gt_sub_mask_2d = gt_triplet['subject']['mask_2d']
                gt_obj_mask_2d = gt_triplet['object']['mask_2d']
            except:
                continue

            match_score = 0.0
            if f"{pred_sub_label}#{pred_predicate}#{pred_obj_label}" == f"{gt_sub_label}#{gt_predicate}#{gt_obj_label}":
                match_score += 0.5
                sub_mask_token_match_score = compute_mask_token_accuracy_by_grading(pred_sub_mask_2d, gt_sub_mask_2d)
                match_score += sub_mask_token_match_score * 0.25
                obj_mask_token_match_score = compute_mask_token_accuracy_by_grading(pred_obj_mask_2d, gt_obj_mask_2d)
                match_score += obj_mask_token_match_score * 0.25
            if max_score < match_score:
                max_score = match_score
        recall_N += max_score
    return recall_N / max_N, non_repeat_score

def non_repeat_reward(predict_str: str) -> float:
    if predict_str is None:
        return 0.0
    regex_pattern = r"<\|mt_start\|><\|mt_\d{4}\|><\|mt_\d{4}\|><\|mt_end\|>"
    mask_tokens = re.findall(regex_pattern, predict_str)
    non_repeat_reward = 1.0
    for mask_token in mask_tokens:
        mask_token_count = predict_str.count(mask_token)
        if mask_token_count > 3:
            non_repeat_reward = 0.0
            break
    return non_repeat_reward

def psg_non_repeat_reward(text_triplets: list[str]):
    if len(text_triplets) == 0:
        return 1.0
    text_triplet_dict = {}
    for text_triplet in text_triplets:
        if text_triplet not in text_triplet_dict:
            text_triplet_dict[text_triplet] = 0
        text_triplet_dict[text_triplet] += 1
    if max(list(text_triplet_dict.values())) > 2:
        return 0.0
    else:
        return 1.0

def extract_scene_graph_dicts(text):
    pattern = r'''
    \{
    \s*"subject"\s*:\s*\{
        \s*"mask_2d"\s*:\s*"[^"]*"\s*,\s*
        \s*"label"\s*:\s*"[^"]*"\s*
    \}\s*,\s*
    \s*"predicate"\s*:\s*"[^"]*"\s*,\s*
    \s*"object"\s*:\s*\{
        \s*"mask_2d"\s*:\s*"[^"]*"\s*,\s*
        \s*"label"\s*:\s*"[^"]*"\s*
    \}
    \s*\}
    '''
    matches = re.findall(pattern, text, flags=re.DOTALL | re.VERBOSE)

    dicts, text_triplets = [], []
    for m in matches:
        try:
            d = json.loads(m)
            dicts.append(d)
            text_triplets.append(m)
        except json.JSONDecodeError:
            pass
    return dicts, text_triplets

def compute_score(reward_inputs: list[dict[str, Any]], format_weight: float = 0.1) -> list[dict[str, float]]:
    
    scores = []
    for reward_input in reward_inputs:
        source = reward_input["source"]

        if source in ['thinking_res', 'thinking_gres', 'thinking_ver', 'reasonseg']:
            format_score = format_reward(reward_input["response"])
            # print("===============>response: ", reward_input["response"])
            think_content, answer_content = extract_think_and_answer_robust(reward_input["response"])
            accuracy_score = mask_token_accuracy_reward(answer_content, reward_input["ground_truth"])
            think_content_no_repeat_score = non_repeat_reward(think_content)
            answer_content_no_repeat_score = non_repeat_reward(answer_content)
            scores.append(
                {
                    "overall": accuracy_score + format_score + think_content_no_repeat_score + answer_content_no_repeat_score,
                    "format": format_score,
                    "accuracy": accuracy_score,
                    "think_content_no_repeat_score": think_content_no_repeat_score,
                    "answer_content_no_repeat_score": answer_content_no_repeat_score,
                }
            )
        elif source in ['glamm_gcg']:
            accuracy_score = glamm_gcg_mask_token_accuracy_reward(reward_input["response"], reward_input["ground_truth"])
            phrase_score = glamm_gcg_phrases_accuracy_reward(reward_input["response"], reward_input["ground_truth"])
            no_repeat_score = non_repeat_reward(reward_input["response"])
            # # caption reward
            # client_idx = random.randint(0, len(client_list) - 1)
            # client = client_list[client_idx]
            # model_name = model_name_list[client_idx]
            # full_prompt = CAPTION_REWARD_PROMPT.format(
            #     gt_caption=reward_input["ground_truth"],
            #     rollout_caption=reward_input["response"],
            # )
            # caption_reward = 0.0
            # for ix in range(8):
            #     chat_response = client.chat.completions.create(
            #         model=model_name,
            #         messages=[
            #             {"role": "user", "content": full_prompt},
            #         ],
            #         seed = random.randint(0, 1000000),
            #         temperature=0.5,
            #     )
            #     response = chat_response.choices[0].message.content.strip()
            #     judgement = response.split('## Equivalence Judgement')[-1].lower()
            #     if 'true' in judgement and 'false' not in judgement:
            #         caption_reward = 1.0
            #         break
            #     elif 'false' in judgement and 'true' not in judgement:
            #         caption_reward = 0.0
            #         break
            #     else:
            #         print(f' [ERROR] judgement format invalid: {judgement}')
            #         continue
            # print("===========>(mask_acc, phrase_acc, no_repeat)=", (accuracy_score, phrase_score, no_repeat_score))
            scores.append(
                {
                    # "overall": accuracy_score + phrase_score + no_repeat_score + caption_reward,
                    "overall": accuracy_score + phrase_score + no_repeat_score,
                    "accuracy": accuracy_score,
                    "phrase_accuracy": phrase_score,
                    "no_repeat_score": no_repeat_score,
                    "caption_reward": caption_reward,
                }
            )
        elif source in ['padt_gcg', 'dw_gcg', 'res', 'gres', 'ver', 'coconut_seg']:
            accuracy_score = mask_token_accuracy_reward(reward_input["response"], reward_input["ground_truth"])
            no_repeat_score = non_repeat_reward(reward_input["response"])
            phrase_score = 1.0
            scores.append(
                {
                    "overall": accuracy_score + no_repeat_score + phrase_score,
                    "accuracy": accuracy_score,
                    "phrase_accuracy": phrase_score,
                    "no_repeat_score": no_repeat_score,
                }
            )
        elif source in ['psg']:
            accuracy_score, no_repeat_score = psg_accuracy_reward(reward_input['response'], reward_input['ground_truth'])
            phrase_score = 1.0
            scores.append(
                {
                    "overall": accuracy_score + no_repeat_score + phrase_score,
                    "accuracy": accuracy_score,
                    "phrase_accuracy": phrase_score,
                    "no_repeat_score": no_repeat_score,
                }
            )
        else:
            raise NotImplementedError
    
    return scores


if __name__ == "__main__":
    # text = "```json\n[{\"subject\": {\"mask_2d\": \"<|mt_start|><|mt_0017|><|mt_0322|><|mt_end|>\", \"label\": \"person\"}, \"predicate\": \"beside\", \"object\": {\"mask_2d\": \"<|mt_start|><|mt_0044|><|mt_0438|><|mt_end|>\", \"label\": \"person\"}},\n{\"subject\": {\"mask_2d\": \"<|mt_start|><|mt_0017|><|mt_0322|><|mt_end|>\", \"label\": \"person\"}, \"predicate\": \"standing on\", \"object\": {\"mask_2d\": \"<|mt_start|><|mt_0186|><|mt_0268|><|mt_end|>\", \"label\": \"grass-merged\"}},\n{\"subject\": {\"mask_2d\": \"<|mt_start|><|mt_0044|><|mt_0438|><|mt_end|>\", \"label\": \"person\"}, \"predicate\": \"holding\", \"object\": {\"mask_2d\": \"<|mt_start|><|mt_0116|><|mt_0448|><|mt_end|>\", \"label\": \"umbrella\"}},\n{\"subject\": {\"mask_2d\": \"<|mt_start|><|mt_0044|><|mt_0438|><|mt_end|>\", \"label\": \"person\"}, \"predicate\": \"standing on\", \"object\": {\"mask_2d\": \"<|mt_start|><|mt_0186|><|mt_0268|><|mt_end|>\", \"label\": \"grass-merged\"}},\n{\"subject\": {\"mask_2d\": \"<|mt_start|><|mt_0040|><|mt_0497|><|mt_end|>\", \"label\": \"fence-merged\"}, \"predicate\": \"in front of\", \"object\": {\"mask_2d\": \"<|mt_start|><|mt_0135|><|mt_0306|><|mt_end|>\", \"label\": \"tree-merged\"}},\n{\"subject\": {\"mask_2d\": \"<|mt_start|><|mt_0168|><|mt_0428|><|mt_end|>\", \"label\": \"sky-other-merged\"}, \"predicate\": \"over\", \"object\": {\"mask_2d\": \"<|mt_start|><|mt_0135|><|mt_0306|><|mt_end|>\", \"label\": \"tree-merged\"}}]\n```"
    # triplets = extract_scene_graph_dicts(text)
    # for triplet in triplets:
    #     subject_label = triplet['subject']['label']
    #     predicate = triplet['predicate']
    #     object_label = triplet['object']['label']
    #     print(f"{subject_label}#{predicate}#{object_label}")
    # print(triplets)
    caption = "<|object_ref_start|> A snowboarder <|object_ref_end|> <|mt_start|><|mt_0051|><|mt_0415|><|mt_end|> is grinding on <|object_ref_start|> a rail <|object_ref_end|> <|mt_start|><|mt_0006|><|mt_0293|><|mt_end|> ."
    bad_caption = "<|object_ref_start|> A snowboarder <|object_ref_end|> <|mt_start|><|mt_0051|><|mt_0415|><|mt_end|>. <|object_ref_start|> a rail <|object_ref_end|> <|mt_start|><|mt_0006|><|mt_0293|><|mt_end|> ."
    client_idx = random.randint(0, len(client_list) - 1)
    client = client_list[client_idx]
    model_name = model_name_list[client_idx]
    full_prompt = CAPTION_REWARD_PROMPT.format(
        gt_caption=caption,
        rollout_caption=bad_caption,
    )
    caption_reward = 0.0
    for ix in range(8):
        chat_response = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "user", "content": full_prompt},
            ],
            seed = random.randint(0, 1000000),
            temperature=0.5,
        )
        response = chat_response.choices[0].message.content.strip()
        print("============>>>response: ", response)
        judgement = response.lower()
        if 'true' in judgement and 'false' not in judgement:
            caption_reward = 1.0
            break
        elif 'false' in judgement and 'true' not in judgement:
            caption_reward = 0.0
            break
        else:
            print(f' [ERROR] judgement format invalid: {judgement}')
            continue
