hp:
  model: ResNet18
  dataset: CIFAR10
  T: 18
  act_fn: leaky_relu
  batch_size: 128
  epochs: 50
  precision_type: S
  alpha: 0.001
  se_flag: true
  optim:
    w:
      lr: 1.874539633446276e-05
      wd: 0.004918167427407904
    x:
      lr: 0.8879128023160621
      momentum: 0.5
