hp:
  model: ResNet10
  dataset: CIFAR10
  T: 10
  act_fn: leaky_relu
  batch_size: 128
  epochs: 50
  precision_type: S
  alpha: 1.0
  se_flag: true
  optim:
    w:
      lr: 0.0005401268407862822
      wd: 7.443804128279163e-05
    x:
      lr: 0.0025
      momentum: 0.9
