hp:
  model: ResNet18
  dataset: TinyImageNet
  T: 20
  act_fn: leaky_relu
  batch_size: 128
  epochs: 50
  precision_type: S
  alpha: 0.0005
  se_flag: true
  optim:
    w:
      lr: 0.0001031049826489835
      wd: 0.002243550060816361
    x:
      lr: 0.7389604706684876
      momentum: 0.9
