algorithm:
  name: FedFewS
  params:
    num_server_models: 3
experiment:
  name: fedisic2019_fedfews_natural
  description:
    Fed-ISIC2019 - 6 centers (natural domain shift) - FedFewS (STCH-Set
    dual-layer weights)
  goal: ours
