algorithm:
  name: FedFewS
  params:
    num_server_models: 3
experiment:
  name: agnews_fedfews_noniid_dir_20_a0p5
  goal: ours
  description: AG News - Dirichlet(α=0.5) - FedFewS (STCH-Set dual-layer weights)
