alpha: 0.1

h_params_saps:
  T: 0.74
  lamda: 0.28

hpo_iterations: 50
save_model_ckpt: true
model_checkpoint: null

llm_model: 'gpt-4o-mini'
conformal_result_dataset: ""
statistics_result_dataset: ""
statistics_dataset: ""

llm_temp: 0.7
llm_inference_repeats: 10
