"""
Generic ORB fine-tuning script suitable for Kaggle notebooks.
"""

from __future__ import annotations

import argparse
import inspect
import json
import math
import random
import hashlib
import time
from pathlib import Path
from typing import Dict, Mapping, MutableMapping, Optional, Sequence, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset, Subset

from orb_models.dataset.ase_sqlite_dataset import AseSqliteDataset
from orb_models.forcefield import base as ff_base
from orb_models.forcefield import property_definitions
from orb_models.forcefield import pretrained

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_BASE = REPO_ROOT / "models" / "trained"

KCAL_MOL_TO_EV = 1.0 / 23.060547
EV_TO_KCAL_MOL = 23.060547


def normalize_units(units: str) -> str:
    return units.strip().lower().replace(" ", "")


def resolve_data_unit_scale(units: str) -> float:
    key = normalize_units(units)
    if key in ("kcal/mol", "kcalmol", "kcal_per_mol", "kcalpermol", "kcal"):
        return KCAL_MOL_TO_EV
    if key in ("ev", "electronvolt", "electronvolts"):
        return 1.0
    raise ValueError(f"Unsupported data units '{units}'. Use 'kcal/mol' or 'eV'.")


def scale_batch_targets(batch: object, scale: float) -> None:
    if scale == 1.0:
        return
    node_targets = getattr(batch, "node_targets", None)
    if node_targets is not None and "forces" in node_targets:
        node_targets["forces"] = node_targets["forces"] * scale
    system_targets = getattr(batch, "system_targets", None)
    if system_targets is not None and "energy" in system_targets:
        system_targets["energy"] = system_targets["energy"] * scale
    graph_targets = getattr(batch, "graph_targets", None)
    if graph_targets is not None and "energy" in graph_targets:
        graph_targets["energy"] = graph_targets["energy"] * scale


def build_arg_parser() -> argparse.ArgumentParser:
    """Construct the CLI parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dataset-name",
        type=str,
        default=None,
        help="Logical dataset name used in logging.",
    )
    parser.add_argument(
        "--db-path",
        type=Path,
        default=None,
        help="Path to the ASE SQLite database generated by prepare_datasets.py.",
    )
    parser.add_argument(
        "--data-units",
        type=str,
        default="kcal/mol",
        help="Units of dataset targets (kcal/mol or eV). Targets are converted to eV for training.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_BASE,
        help="Directory where checkpoints and logs will be written (defaults to models/trained/<dataset-name>).",
    )
    parser.add_argument(
        "--base-model",
        type=str,
        default="orb-v2",
        choices=sorted(pretrained.ORB_PRETRAINED_MODELS.keys()),
        help="Pretrained ORB backbone to start from.",
    )
    parser.add_argument(
        "--model-size",
        type=str,
        choices=["tiny", "small", "full"],
        help="Shortcut to select a base model: tiny=orb-d3-xs-v2, small=orb-d3-sm-v2, full=orb-v2.",
    )
    parser.add_argument(
        "--precision",
        type=str,
        default="float32-high",
        choices=["float32-high", "float32-highest", "float64"],
        help="Floating point precision passed to the pretrained loader.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="auto",
        help="Torch device (cpu, cuda, cuda:0, mps, auto).",
    )
    parser.add_argument("--epochs", type=int, default=150, help="Number of training epochs.")
    parser.add_argument("--batch-size", type=int, default=16, help="Graphs per batch.")
    parser.add_argument("--lr", type=float, default=3e-4, help="Optimizer learning rate.")
    parser.add_argument("--weight-decay", type=float, default=1e-5, help="AdamW weight decay.")
    parser.add_argument(
        "--val-fraction",
        type=float,
        default=0.1,
        help="Fraction of samples reserved for validation (set 0 to disable).",
    )
    parser.add_argument(
        "--test-fraction",
        type=float,
        default=0.1,
        help="Fraction of samples reserved for test evaluation (set 0 to disable).",
    )
    parser.add_argument(
        "--split-seed",
        type=int,
        default=None,
        help="Seed used for deterministic train/val/test split (defaults to --seed when omitted).",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed.")
    parser.add_argument(
        "--accumulate-steps",
        type=int,
        default=1,
        help="Gradient accumulation steps to emulate larger batches.",
    )
    parser.add_argument(
        "--grad-clip",
        type=float,
        default=1.0,
        help="Gradient norm clip value (set <=0 to disable).",
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=2,
        help="PyTorch DataLoader workers per loader.",
    )
    parser.add_argument(
        "--compile-model",
        action="store_true",
        help="Enable torch.compile on the GNN backbone (may be slow on Kaggle).",
    )
    parser.add_argument(
        "--log-interval",
        type=int,
        default=25,
        help="Log training metrics every N batches.",
    )
    parser.add_argument(
        "--no-save-best",
        action="store_true",
        help="Disable writing an additional best-validation checkpoint.",
    )
    parser.add_argument(
        "--force-only",
        action="store_true",
        help="Train on forces only (energy head removed).",
    )
    parser.add_argument(
        "--save-every",
        type=int,
        default=0,
        help="Save an additional checkpoint every N epochs (0 disables periodic saves).",
    )
    parser.add_argument(
        "--resume-from",
        type=Path,
        default=None,
        help="Path to a checkpoint (.ckpt) to resume training from.",
    )
    parser.add_argument(
        "--resume-optimizer",
        action="store_true",
        help="When resuming, also load optimizer state (if present in the checkpoint).",
    )
    parser.add_argument(
        "--no-scheduler",
        action="store_true",
        help="Disable ReduceLROnPlateau learning-rate scheduler.",
    )
    parser.add_argument(
        "--scheduler-factor",
        type=float,
        default=0.5,
        help="Multiplicative factor for ReduceLROnPlateau.",
    )
    parser.add_argument(
        "--scheduler-patience",
        type=int,
        default=3,
        help="Epoch patience before LR reduction on plateau.",
    )
    parser.add_argument(
        "--scheduler-min-lr",
        type=float,
        default=1e-6,
        help="Minimum learning rate for scheduler.",
    )
    return parser


def resolve_device(device_arg: str) -> torch.device:
    """Map CLI device string to a torch.device."""
    if device_arg == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        if torch.backends.mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")
    return torch.device(device_arg)


def set_global_seed(seed: int) -> None:
    """Seed python, numpy, and torch RNGs."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def tensor_to_float(value: torch.Tensor | float | int) -> float:
    """Convert tensors numbers to python floats."""
    if isinstance(value, torch.Tensor):
        return float(value.detach().cpu().item())
    return float(value)


def accumulate_metrics(
    accumulator: MutableMapping[str, float], metrics: Mapping[str, torch.Tensor | float | int], weight: float
) -> MutableMapping[str, float]:
    """Weighted accumulate metrics."""
    for key, value in metrics.items():
        try:
            accumulator[key] = accumulator.get(key, 0.0) + tensor_to_float(value) * weight
        except TypeError:
            continue
    return accumulator


def finalize_metrics(accumulator: Mapping[str, float], total_weight: float) -> Dict[str, float]:
    """Reduce accumulated metrics."""
    if total_weight <= 0:
        return {}
    return {key: val / total_weight for key, val in accumulator.items()}


def to_cpu_state_dict(state_dict: Mapping[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
    """Detach tensors and move them to CPU for portability."""
    return {key: tensor.detach().cpu() for key, tensor in state_dict.items()}


def _hash_to_unit_interval(key: str, seed: int) -> float:
    """Stable hash -> [0,1) independent of PYTHONHASHSEED."""
    digest = hashlib.blake2b(f"{seed}:{key}".encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, "big") / float(2**64)


def _canonical_split_key(dataset: Dataset, idx: int) -> str:
    """Build a deterministic key for a sample using source_dataset/source_index metadata when available."""
    source_dataset = None
    source_index = None
    if hasattr(dataset, "db"):
        try:
            row = dataset.db.get(idx + 1)  # type: ignore[attr-defined]
            if row is not None:
                data = getattr(row, "data", {})
                source_dataset = data.get("source_dataset") or data.get("dataset")
                source_index = data.get("source_index")
        except Exception:
            pass
    if source_dataset is None:
        source_dataset = getattr(dataset, "name", dataset.__class__.__name__)
    if source_index is None:
        source_index = idx
    return f"{source_dataset}:{source_index}"


def deterministic_train_val_test_split(
    dataset: Dataset, val_fraction: float, test_fraction: float, seed: int
) -> Tuple[Dataset, Optional[Dataset], Optional[Dataset]]:
    """Split dataset with a deterministic hash so partitions align across datasets."""
    if val_fraction < 0.0 or test_fraction < 0.0:
        raise ValueError("val_fraction and test_fraction must be >= 0.")
    if val_fraction + test_fraction >= 1.0:
        raise ValueError("val_fraction + test_fraction must be < 1.0.")
    if (val_fraction <= 0.0 and test_fraction <= 0.0) or len(dataset) < 2:
        return dataset, None, None

    train_indices: list[int] = []
    val_indices: list[int] = []
    test_indices: list[int] = []

    val_cutoff = test_fraction + val_fraction

    for idx in range(len(dataset)):
        key = _canonical_split_key(dataset, idx)
        prob = _hash_to_unit_interval(key, seed)
        if test_fraction > 0.0 and prob < test_fraction:
            test_indices.append(idx)
        elif val_fraction > 0.0 and prob < val_cutoff:
            val_indices.append(idx)
        else:
            train_indices.append(idx)

    if val_fraction > 0.0 and not val_indices:
        if train_indices:
            val_indices.append(train_indices.pop())
        elif test_indices:
            val_indices.append(test_indices.pop())
    if test_fraction > 0.0 and not test_indices:
        if train_indices:
            test_indices.append(train_indices.pop())
        elif val_indices:
            test_indices.append(val_indices.pop())

    train_subset: Dataset = Subset(dataset, train_indices)
    val_subset: Optional[Dataset] = Subset(dataset, val_indices) if val_indices else None
    test_subset: Optional[Dataset] = Subset(dataset, test_indices) if test_indices else None

    for subset in (train_subset, val_subset, test_subset):
        if subset is not None and hasattr(dataset, "db"):
            subset.db = dataset.db  # type: ignore[attr-defined]

    return train_subset, val_subset, test_subset


def deterministic_train_val_split(
    dataset: Dataset, val_fraction: float, seed: int
) -> Tuple[Dataset, Optional[Dataset]]:
    """Backward-compatible train/val split wrapper (no test split)."""
    train_subset, val_subset, _ = deterministic_train_val_test_split(dataset, val_fraction, 0.0, seed)
    return train_subset, val_subset


def build_dataloaders(
    dataset: Dataset,
    batch_size: int,
    val_fraction: float,
    test_fraction: float,
    seed: int,
    num_workers: int,
) -> Tuple[DataLoader, Optional[DataLoader], Optional[Dataset]]:
    """Split dataset and construct train/val DataLoaders."""
    collate_fn = ff_base.batch_graphs
    train_subset, val_subset, test_subset = deterministic_train_val_test_split(
        dataset, val_fraction, test_fraction, seed
    )

    train_loader = DataLoader(
        train_subset,
        batch_size=batch_size,
        shuffle=True,
        collate_fn=collate_fn,
        num_workers=num_workers,
    )
    val_loader = None
    if val_subset is not None:
        val_loader = DataLoader(
            val_subset,
            batch_size=batch_size,
            shuffle=False,
            collate_fn=collate_fn,
            num_workers=num_workers,
        )
    return train_loader, val_loader, test_subset


def train_epoch(
    model: torch.nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    dtype: torch.dtype,
    accumulate_steps: int,
    grad_clip: float,
    log_interval: int,
    target_scale: float,
) -> Dict[str, float]:
    """Run one training epoch."""
    model.train()
    metrics_sum: Dict[str, float] = {}
    total_weight = 0.0
    optimizer.zero_grad(set_to_none=True)
    steps_since_update = 0

    for step, batch in enumerate(loader, start=1):
        batch = batch.to(device=device, dtype=dtype)
        scale_batch_targets(batch, target_scale)
        graphs_in_batch = float(batch.n_node.shape[0])
        total_weight += graphs_in_batch

        output = model.loss(batch)
        loss = output.loss / accumulate_steps
        loss.backward()
        steps_since_update += 1

        if steps_since_update == accumulate_steps:
            if grad_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)
            steps_since_update = 0

        metrics_sum = accumulate_metrics(metrics_sum, output.log, graphs_in_batch)

        if step % log_interval == 0:
            loss_val = tensor_to_float(output.log.get("loss", output.loss))
            print(f"  [train] step {step:04d} | loss={loss_val:.4f}")

    if steps_since_update:
        if grad_clip > 0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
        optimizer.step()
        optimizer.zero_grad(set_to_none=True)

    return finalize_metrics(metrics_sum, total_weight)


def eval_epoch(
    model: torch.nn.Module,
    loader: DataLoader,
    device: torch.device,
    dtype: torch.dtype,
    target_scale: float,
) -> Dict[str, float]:
    """Evaluate model on validation loader."""
    model.eval()
    metrics_sum: Dict[str, float] = {}
    total_weight = 0.0

    with torch.no_grad():
        for batch in loader:
            batch = batch.to(device=device, dtype=dtype)
            scale_batch_targets(batch, target_scale)
            graphs_in_batch = float(batch.n_node.shape[0])
            total_weight += graphs_in_batch
            output = model.loss(batch)
            metrics_sum = accumulate_metrics(metrics_sum, output.log, graphs_in_batch)

    return finalize_metrics(metrics_sum, total_weight)


def load_pretrained_model(
    base_model: str, device: torch.device, precision: str, compile_model: bool
) -> torch.nn.Module:
    """Load ORB pretrained backbone for fine-tuning."""
    loader = pretrained.ORB_PRETRAINED_MODELS[base_model]
    model = loader(device=device, precision=precision, compile=compile_model, train=True)
    return model


def save_checkpoint(path: Path, state: Mapping[str, object]) -> None:
    """Persist checkpoint state."""
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(state, path)


def load_checkpoint(path: Path) -> Dict[str, object]:
    """Load checkpoint state (map location CPU)."""
    checkpoint = torch.load(path, map_location="cpu")
    if not isinstance(checkpoint, dict):
        raise ValueError(f"Checkpoint at {path} is not a dictionary.")
    return checkpoint


def plot_loss_curves(history: Sequence[Mapping[str, object]], output_dir: Path, dataset_name: str) -> Optional[Path]:
    """Plot train/val loss history on a log scale and save to PNG."""
    def normalize_loss(value: object) -> Optional[float]:
        try:
            loss_val = float(value)
        except (TypeError, ValueError):
            return None
        if not math.isfinite(loss_val) or loss_val <= 0:
            return None
        return loss_val

    train_points: list[tuple[int, float]] = []
    val_points: list[tuple[int, float]] = []
    for entry in history:
        epoch = entry.get("epoch")
        if epoch is None:
            continue
        try:
            epoch_idx = int(epoch)
        except (TypeError, ValueError):
            continue
        train_loss = normalize_loss(entry.get("train", {}).get("loss") if isinstance(entry.get("train"), Mapping) else None)
        val_loss = normalize_loss(entry.get("val", {}).get("loss") if isinstance(entry.get("val"), Mapping) else None)
        if train_loss is not None:
            train_points.append((epoch_idx, train_loss))
        if val_loss is not None:
            val_points.append((epoch_idx, val_loss))

    if not train_points and not val_points:
        return None

    fig, ax = plt.subplots()
    if train_points:
        epochs, losses = zip(*train_points)
        ax.plot(epochs, losses, label="train", color="#1f77b4")
    if val_points:
        epochs, losses = zip(*val_points)
        ax.plot(epochs, losses, label="val", color="#d62728")
    ax.set_yscale("log")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss")
    ax.grid(True, which="both", linestyle="--", alpha=0.3)
    ax.legend()
    fig.tight_layout()
    output_path = output_dir / f"{dataset_name}_loss.png"
    fig.savefig(output_path, dpi=200)
    plt.close(fig)
    return output_path


def run_training(args: argparse.Namespace) -> None:
    """Execute the full training loop."""
    if args.output_dir == DEFAULT_OUTPUT_BASE and args.dataset_name:
        args.output_dir = DEFAULT_OUTPUT_BASE / args.dataset_name
    if args.val_fraction < 0.0 or args.test_fraction < 0.0:
        raise ValueError("--val-fraction and --test-fraction must be >= 0.")
    if args.val_fraction + args.test_fraction >= 1.0:
        raise ValueError("--val-fraction + --test-fraction must be < 1.")
    device = resolve_device(args.device)
    set_global_seed(args.seed)
    training_start = time.perf_counter()

    model = load_pretrained_model(args.base_model, device, args.precision, args.compile_model)
    model_dtype = next(model.parameters()).dtype
    target_scale = resolve_data_unit_scale(args.data_units)

    print(f"Using device={device.type} precision={model_dtype} base_model={args.base_model}")
    if target_scale != 1.0:
        print(f"Converting targets from {args.data_units} to eV for training.")

    target_config = property_definitions.PropertyConfig(
        node_names=["forces"],
        graph_names=[] if args.force_only else ["energy"],
    )

    if "stress" in model.heads:
        stress_target_name = model.heads["stress"].target.fullname
        if stress_target_name not in target_config.graph_properties:
            print("Removing stress head (no stress targets available for this dataset).")
            del model.heads["stress"]
            model.loss_weights.pop("stress", None)

    if args.force_only and "energy" in model.heads:
        print("Force-only mode: removing energy head and its loss.")
        del model.heads["energy"]
        model.loss_weights.pop("energy", None)

    dataset = AseSqliteDataset(
        name=args.dataset_name,
        path=args.db_path,
        system_config=model.system_config,
        target_config=target_config,
        dtype=model_dtype,
    )

    split_seed = args.split_seed if args.split_seed is not None else args.seed
    train_loader, val_loader, test_subset = build_dataloaders(
        dataset,
        batch_size=args.batch_size,
        val_fraction=args.val_fraction,
        test_fraction=args.test_fraction,
        seed=split_seed,
        num_workers=args.num_workers,
    )

    train_count = len(train_loader.dataset)
    val_count = len(val_loader.dataset) if val_loader is not None else 0
    test_count = len(test_subset) if test_subset is not None else 0
    print(
        f"Dataset {args.dataset_name}: total={len(dataset)} train={train_count}"
        + (f" val={val_count}" if val_loader is not None else "")
        + (f" test={test_count}" if test_subset is not None else "")
    )

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scheduler: Optional[torch.optim.lr_scheduler.ReduceLROnPlateau] = None
    if not args.no_scheduler and val_loader is not None:
        scheduler_kwargs = {
            "mode": "min",
            "factor": args.scheduler_factor,
            "patience": args.scheduler_patience,
            "min_lr": args.scheduler_min_lr,
        }
        if "verbose" in inspect.signature(torch.optim.lr_scheduler.ReduceLROnPlateau.__init__).parameters:
            scheduler_kwargs["verbose"] = True
        else:
            print("ReduceLROnPlateau.verbose not supported by this torch version; continuing without verbose logging.")
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, **scheduler_kwargs)
    elif not args.no_scheduler:
        print("Validation split disabled; skipping ReduceLROnPlateau scheduler.")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    history: list[dict[str, float | int | dict[str, float]]] = []
    best_val_loss = float("inf")
    best_state: Optional[Dict[str, torch.Tensor]] = None
    start_epoch = 1

    if args.resume_from:
        checkpoint = load_checkpoint(args.resume_from)
        model_state = checkpoint.get("model")
        if model_state is None:
            raise KeyError(f"Checkpoint {args.resume_from} does not contain 'model' weights.")
        model.load_state_dict(model_state)
        if args.resume_optimizer and "optimizer" in checkpoint:
            optimizer.load_state_dict(checkpoint["optimizer"])
        best_val_loss = float(checkpoint.get("best_val_loss", float("inf")))
        best_model_state = checkpoint.get("best_model")
        if isinstance(best_model_state, Mapping):
            best_state = {k: v.clone().cpu() for k, v in best_model_state.items() if isinstance(v, torch.Tensor)}
        if scheduler is not None and "scheduler" in checkpoint:
            scheduler.load_state_dict(checkpoint["scheduler"])
        previous_history = checkpoint.get("history")
        if isinstance(previous_history, list):
            history = list(previous_history)
        start_epoch = int(checkpoint.get("epoch", 0)) + 1
        print(f"Resuming from checkpoint {args.resume_from} (next epoch {start_epoch}).")

    last_epoch = start_epoch - 1

    for epoch in range(start_epoch, args.epochs + 1):
        epoch_start = time.time()
        train_metrics = train_epoch(
            model,
            train_loader,
            optimizer,
            device,
            model_dtype,
            args.accumulate_steps,
            args.grad_clip,
            args.log_interval,
            target_scale,
        )
        val_metrics = {}
        if val_loader is not None:
            val_metrics = eval_epoch(model, val_loader, device, model_dtype, target_scale)
            val_loss = val_metrics.get("loss", float("inf"))
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_state = to_cpu_state_dict(model.state_dict())

        elapsed = time.time() - epoch_start
        train_loss = train_metrics.get("loss", float("nan"))
        if val_loader is None:
            print(f"Epoch {epoch:03d}/{args.epochs:03d} | train_loss={train_loss:.4f} | {elapsed:.1f}s")
        else:
            val_loss = val_metrics.get("loss", float("nan"))
            print(
                f"Epoch {epoch:03d}/{args.epochs:03d} | train_loss={train_loss:.4f} | "
                f"val_loss={val_loss:.4f} | {elapsed:.1f}s"
            )
        history.append(
            {
                "epoch": epoch,
                "train": train_metrics,
                "val": val_metrics,
                "elapsed_seconds": elapsed,
            }
        )
        plateau_metric = (
            val_metrics.get("loss")
            if val_loader is not None
            else train_metrics.get("loss")
        )
        if scheduler is not None and plateau_metric is not None:
            metric_value = float(plateau_metric)
            if math.isfinite(metric_value):
                scheduler.step(metric_value)
        last_epoch = epoch

        if args.save_every > 0 and epoch % args.save_every == 0:
            periodic_state: Dict[str, object] = {
                "model": to_cpu_state_dict(model.state_dict()),
                "optimizer": optimizer.state_dict(),
                "epoch": epoch,
                "best_val_loss": best_val_loss,
                "history": history,
            }
            if best_state is not None:
                periodic_state["best_model"] = best_state
            if scheduler is not None:
                periodic_state["scheduler"] = scheduler.state_dict()
            checkpoint_path = args.output_dir / f"{args.dataset_name}_epoch{epoch:03d}.ckpt"
            save_checkpoint(checkpoint_path, periodic_state)
            print(f"Saved checkpoint at epoch {epoch} -> {checkpoint_path}")

    final_state: Dict[str, object] = {
        "model": to_cpu_state_dict(model.state_dict()),
        "optimizer": optimizer.state_dict(),
        "epoch": last_epoch,
        "best_val_loss": best_val_loss,
        "history": history,
    }
    if best_state is not None:
        final_state["best_model"] = best_state
    if scheduler is not None:
        final_state["scheduler"] = scheduler.state_dict()
    final_path = args.output_dir / f"{args.dataset_name}_final.ckpt"
    save_checkpoint(final_path, final_state)

    if best_state is not None and not args.no_save_best:
        best_path = args.output_dir / f"{args.dataset_name}_best.ckpt"
        best_checkpoint_state: Dict[str, object] = {
            "model": best_state,
            "epoch": last_epoch,
            "best_val_loss": best_val_loss,
            "history": history,
        }
        if scheduler is not None:
            best_checkpoint_state["scheduler"] = scheduler.state_dict()
        save_checkpoint(best_path, best_checkpoint_state)
        print(f"Best validation loss: {best_val_loss:.4f} (saved to {best_path})")

    history_path = args.output_dir / f"{args.dataset_name}_history.json"
    with history_path.open("w", encoding="utf-8") as handle:
        json.dump(history, handle, indent=2)

    plot_path = plot_loss_curves(history, args.output_dir, args.dataset_name)
    if plot_path is not None:
        print(f"Saved loss curve to {plot_path}")

    config_path = args.output_dir / f"{args.dataset_name}_config.json"
    serializable_args = {key: (str(value) if isinstance(value, Path) else value) for key, value in vars(args).items()}
    with config_path.open("w", encoding="utf-8") as handle:
        json.dump(serializable_args, handle, indent=2)

    total_elapsed = time.perf_counter() - training_start
    print(f"Training artifacts written to {args.output_dir}")
    print(f"Total training time: {total_elapsed:.2f}s")


def main(argv: Sequence[str] | None = None, default_overrides: Optional[Dict[str, object]] = None) -> None:
    """CLI entry point supporting optional default overrides."""
    parser = build_arg_parser()
    if default_overrides:
        parser.set_defaults(**default_overrides)
    args = parser.parse_args(argv)
    if args.model_size:
        size_map = {
            "tiny": "orb-d3-xs-v2",
            "small": "orb-d3-sm-v2",
            "full": "orb-v2",
        }
        args.base_model = size_map[args.model_size]
    if args.dataset_name is None:
        parser.error("--dataset-name is required")
    if args.db_path is None:
        parser.error("--db-path is required")
    run_training(args)


if __name__ == "__main__":
    main()
