name: recycling4vlalignment
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda
  - numpy
  - scipy
  - scikit-learn
  - pillow
  - matplotlib
  - tqdm
  - psutil
  - joblib
  - nltk
  - pip
  - pip:
      - timm
      - transformers
      - sentence-transformers
      - datasets
      - torchgeo
      - cca-zoo
      - omegaconf
