[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sae_tools"
version = "0.1.0"
description = "Analysis framework for SAE activations"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "sae-lens",
    "python-dotenv",
    "datasets",
    "matplotlib",
    "scikit-learn"
]

[tool.setuptools.packages.find]
where = ["src"]