algorithm:
  name: FedFewS
  params:
    num_server_models: 3
experiment:
  name: cifar100_fedfews_noniid_dir_20_a0p5
  description:
    CIFAR-100 - Dirichlet(α=0.5) - 20 clients - FedFewS (STCH-Set dual-layer
    weights)
  goal: ours
