CONFIG = {'entrypoint': 'conformal_model.scale.config.run:run',
 'pass_namespace': True,
 'args': {'workers': 0,
          'num_threads': 1,
          'alphas': [0.05, 0.1, 0.2],
          'epochs': 30,
          'batch_size': 16,
          'patience': 3,
          'grad_clip_val': 5,
          'val_len': 0.1,
          'lr': 0.0008,
          'weight_decay': 0.0001,
          'lr_scheduler': {'name': 'MultiStepLR',
                           'hparams': {'gamma': 0.5, 'milestones': [5, 8]}},
          'device': 'cuda',
          'early_stop_metric': 'val_loss',
          'early_stop_min_delta': 0.0,
          'scale_axis': 'graph',
          'apply_scaler': True,
          'add_exogenous': False,
          'target_as_input': False,
          
          # 'src_dir': 'logs\\base\\la\\dcrnn\\2026-01-24\\21-15-42',
          # 'src_dir': 'logs/base/la/stgnn/2026-01-17/22-06-51',
          'src_dir': 'logs/base/la/stgnn/2026-01-14/14-40-13',
            # 'src_dir': 'logs/base/la/stgnn/2026-01-13/21-37-20',
          # 'src_dir': 'logs/base/la/stgnn/2026-01-12/21-31-17',
        #   'src_dir':  'logs/base/la/rnn/2026-01-13/00-23-35',
            # 'src_dir': 'logs/base/la/transformer/2026-01-29/11-47-41',
          'dataset': {'name': 'la',
                      'connectivity': {'method': 'distance',
                                       'threshold': 0.1,
                                       'include_self': False,
                                       'layout': 'dense'}},
          'window': 12,
          'horizon': 1,
          'stride': 1,
          'delay': 0,
          'scale_target': False,
          'model': {'name': 'scale',
                    'hparams': {'model': {'n_scales': 4,
                                          'kernel_type': 'mexican_hat',
                                          'n_high_scales': None,
                                          'backbone_out_dim': 128,
                                          'enable_gating': True,
                                          'backbone': {'node_dim': 128,
                                                       'embed_dim': 128,
                                                       'num_layer': 5,
                                                       'temp_dim_tid': 128,
                                                       'temp_dim_diw': 128,
                                                       'time_of_day_size': 288,
                                                       'day_of_week_size': 7},
                                          'backbone_kwargs': {}},
                                'loss': {'crossing_penalty': 15.0, 'smoothness_weight': 0.5},
                                }},
          'run': {'dir': 'logs/scale/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}'}}}
