name: bias-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - anthropic
  - tqdm
  - openai
  - pytorch
  - regex
  - mypy
  - numpy
  - prompt_toolkit
  - pyyaml
  - pydantic
  - python-levenshtein
  - tiktoken
  - transformers
  - pandas
  - seaborn
  - selenium
  - xmltodict
  - tokenizers>=0.13.3
  - matplotlib
  - scikit-learn
  - requests
  - pytorch
  - pip:
      - datasets
      - google-cloud-aiplatform
      - pyinputplus
      - accelerate
      - sentence-transformers
      - gradio
      - sortedcontainers
      - duckdb
      - cmcrameri
      - together
      - plotly>=5.0.0
      - dash>=2.10.0
      - dash-bootstrap-components>=1.4.0
      - python-dateutil>=2.8.0
      - pyarrow>=10.0.0
      - rapidfuzz
      - Levenshtein
      - matplotlib-set-diagrams
