# -*- coding: utf-8 -*-
"""scvi_larry_top200_train_test_final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpUy5ctfAec2TqvSN9xr0fcv43FlXsth

**1. Change the directory to the google drive**
"""

from google.colab import drive
drive.mount('/content/drive')
import os
os.chdir('/content/drive/My Drive/Colab Notebooks/scvi_test/scvi_embeddings')

!pwd

"""**2. Install the packages for scCL**"""

# Install required packages
!pip install scanpy scvi-tools seaborn torch anndata scikit-misc numpy

"""**get the embedding**"""

import os
import tempfile
import scanpy as sc
import scvi
import seaborn as sns
import torch
import anndata as ad

"""**4. Run scvi**"""

scvi.settings.seed = 0
print("Last run with scvi-tools version:", scvi.__version__)

# Commented out IPython magic to ensure Python compatibility.
sc.set_figure_params(figsize=(6, 6), frameon=False)
sns.set_theme()
torch.set_float32_matmul_precision("high")
save_dir = tempfile.TemporaryDirectory()

# %config InlineBackend.print_figure_kwargs={"facecolor": "w"}
# %config InlineBackend.figure_format="retina"

adata = ad.read_h5ad(f'/content/drive/MyDrive/Colab Notebooks/data/Larry_scvi_train_200.h5ad')
print("adata.X.shape:", adata.X.shape)

# sc.pp.filter_genes(adata, min_counts=3)

adata.shape

adata.layers["counts"] = adata.X.copy()  # preserve counts
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
adata.raw = adata  # freeze the state in `.raw`

sc.pp.highly_variable_genes(
    adata,
    n_top_genes=2000,
    subset=True,
    layer="counts",
    flavor="seurat_v3",
    batch_key=None,
)

scvi.model.SCVI.setup_anndata(
    adata,
    layer="counts",
)

model = scvi.model.SCVI(adata)

model

model.train()

SCVI_LATENT_KEY = "X_scVI"

latent = model.get_latent_representation()
adata.obsm[SCVI_LATENT_KEY] = latent
latent.shape

type(latent)

import numpy as np
np.save(f'Larry_scvi_train_200_embeddings.npy', latent)

"""### test"""

test_adata = ad.read_h5ad(f'/content/drive/MyDrive/Colab Notebooks/data/Larry_scvi_test_200.h5ad')

# Assuming your test adata is already loaded as test_adata
test_adata.layers["counts"] = test_adata.X.copy()
# Get the latent representation for the test data
test_latent = model.get_latent_representation(test_adata)

# Optionally, save the test latent representation to a file
np.save('Larry_scvi_test_200_embeddings.npy', test_latent)

# You can also add the latent representation back to the test adata object if needed
SCVI_LATENT_KEY = "X_scVI_test"
test_adata.obsm[SCVI_LATENT_KEY] = test_latent

# Check the shape of the latent representation
print(test_latent.shape)