name: scgfm
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda
  - pyg
  - numpy
  - scipy
  - scikit-learn
  - networkx
  - tqdm
  - pyyaml
  - pytest
  - pip
  - pip:
      - POT

