algorithm:
  name: FedFewS
  params:
    num_server_models: 5
experiment:
  name: cifar10_fedfews_k5_noniid_dir_20_a0p5
  description: CIFAR-10 - Dirichlet(α=0.5) - 20 clients - FedFewS (K=5)
  goal: k5