algorithm:
  name: FedFewS
  params:
    num_server_models: 8
experiment:
  name: cifar10_fedfews_k8_noniid_dir_20_a0p5
  description: CIFAR-10 - Dirichlet(α=0.5) - 20 clients - FedFewS (K=8)
  goal: k8