[project]
name = "blip"
version = "0.0.1"
description = "INSERT"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [{ name = "Dario Coscia", email = "dariocos99@gmail.com" }]
dependencies = [
    "torch",
    "torch_geometric",
    "tensorboard",
    "matplotlib",
    "orb-models==0.5.5",
    "nff @ git+https://github.com/dario-coscia/NeuralForceField.git"
]

[tool.setuptools.packages.find]
include = ["blip*"]
