"""
Plot CSR threshold sensitivity curves from sweep CSV files.

Creates a two-panel figure:
  1. Accuracy vs threshold
  2. Detection rate vs threshold

Each point is annotated with its numeric value for easy inspection.
"""

import argparse
import os
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


def parse_args():
    parser = argparse.ArgumentParser(description="Plot threshold sweep curves")
    parser.add_argument(
        "--csvs",
        nargs="+",
        required=True,
        help="Input CSV files generated by sweep_detect_thresh.py",
    )
    parser.add_argument(
        "--labels",
        nargs="+",
        default=None,
        help="Display labels matching the input CSVs",
    )
    parser.add_argument(
        "--output_prefix",
        required=True,
        help="Output path prefix without extension",
    )
    parser.add_argument(
        "--clean_csv",
        default=None,
        help="Optional clean-sample threshold sweep CSV",
    )
    parser.add_argument(
        "--clean_label",
        default="Clean ImageNet",
        help="Legend label for the clean curve",
    )
    return parser.parse_args()


def infer_label(path):
    name = Path(path).stem
    for eps in ["1_255", "2_255", "4_255"]:
        if f"apgd_{eps}_" in name:
            return f"APGD {eps.replace('_', '/')}"
    return name


def load_frames(csvs, labels=None):
    frames = []
    resolved_labels = labels or [infer_label(path) for path in csvs]

    if len(resolved_labels) != len(csvs):
        raise ValueError("The number of labels must match the number of CSV files")

    for path, label in zip(csvs, resolved_labels):
        df = pd.read_csv(path).copy()
        df["series_label"] = label
        frames.append(df)

    return pd.concat(frames, ignore_index=True), resolved_labels


def annotate_points(ax, df, x_col, y_col, text_col, offsets):
    for idx, label in enumerate(df["series_label"].unique()):
        sub = df[df["series_label"] == label].sort_values(x_col)
        x_offset, y_offset = offsets[idx % len(offsets)]

        for _, row in sub.iterrows():
            ax.annotate(
                f"{row[text_col]:.1f}",
                (row[x_col], row[y_col]),
                textcoords="offset points",
                xytext=(x_offset, y_offset),
                ha="center",
                fontsize=8,
                color=ax.lines[idx].get_color(),
                bbox=dict(boxstyle="round,pad=0.15", fc="white", ec="none", alpha=0.75),
            )


def annotate_single_series(ax, df, x_col, y_col, text_col, color, offset=(0, 10)):
    sub = df.sort_values(x_col)
    for _, row in sub.iterrows():
        ax.annotate(
            f"{row[text_col]:.1f}",
            (row[x_col], row[y_col]),
            textcoords="offset points",
            xytext=offset,
            ha="center",
            fontsize=8,
            color=color,
            bbox=dict(boxstyle="round,pad=0.15", fc="white", ec="none", alpha=0.75),
        )


def make_plot(df, labels, output_prefix, clean_df=None, clean_label="Clean ImageNet"):
    sns.set_theme(style="whitegrid", context="talk")

    palette = {
        labels[0]: "#D55E00",
        labels[1]: "#0072B2",
        labels[2]: "#009E73",
    }

    nrows = 3 if clean_df is not None else 2
    fig, axes = plt.subplots(nrows, 1, figsize=(14, 16 if clean_df is not None else 12), sharex=True)
    metrics = [
        ("accuracy_percent", "Accuracy (%)", [(0, 10), (0, -16), (0, 18)]),
        ("detection_rate_percent", "Detection Rate (%)", [(0, 10), (0, -16), (0, 18)]),
    ]

    for ax, (metric, y_label, offsets) in zip(axes, metrics):
        sns.lineplot(
            data=df,
            x="threshold",
            y=metric,
            hue="series_label",
            style="series_label",
            markers=True,
            dashes=False,
            linewidth=2.5,
            markersize=8,
            palette=palette,
            ax=ax,
        )
        annotate_points(ax, df, "threshold", metric, metric, offsets)
        ax.set_ylabel(y_label)
        ax.set_xlabel("Threshold")
        ax.set_xticks(sorted(df["threshold"].unique()))
        ax.set_xlim(df["threshold"].min() - 0.005, df["threshold"].max() + 0.005)
        ax.legend(title="Series", loc="best")

    axes[0].set_title("CLIP-B-16 + CSR on ImageNet APGD Samples")
    axes[1].set_title("Threshold Sensitivity with Per-Point Values")

    if clean_df is not None:
        clean_ax = axes[2]
        clean_color = "#CC79A7"
        clean_df = clean_df.sort_values("threshold")
        clean_ax.plot(
            clean_df["threshold"],
            clean_df["accuracy_percent"],
            marker="o",
            linewidth=2.5,
            markersize=8,
            color=clean_color,
            label=clean_label,
        )
        annotate_single_series(
            clean_ax,
            clean_df,
            "threshold",
            "accuracy_percent",
            "accuracy_percent",
            color=clean_color,
            offset=(0, 10),
        )
        clean_ax.set_ylabel("Clean Accuracy (%)")
        clean_ax.set_xlabel("Threshold")
        clean_ax.set_xticks(sorted(clean_df["threshold"].unique()))
        clean_ax.set_xlim(clean_df["threshold"].min() - 0.005, clean_df["threshold"].max() + 0.005)
        clean_ax.legend(title="Series", loc="best")
        clean_ax.set_title("Benign Sample Accuracy with Per-Point Values")

    plt.tight_layout()

    png_path = f"{output_prefix}.png"
    pdf_path = f"{output_prefix}.pdf"
    fig.savefig(png_path, dpi=220, bbox_inches="tight")
    fig.savefig(pdf_path, bbox_inches="tight")
    plt.close(fig)
    return png_path, pdf_path


def main():
    args = parse_args()
    df, labels = load_frames(args.csvs, args.labels)
    clean_df = pd.read_csv(args.clean_csv) if args.clean_csv else None
    output_dir = os.path.dirname(args.output_prefix)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    png_path, pdf_path = make_plot(
        df,
        labels,
        args.output_prefix,
        clean_df=clean_df,
        clean_label=args.clean_label,
    )
    print(f"[Plot] PNG: {png_path}")
    print(f"[Plot] PDF: {pdf_path}")


if __name__ == "__main__":
    main()
