name: rfm

channels:
  - nvidia
  - conda-forge
  - menpo
  - defaults

dependencies:
  - python=3.10

  - wandb

  - glew
  - mesalib
  - glfw3

  - pip>=23
  - pip:
      - patchelf==0.17.2.4
      - jax[cuda12]==0.6.2
      - flax==0.10.7
      - optax==0.2.6
      - termcolor==3.2.0
      - gymnasium==1.2.2
      - dm_env==1.6
      - dm_control==1.0.34
