c_data: 1
c_residual: 0.01
c_ineq: 0.001
lambda_opt: 0.1
diff_steps: 100
x0_estimation: 'mean'
ddim_steps: 0
residual_grad_guidance: False
correction_mode: xt
M_correction: 0
N_correction: 0
gov_eqs: mechanics
fd_acc: 2

use_projection_heads: False
projection_positions: []
projection_hidden_dim: 0
c_projection: 0.0

run_name: mechanics.pidm.unet
train_iterations: 300000
train_batch_size: 8
wandb_track: False
load_model_flag: False
resume_step: 0
checkpoint_save_freq: 5000
sample_freq: 5000
test_eval_freq: 1000
log_freq: 20
no_samples: 8
ema_start: 1000
use_ema_for_eval: True
collect_physics_per_step: False

pixels_per_dim: 64
turbulent_data_path: ./data/ch_2Dxysec.pickle
turbulent_train_fraction: 0.9
lambda_wall: 0.1
lambda_smooth: 0.01
lambda_gradient: 0.0
lambda_near_wall: 0.0
near_wall_rows: 3
