algorithm:
  name: FedFewS
  params:
    num_server_models: 3
training:
  global_rounds: 125
  local_epochs: 16
experiment:
  name: cifar10_fedfews_le16_gr125_noniid_dir_20_a0p5
  description: CIFAR-10 - FedFewS - Local Epochs=16, Global Rounds=125
  goal: le16_gr125