algorithm:
  name: FedFewS
  params:
    num_server_models: 3
training:
  global_rounds: 1000
  local_epochs: 2
experiment:
  name: cifar10_fedfews_le2_gr1000_noniid_dir_20_a0p5
  description: CIFAR-10 - FedFewS - Local Epochs=2, Global Rounds=1000
  goal: le2_gr1000