algorithm:
  name: FedFewS
  params:
    num_server_models: 3
training:
  global_rounds: 500
  local_epochs: 4
experiment:
  name: cifar10_fedfews_le4_gr500_noniid_dir_20_a0p5
  description: CIFAR-10 - FedFewS - Local Epochs=4, Global Rounds=500
  goal: le4_gr500