algorithm:
  name: FedFewS
  params:
    num_server_models: 3
training:
  global_rounds: 250
  local_epochs: 8
experiment:
  name: cifar10_fedfews_le8_gr250_noniid_dir_20_a0p5
  description: CIFAR-10 - FedFewS - Local Epochs=8, Global Rounds=250
  goal: le8_gr250