algorithm:
  name: FedFewS
  params:
    num_server_models: 3
training:
  global_rounds: 2000
  local_epochs: 1
experiment:
  name: cifar10_fedfews_le1_gr2000_noniid_dir_20_a0p5
  description: CIFAR-10 - FedFewS - Local Epochs=1, Global Rounds=2000
  goal: le1_gr2000