"""
EdgeJudge base class: provides a unified soft-scoring interface for edges generated by the Actor.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Tuple

from AgentTailor.ATNetwork.Critics import Encoder


class EdgeJudge(ABC):
    @abstractmethod
    def score_edge(
        self,
        encoder: Encoder,
        edge_input: Dict[str, Any],
        task_text: str,
        feedback_summary: str,
        pass_ratio: float,
        unit_tests: List[str],
        test_state: Tuple[bool, ...],
    ) -> float:
        raise NotImplementedError


__all__ = ["EdgeJudge"]

