accelerate launch src/train_infdiff.py \
    --sd_path="./stabilityai/sd-turbo" \
    --output_dir="./HiDRA" \
    --dataset_folder="./datasets/HM-TIR" \
    --train_image_prep="randomcrop_512x512_hflip" \
    --resolution=512 \
    --train_batch_size=2 \
    --enable_xformers_memory_efficient_attention \
    --gradient_accumulation_steps=1 \
    --num_training_epochs=50 \
    --max_train_steps=30000 \
    --eval_freq=5000 \
    --viz_freq 50 \
    --report_to "wandb" --tracker_project_name "HiDRA"
