# Fixed Settings
target: 'nodes' # or time, nodes, gap or accuracy
train_seed: 666666
valid_seed: 666666
train_num: 4
valid_num: 8
max_workers: 8

# Practical Settings
setcover:
  stage1_timeout: 600
  stage2_timeout: 2000
  rpb: false
  parameter_opt: true
  n_calls: 80  
  n_initial: 10

cauctions:
  stage1_timeout: 600
  stage2_timeout: 2000
  rpb: false
  parameter_opt: true
  n_calls: 100   
  n_initial: 10

facilities:
  stage1_timeout: 1000
  stage2_timeout: 3000
  rpb: false
  parameter_opt: true
  n_calls: 16
  n_initial: 2

indset:
  stage1_timeout: 1000
  stage2_timeout: 2000
  rpb: false
  parameter_opt: true
  n_calls: 50
  n_initial: 10