name: approximate-equivariance-projection
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - scipy
  - pandas
  - scikit-image
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - pyyaml
  - h5py
  - pillow
  - tensorboard
  - pytest
  - ipython
  - pip
  - pip:
      - e2cnn
      - escnn
      - wandb
      - tensorboardX
      - lmdb==1.3.0
      - opencv-python==4.5.5.64
      - medmnist
