seed_everything: true
sample_every: 1000
name: "svae_large"
trainer:
  accelerator: "auto"
  benchmark: true
  max_steps: 100000
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "sed"  # TODO: check project
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "{step:06}"
        verbose: true
        save_last: true
        save_top_k: 1
        monitor: "val/loss"
model:
  class_path: sed.models.vae.svae.SVAE
  init_args:
    num_layers: 6
    d_model: 256
    d_ff: 1024
    h: 4
    lr: null
