hp:
  model: ResNet18
  dataset: TinyImageNet
  T: 18
  act_fn: relu
  batch_size: 128
  epochs: 50
  precision_type: PC
  Forward_type: PC
  alpha: 1.0
  se_flag: true
  optim:
    w:
      lr: 1.6572780503636338e-05
      wd: 3.47108337118143e-05
    x:
      lr: 0.011168817700767145
      momentum: 0.5
