hp:
  model: ResNet10
  dataset: CIFAR10
  T: 12
  act_fn: leaky_relu
  batch_size: 128
  epochs: 50
  precision_type: PC
  Forward_type: PC
  alpha: 1.0
  se_flag: true
  optim:
    w:
      lr: 0.00010199619221523417
      wd: 0.0014565520321237998
    x:
      lr: 0.028695847013581143
      momentum: 0.1
