hp:
  model: ResNet10
  dataset: TinyImageNet
  T: 10
  act_fn: leaky_relu
  batch_size: 128
  epochs: 50
  precision_type: PC
  Forward_type: PC
  alpha: 1.0
  se_flag: true
  optim:
    w:
      lr: 0.0001243854536025437
      wd: 3.9314898633089115e-05
    x:
      lr: 0.02140798753335888
      momentum: 0.1
