hp:
  model: ResNet10
  dataset: CIFAR100
  T: 12
  act_fn: gelu
  batch_size: 128
  epochs: 50
  precision_type: PC
  Forward_type: PC
  alpha: 1.0
  se_flag: true
  optim:
    w:
      lr: 0.00027676461163931475
      wd: 3.0323167908335362e-05
    x:
      lr: 0.01542046214228625
      momentum: 0.1
