hp:
  model: ResNet18
  dataset: CIFAR10
  T: 18
  act_fn: gelu
  batch_size: 128
  epochs: 50
  precision_type: PC
  Forward_type: PC
  alpha: 1.0
  se_flag: true
  optim:
    w:
      lr: 2.268875405252464e-05
      wd: 2.5240613909522985e-05
    x:
      lr: 0.6111228660579101
      momentum: 0.5
