hp:
  model: VGG10
  dataset: CIFAR10
  T: 13
  act_fn: hard_tanh
  batch_size: 128
  epochs: 50
  precision_type: PC
  Forward_type: PC
  alpha: 1.0
  se_flag: false
  optim:
    w:
      lr: 0.00014446329952752017
      wd: 0.00018737826177760568
    x:
      lr: 0.05003444231309284
      momentum: 0.1
