hp:
  model: VGG10
  dataset: CIFAR100
  T: 13
  act_fn: hard_tanh
  batch_size: 128
  epochs: 50
  precision_type: PC
  Forward_type: PC
  alpha: 1.0
  se_flag: false
  optim:
    w:
      lr: 0.0004085229559794695
      wd: 1.1815526333940613e-05
    x:
      lr: 0.012745966853398807
      momentum: 0.9
