hp:
  model: VGG5
  dataset: CIFAR10
  T: 5
  act_fn: gelu
  batch_size: 128
  epochs: 50
  precision_type: PC
  Forward_type: PC
  alpha: 1.0
  se_flag: true
  optim:
    w:
      lr: 0.0001
      wd: 1.0e-05
    x:
      lr: 0.01
      momentum: 0.99
