hp:
  model: VGG5
  dataset: CIFAR100
  T: 12
  act_fn: hard_tanh
  batch_size: 128
  epochs: 50
  precision_type: PC
  Forward_type: PC
  alpha: 1.0
  se_flag: false
  optim:
    w:
      lr: 0.00021550147504766553
      wd: 0.007599378216624812
    x:
      lr: 0.011510981082033004
      momentum: 0.25
