name: env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.10.8
  - numpy=1.26.4
  - pandas
  - seaborn
  - scikit-learn
  - tqdm
  - pytorch=2.6.0
  - pip
  - typing
  - ipykernel
  - pip:
      - numpy<2
      - cvxpy
      - cvxpylayers
